---
title: "malefemale"
output: html_document
date: "2024-05-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r} 
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(ggstatsplot)
```


```{r}
gender_data_cgnt <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/controlgroup/Ergebnis Vergleich männl_weibl/gender_data_controlgroup.xlsx",
           sheet = 1, skip = 1)
```


```{r}
library(dplyr)
gender_data_cgnt1 <- gender_data_cgnt %>% 
  melt(cols = c("Male", "Female"),
       variable.name = "Gender") %>% 
  dplyr::filter(Treatment == "Leber_Para")


  
```

## patient data###
```{r}
patientidentifier <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/controlgroup/Ergebnis Vergleich männl_weibl/gender_data_controlgroup.xlsx",
           sheet = 1, skip = 1 ) %>% 
  filter(Treatment == "Leber_Para") %>% 
  pivot_longer(cols = 3:4,
               names_to = "gender",
               values_to = "numberofpatient") %>% 
  filter(numberofpatient== 1) 

## unknown gender dataframe
#test <- tibble(`Edited_BfArM Nummer2`=c("9042861","9044899"),
#                     Treatment=c("Leber_Dic``lo","Leber_Diclo"),
#                     gender=c("Unknown","Unknown"),
#                     numberofpatient=c(1,1))

#patientidentifier <- rbind(patientidentifier,test)
  

```

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier
gptaltdata_long_cgnt <- gpt_rawdata_cgnt %>%
  tidyr::pivot_longer(cols = -c("Edited_BfArM Nummer2", "Treatment"), 
               names_to = "Attribute", 
               values_to = "labreads")

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- gptaltdata_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(Attribute, "_From Start|Day_Unknown")) ####NEW####

# Step 3: Count occurrences, preserving the identifier
counts_data_cgnt <- filtered_data_cgnt %>%
  group_by(Attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
gptaltdata_with_counts <- filtered_data_cgnt %>%
  left_join(counts_data_cgnt, by = "Attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 filtered_data_cgnt_with_min_counts <- gptaltdata_with_counts %>%
  #filter(count >= 3) %>%      ####NEW####
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(filtered_data_cgnt_with_min_counts)

  
```

## alt data greater than 5 counts in all attribute###
```{r}
lparaalt_data_cgnt <- left_join(patientidentifier,filtered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```


```{r}
lparaalt_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```


```{r}
dd <- lparaalt_data_cgnt %>% 
  group_by(gender)
  
ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of ALT for male, female and unknown gender",  ###NEW###
  type = "np",
  ylab = "ALT U/L",
  ggtheme = theme_classic()
)

```




##############################################################################
##ast##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier
astaltdata_long_cgnt <- got_rawdata_cgnt %>%
  tidyr::pivot_longer(cols = -c("Edited_BfArM Nummer2", "Treatment"), 
               names_to = "Attribute", 
               values_to = "labreads")

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- astaltdata_long_cgnt %>%
  filter(Treatment == "Leber_Para") %>% 
  filter(!str_detect(Attribute, "_From Start|Day_Unknown"))

# Step 3: Count occurrences, preserving the identifier
astcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(Attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
astdata_with_counts <- filtered_data_cgnt %>%
  left_join(astcounts_data_cgnt, by = "Attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 astfiltered_data_cgnt_with_min_counts <- astdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(astfiltered_data_cgnt_with_min_counts)

  
```




```{r}
lparaast_data_cgnt <- left_join(patientidentifier,astfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
lparaast_data_cgnt
```


```{r}
lparaast_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```


```{r}
dd <- lparaast_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of AST for male, female and unknown gender",  ###NEW###
  type = "np",
  ylab = "AST U/L",
  ggtheme = theme_classic()
)

```

##############################################################################
##ck##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier
ckdata_long_cgnt <- ck_rawdata_cgnt %>%
  tidyr::pivot_longer(cols = -c("Edited_BfArM Nummer2", "Treatment"), 
               names_to = "Attribute", 
               values_to = "labreads")

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- ckdata_long_cgnt %>%
  filter(Treatment == "Leber_Para") %>% 
  filter(!str_detect(Attribute, "_From Start|Day_Unknown"))

# Step 3: Count occurrences, preserving the identifier
ckcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(Attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
ckdata_with_counts <- filtered_data_cgnt %>%
  left_join(ckcounts_data_cgnt, by = "Attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 ckfiltered_data_cgnt_with_min_counts <- ckdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(ckfiltered_data_cgnt_with_min_counts)

  
```




```{r}
lparack_data_cgnt <- left_join(patientidentifier,ckfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
lparack_data_cgnt
```


```{r}
lparack_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```


```{r}
dd <- lparack_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of CK for male, female and unknown gender",  ###NEW###
  type = "np",
  ylab = "CK U/L",
  ggtheme = theme_classic()
)

```









##############################################################################
##quick##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- quick_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
quickcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
quickdata_with_counts <- filtered_data_cgnt %>%
  left_join(quickcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 quickfiltered_data_cgnt_with_min_counts <- quickdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(quickfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparaquick_data_cgnt <- left_join(patientidentifier,quickfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```


```{r}
lparaquick_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaquick_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of quick for male, female and unknown gender",
  type = "np",
  ylab = "quick %",
  ggtheme = theme_classic()
)

```


##############################################################################
##inr##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- inr_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
inrcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
inrdata_with_counts <- filtered_data_cgnt %>%
  left_join(inrcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 inrfiltered_data_cgnt_with_min_counts <- inrdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(inrfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparainr_data_cgnt <- left_join(patientidentifier,inrfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```


```{r}
lparainr_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparainr_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of INR for male, female and unknown gender",
  type = "np",
  ylab = "INR",
  ggtheme = theme_classic()
)

```
##############################################################################
##ptt##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- ptt_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
pttcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
pttdata_with_counts <- filtered_data_cgnt %>%
  left_join(pttcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 pttfiltered_data_cgnt_with_min_counts <- pttdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(pttfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparaptt_data_cgnt <- left_join(patientidentifier,pttfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```


```{r}
lparaptt_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaptt_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of PTT for male, female and unknown gender",
  type = "np",
  ylab = "PTT",
  ggtheme = theme_classic()
)

```

##############################################################################
##Leukozyten##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- leukozyten_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
leukozytencounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
leukozytendata_with_counts <- filtered_data_cgnt %>%
  left_join(leukozytencounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 leukozytenfiltered_data_cgnt_with_min_counts <- leukozytendata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(leukozytenfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparaleukozyten_data_cgnt <- left_join(patientidentifier,leukozytenfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparaleukozyten_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaleukozyten_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of leucocytes for male, female and unknown gender",
  type = "np",
  ylab = "Leucocytes Cells/ul",
  ggtheme = theme_classic()
)

```

##############################################################################
##ggt##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- ggt_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
ggtcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
ggtdata_with_counts <- filtered_data_cgnt %>%
  left_join(ggtcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 ggtfiltered_data_cgnt_with_min_counts <- ggtdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(ggtfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparaggt_data_cgnt <- left_join(patientidentifier,ggtfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparaggt_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaggt_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of GGT for male, female and unknown gender",
  type = "np",
  ylab = "GGT U/L",
  ggtheme = theme_classic()
)

```

##############################################################################
##ldh##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- ldh_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
ldhcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
ldhdata_with_counts <- filtered_data_cgnt %>%
  left_join(ldhcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 ldhfiltered_data_cgnt_with_min_counts <- ldhdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(ldhfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparaldh_data_cgnt <- left_join(patientidentifier,ldhfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparaldh_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaldh_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of LDH for male, female and unknown gender",
  type = "np",
  ylab = "LDH U/L",
  ggtheme = theme_classic()
)

```

##############################################################################
##hb##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- hb_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
hbcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
hbdata_with_counts <- filtered_data_cgnt %>%
  left_join(hbcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 hbfiltered_data_cgnt_with_min_counts <- hbdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(hbfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparahb_data_cgnt <- left_join(patientidentifier,hbfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparahb_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparahb_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of HB for male, female and unknown gender",
  type = "np",
  ylab = "HB g/dl",
  ggtheme = theme_classic()
)

```

##############################################################################
##totales Bilirubin##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- total_bilirubin_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
totbilicounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
totbilidata_with_counts <- filtered_data_cgnt %>%
  left_join(totbilicounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 totbilifiltered_data_cgnt_with_min_counts <- totbilidata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(totbilifiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparatotbili_data_cgnt <- left_join(patientidentifier,totbilifiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparatotbili_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparatotbili_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of total bilirubin for male, female and unknown gender",
  type = "np",
  ylab = "total Bilirubin mg/dl",
  ggtheme = theme_classic()
)

```
##############################################################################
##direktes Bilirubin##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- direct_bilirubin_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
dirbilicounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
dirbilidata_with_counts <- filtered_data_cgnt %>%
  left_join(dirbilicounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 dirbilifiltered_data_cgnt_with_min_counts <- dirbilidata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(dirbilifiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparadirbili_data_cgnt <- left_join(patientidentifier,dirbilifiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparadirbili_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparadirbili_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of direct bilirubin for male, female and unknown gender",
  type = "np",
  ylab = "direct Bilirubin mg/dl",
  ggtheme = theme_classic()
)

```

##############################################################################
##Gesamteiweiß##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- gesamteiweiß_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
gescounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
gesdata_with_counts <- filtered_data_cgnt %>%
  left_join(gescounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 gesfiltered_data_cgnt_with_min_counts <- gesdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(gesfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparages_data_cgnt <- left_join(patientidentifier,gesfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparages_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparages_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of total protein for male, female and unknown gender",
  type = "np",
  ylab = "total protein g/dl",
  ggtheme = theme_classic()
)

```



##############################################################################
##AP##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- ap_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
apcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
apdata_with_counts <- filtered_data_cgnt %>%
  left_join(apcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 apfiltered_data_cgnt_with_min_counts <- apdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(apfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparaap_data_cgnt <- left_join(patientidentifier,apfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparaap_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaap_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of AP for male, female and unknown gender",
  type = "np",
  ylab = "AP U/L",
  ggtheme = theme_classic()
)

```

##############################################################################
##Keratinin##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- kreatinin_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
kreacounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
kreadata_with_counts <- filtered_data_cgnt %>%
  left_join(kreacounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 kreafiltered_data_cgnt_with_min_counts <- kreadata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(kreafiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparakrea_data_cgnt <- left_join(patientidentifier,kreafiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparakrea_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparakrea_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of Creatinine for male, female and unknown gender",
  type = "np",
  ylab = "Creatinine mg/dl",
  ggtheme = theme_classic()
)

```

##############################################################################
##Lipase##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- lipase_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
lipacounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
lipadata_with_counts <- filtered_data_cgnt %>%
  left_join(lipacounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 lipafiltered_data_cgnt_with_min_counts <- lipadata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(lipafiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparalipa_data_cgnt <- left_join(patientidentifier,lipafiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparalipa_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparalipa_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of Lipase for male, female and unknown gender",
  type = "np",
  ylab = "Lipase mg/dl",
  ggtheme = theme_classic()
)

```



##############################################################################
##CRP##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- crp_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
crpcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
crpdata_with_counts <- filtered_data_cgnt %>%
  left_join(crpcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 crpfiltered_data_cgnt_with_min_counts <- crpdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(crpfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparacrp_data_cgnt <- left_join(patientidentifier,crpfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparacrp_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparacrp_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of CRP for male, female and unknown gender",
  type = "np",
  ylab = "CRP mg/l",
  ggtheme = theme_classic()
)

```

##############################################################################
##Harnstoff##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- harnstoff_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
hstcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
hstdata_with_counts <- filtered_data_cgnt %>%
  left_join(hstcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 hstfiltered_data_cgnt_with_min_counts <- hstdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(hstfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparahst_data_cgnt <- left_join(patientidentifier,hstfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparahst_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparahst_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of Urea for male, female and unknown gender",
  type = "np",
  ylab = "Urea mg/dl",
  ggtheme = theme_classic()
)

```

##########################################################################################Erythrozyten##########################

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- erythrozyten_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
erycounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
erydata_with_counts <- filtered_data_cgnt %>%
  left_join(erycounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 eryfiltered_data_cgnt_with_min_counts <- erydata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(eryfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparaery_data_cgnt <- left_join(patientidentifier,eryfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparaery_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaery_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of erythrocytes for male, female and unknown gender",
  type = "np",
  ylab = "Erythrocytes cells/ul",
  ggtheme = theme_classic()
)

```



##############################################################################
##Thrombozyten##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- thrombozyten_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
thrombcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
thrombdata_with_counts <- filtered_data_cgnt %>%
  left_join(thrombcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 thrombfiltered_data_cgnt_with_min_counts <- thrombdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(thrombfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparathromb_data_cgnt <- left_join(patientidentifier,thrombfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparathromb_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparathromb_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of thrombocytes for male, female and unknown gender",
  type = "np",
  ylab = "Thrombocytes Cells/ul",
  ggtheme = theme_classic()
)

```

##############################################################################
##Hämatokrit##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- hämatokrit_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
hktcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
hktdata_with_counts <- filtered_data_cgnt %>%
  left_join(hktcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 hktfiltered_data_cgnt_with_min_counts <- hktdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(hktfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparahkt_data_cgnt <- left_join(patientidentifier,hktfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparahkt_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparahkt_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of HKT for male, female and unknown gender",
  type = "np",
  ylab = "Hematokrit %",
  ggtheme = theme_classic()
)

```

##############################################################################
##Natrium##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- natrium_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
natcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
natdata_with_counts <- filtered_data_cgnt %>%
  left_join(natcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 natfiltered_data_cgnt_with_min_counts <- natdata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(natfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparanat_data_cgnt <- left_join(patientidentifier,natfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparanat_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparanat_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of sodium for male, female and unknown gender",
  type = "np",
  ylab = "Sodium mmol/l",
  ggtheme = theme_classic()
)

```



##############################################################################
##Kalium##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- kalium_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
kalcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
kaldata_with_counts <- filtered_data_cgnt %>%
  left_join(kalcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 kalfiltered_data_cgnt_with_min_counts <- kaldata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(kalfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparakal_data_cgnt <- left_join(patientidentifier,kalfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparakal_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparakal_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of potassium for male, female and unknown gender",
  type = "np",
  ylab = "Potassium mmol/l",
  ggtheme = theme_classic()
)

```

##############################################################################
##Kalzium##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- kalzium_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
calcounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
caldata_with_counts <- filtered_data_cgnt %>%
  left_join(calcounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 calfiltered_data_cgnt_with_min_counts <- caldata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(calfiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparacal_data_cgnt <- left_join(patientidentifier,calfiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparacal_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparacal_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of calcium for male, female and unknown gender",
  type = "np",
  ylab = "Calcium mmol/l",
  ggtheme = theme_classic()
)

```

##############################################################################
##Glucose##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data_cgnt <- glucose_long_cgnt %>%
  filter(Treatment == "Leber_Para")%>% 
  filter(!str_detect(attribute, "_From start|_From Start|Day_Unknown"))  ####NEW####

# Step 3: Count occurrences, preserving the identifier
glucounts_data_cgnt <- filtered_data_cgnt %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
gludata_with_counts <- filtered_data_cgnt %>%
  left_join(glucounts_data_cgnt, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 3
 glufiltered_data_cgnt_with_min_counts <- gludata_with_counts %>%
  #filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 3
print(glufiltered_data_cgnt_with_min_counts)

  
```

```{r}
lparaglu_data_cgnt <- left_join(patientidentifier,glufiltered_data_cgnt_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparaglu_data_cgnt %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaglu_data_cgnt %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  title = "liver_para labvalues of glucose for male, female and unknown gender",
  type = "np",
  ylab = "Glucose mg/dl",
  ggtheme = theme_classic()
)

```


####

