---
title: "Untitled"
output: html_document
date: "2026-04-08"
---

```{r}
library(GGally)
library(dplyr)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(ggstatsplot)
library(ggplot2)
library(performance)
library(car)
```

```{r}
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/hospitalisation")

hospitalisation_data <- read_excel("hospitalisation rawdata.xlsx", sheet = 1)  

hospitalisation_data
```

```{r}
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/age plots")

age_data <- read_excel("age plots full.xlsx", sheet = 1) %>%
  select(1:3)

age_data
```

```{r}
hospitalisation_data_prepared <- hospitalisation_data %>%
  dplyr::select(1,7)
hospitalisation_data_prepared
```

```{r}
hospitalisation_age_data <- left_join(hospitalisation_data_prepared, age_data, by = ("Edited_BfArM Nummer2"))
hospitalisation_age_data
```


```{r}
all_groups_hospitalisation_age_correlation <- hospitalisation_age_data %>% 
  select(`Dauer Krankenhausaufenthalt (Tage)`,age) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "all groups_correlation hospitalisation time and age")

all_groups_hospitalisation_age_correlation
dir.create("plots/corr hosp age", showWarnings = FALSE)
svg("plots/corr hosp age/all groups_corr hospitalisation time and age.svg", height = 6, width = 8)
print(all_groups_hospitalisation_age_correlation)
dev.off()
```


```{r}
# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(age ~ poly(`Dauer Krankenhausaufenthalt (Tage)`, 2, raw = TRUE), data = hospitalisation_age_data)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- hospitalisation_age_data %>% 
  ggplot(aes(x = `Dauer Krankenhausaufenthalt (Tage)`, y = age)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  scale_x_log10() +
  labs(
    title = paste0("all groups_correlation hospitalisation time and age"),
    x = "Hospitalisation time in days (log-scale)",
    y = "Age"
  )

print(p_reg)

dir.create("plots/corr hosp age", showWarnings = FALSE)
svg("plots/corr hosp age/all groups_reg hospitalisation time and age.svg", height = 6, width = 8)
print(p_reg)
dev.off()
```


### Leber_Diclo ###

```{r}
ld_hospitalisation_age_data <- hospitalisation_age_data %>% 
  filter(Treatment == "Leber_Diclo")
```

```{r}
ld_hospitalisation_age_correlation <- ld_hospitalisation_age_data %>% 
  select(`Dauer Krankenhausaufenthalt (Tage)`,age) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "Liver diclo_correlation hospitalisation time and age")

ld_hospitalisation_age_correlation
dir.create("plots/corr hosp age", showWarnings = FALSE)
svg("plots/corr hosp age/ld_corr hospitalisation time and age.svg", height = 6, width = 8)
print(ld_hospitalisation_age_correlation)
dev.off()
```


```{r}
# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(age ~ poly(`Dauer Krankenhausaufenthalt (Tage)`, 2, raw = TRUE), data = ld_hospitalisation_age_data)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- ld_hospitalisation_age_data %>% 
  ggplot(aes(x = `Dauer Krankenhausaufenthalt (Tage)`, y = age)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  scale_x_log10() +
  labs(
    title = paste0("Liver diclo_correlation hospitalisation time and age"),
    x = "Hospitalisation time in days (log-scale)",
    y = "Age"
  )

print(p_reg)

dir.create("plots/corr hosp age", showWarnings = FALSE)
svg("plots/corr hosp age/ld_reg hospitalisation time and age.svg", height = 6, width = 8)
print(p_reg)
dev.off()
```


### Leber_Ibu ###

```{r}
li_hospitalisation_age_data <- hospitalisation_age_data %>% 
  filter(Treatment == "Leber_Ibu")
```

```{r}
li_hospitalisation_age_correlation <- li_hospitalisation_age_data %>% 
  select(`Dauer Krankenhausaufenthalt (Tage)`,age) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "Liver ibu_correlation hospitalisation time and age")

li_hospitalisation_age_correlation
dir.create("plots/corr hosp age", showWarnings = FALSE)
svg("plots/corr hosp age/li_corr hospitalisation time and age.svg", height = 6, width = 8)
print(li_hospitalisation_age_correlation)
dev.off()
```


```{r}
# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(age ~ poly(`Dauer Krankenhausaufenthalt (Tage)`, 2, raw = TRUE), data = li_hospitalisation_age_data)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- li_hospitalisation_age_data %>% 
  ggplot(aes(x = `Dauer Krankenhausaufenthalt (Tage)`, y = age)) +
  geom_point(color = "blue", size = 3, aliha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  scale_x_log10() +
  labs(
    title = paste0("Liver ibu_correlation hospitalisation time and age"),
    x = "Hospitalisation time in days (log-scale)",
    y = "Age"
  )

print(p_reg)

dir.create("plots/corr hosp age", showWarnings = FALSE)
svg("plots/corr hosp age/li_reg hospitalisation time and age.svg", height = 6, width = 8)
print(p_reg)
dev.off()
```






### Leber_Para ###

```{r}
lp_hospitalisation_age_data <- hospitalisation_age_data %>% 
  filter(Treatment == "Leber_Para")
```

```{r}
lp_hospitalisation_age_correlation <- lp_hospitalisation_age_data %>% 
  select(`Dauer Krankenhausaufenthalt (Tage)`,age) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "Liver para_correlation hospitalisation time and age")

lp_hospitalisation_age_correlation
dir.create("plots/corr hosp age", showWarnings = FALSE)
svg("plots/corr hosp age/lp_corr hospitalisation time and age.svg", height = 6, width = 8)
print(lp_hospitalisation_age_correlation)
dev.off()
```


```{r}
# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(age ~ poly(`Dauer Krankenhausaufenthalt (Tage)`, 2, raw = TRUE), data = lp_hospitalisation_age_data)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- lp_hospitalisation_age_data %>% 
  ggplot(aes(x = `Dauer Krankenhausaufenthalt (Tage)`, y = age)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  scale_x_log10() +
  labs(
    title = paste0("Liver para_correlation hospitalisation time and age"),
    x = "Hospitalisation time in days (log-scale)",
    y = "Age"
  )

print(p_reg)

dir.create("plots/corr hosp age", showWarnings = FALSE)
svg("plots/corr hosp age/lp_reg hospitalisation time and age.svg", height = 6, width = 8)
print(p_reg)
dev.off()
```




