---
title: "Untitled"
output: html_document
date: "2026-04-08"
---

```{r}
library(GGally)
library(dplyr)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(ggstatsplot)
library(ggplot2)
library(performance)
library(car)
```

```{r}
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/hospitalisation")

hospitalisation_data <- read_excel("hospitalisation rawdata.xlsx", sheet = 1)  

hospitalisation_data
```

```{r}
hospitalisation_data_prepared <- hospitalisation_data %>%
  dplyr::select(1,7)
hospitalisation_data_prepared
```

```{r}
gender_data <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/gender plots - bmi/gender_info_full.xlsx",
           sheet = 1, skip = 1)
```

```{r}
library(dplyr)
gender_data1 <- gender_data %>% 
  melt(cols = c("Male", "Female"),
       variable.name = "Gender") %>% 
  drop_na(value)

gender_data1
  
```


```{r}
hospitalisation_gender_data <- left_join(hospitalisation_data_prepared, gender_data1, by = ("Edited_BfArM Nummer2")) %>% 
  drop_na(value) %>% 
  drop_na("Dauer Krankenhausaufenthalt (Tage)")
hospitalisation_gender_data
```


```{r}
all_groups_hospitalisation_gender_violin <- ggbetweenstats(
  data = hospitalisation_gender_data,
  x = "Gender",
  y = "Dauer Krankenhausaufenthalt (Tage)",
  type = "np",  # non-parametrisch
  title = "All groups_hospitalisation times of male vs. female",
  xlab = "Gender",
  ylab = "Hospitalisaiton time (days)",
  messages = FALSE
)

all_groups_hospitalisation_gender_violin
dir.create("plots/corr hosp gender", showWarnings = FALSE)
svg("plots/corr hosp gender/all groups_violin_hospitalisation for gender.svg", height = 6, width = 8)
print(all_groups_hospitalisation_gender_violin)
dev.off()
```



### Leber_Diclo ###

```{r}
ld_hospitalisation_gender_data <- hospitalisation_gender_data %>% 
  filter(Treatment == "Leber_Diclo")
```


```{r}
ld_hospitalisation_gender_violin <- ggbetweenstats(
  data = ld_hospitalisation_gender_data,
  x = "Gender",
  y = "Dauer Krankenhausaufenthalt (Tage)",
  type = "np",  # non-parametrisch
  title = "Liver diclo_hospitalisation times of male vs. female",
  xlab = "Gender",
  ylab = "Hospitalisaiton time (days)",
  messages = FALSE
)

ld_hospitalisation_gender_violin
dir.create("plots/corr hosp gender", showWarnings = FALSE)
svg("plots/corr hosp gender/ld_violin_hospitalisation for gender.svg", height = 6, width = 8)
print(ld_hospitalisation_gender_violin)
dev.off()
```




### Leber_Ibu ###

```{r}
li_hospitalisation_gender_data <- hospitalisation_gender_data %>% 
  filter(Treatment == "Leber_Ibu")
```


```{r}
li_hospitalisation_gender_violin <- ggbetweenstats(
  data = li_hospitalisation_gender_data,
  x = "Gender",
  y = "Dauer Krankenhausaufenthalt (Tage)",
  type = "np",  # non-parametrisch
  title = "Liver ibu_hospitalisation times of male vs. female",
  xlab = "Gender",
  ylab = "Hospitalisaiton time (days)",
  messages = FALSE
)

li_hospitalisation_gender_violin
dir.create("plots/corr hosp gender", showWarnings = FALSE)
svg("plots/corr hosp gender/li_violin_hospitalisation for gender.svg", height = 6, width = 8)
print(li_hospitalisation_gender_violin)
dev.off()
```


### Leber_Para ###

```{r}
lp_hospitalisation_gender_data <- hospitalisation_gender_data %>% 
  filter(Treatment == "Leber_Para")
```

```{r}
lp_hospitalisation_gender_violin <- ggbetweenstats(
  data = lp_hospitalisation_gender_data,
  x = "Gender",
  y = "Dauer Krankenhausaufenthalt (Tage)",
  type = "np",  # non-parametrisch
  title = "Liver para_hospitalisation times of male vs. female",
  xlab = "Gender",
  ylab = "Hospitalisaiton time (days)",
  messages = FALSE
)

lp_hospitalisation_gender_violin
dir.create("plots/corr hosp gender", showWarnings = FALSE)
svg("plots/corr hosp gender/lp_violin_hospitalisation for gender.svg", height = 6, width = 8)
print(lp_hospitalisation_gender_violin)
dev.off()
```










