---
title: "Untitled"
output: html_document
date: "2026-03-28"
---

```{r}
library(GGally)
library(dplyr)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(ggstatsplot)
library(ggplot2)
library(performance)
library(car)
```

```{r}
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/hospitalisation")

hospitalisation_data <- read_excel("hospitalisation rawdata.xlsx", sheet = 1)  

#lvdiclo_dosedata <- dose_data %>% 
#  filter(Attribut == "Leber_Diclo") %>% 
#  rename( "Edited_BfArM Nummer2" ="BfArM Nummer_2" )

#lvdiclo_dosedata
hospitalisation_data
```

### gpt #############################################################

```{r}
# Attribute korrekt erstellen, abhängig von Dauer
hospitalisation_data_transformed <- hospitalisation_data %>%
  mutate(
    attribute = ifelse(
      `Dauer Diagnose bis Aufnahme (Tage)` >= 0,
      paste0("GPT Day", `Dauer Diagnose bis Entlassung (Tage)` + 1),
      paste0("GPT Day", `Dauer Diagnose bis Entlassung (Tage)` + 1)
    ))
hospitalisation_data_transformed
```


```{r}
gpt_after_discharge <- gpt_full %>%
  # Tag aus "GPT DayX" extrahieren
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  mutate(
    day = as.numeric(str_extract(attribute, "\\d+"))
  ) %>%
  # Join mit hospitalisation_data über Patienten-ID
  left_join(
    hospitalisation_data %>%
      select(`Edited_BfArM Nummer2`, `Dauer Diagnose bis Entlassung (Tage)`),
    by = "Edited_BfArM Nummer2"
  ) %>%
  # Nur Werte nach Entlassung behalten
  filter(day > `Dauer Diagnose bis Entlassung (Tage)`)

gpt_after_discharge
```


```{r}
gpt_discharge_labv_grouped <- gpt_after_discharge %>%
  group_by(`Edited_BfArM Nummer2`) %>%
  summarise(
    median_labreads = median(labreads, na.rm = TRUE),
    n_measurements = sum(!is.na(labreads)),
    .groups = "drop") %>%
  mutate(
    Labvalue_Group = case_when(
      median_labreads <= 20.9 ~ "within normal reference",
      median_labreads >= 21 & median_labreads <= 62.9 ~ "1-2 times ULN",
      median_labreads >= 63 & median_labreads <= 127.9 ~ "3-5 times ULN",
      median_labreads >= 128 & median_labreads <= 212.9 ~ "6-9 times ULN",
      median_labreads >= 213 & median_labreads <= 1062.9 ~ "10-49 times ULN",
      median_labreads >= 1063 & median_labreads <= 2124.9 ~ "50-99 times ULN",
      median_labreads >= 2125 & median_labreads <= 10624.9 ~ "100-499 times ULN",
      median_labreads >= 10625 ~ ">500 times ULN",
      TRUE ~ NA_character_
    ))
gpt_discharge_labv_grouped
```


####labreads per Group count###
```{r}
gpt_discharge_labv_grouped_count <- gpt_discharge_labv_grouped %>%
  count(Labvalue_Group, sort = TRUE)
gpt_discharge_labv_grouped_count
```


```{r}
gpt_discharge_labv_grouped_count$Labvalue_Group <-  factor(gpt_discharge_labv_grouped_count$Labvalue_Group, 
                                   levels = c( "within normal reference","1-2 times ULN", "3-5 times ULN", 
"6-9 times ULN", "10-49 times ULN", "50-99 times ULN","100-499 times ULN",  ">500 times ULN"))

all_groups_gpt_dimension_labvalues_at_dismiss <- gpt_discharge_labv_grouped_count %>%
  mutate(n = as.numeric(n)) %>% 
  ggplot(aes(x = Labvalue_Group, y =n)) +
  geom_col() +
  theme_classic() +
  geom_text(data = gpt_discharge_labv_grouped_count, 
            aes(label = paste0("N = ", n)),
            vjust = -0.3,  # Positionierung leicht oberhalb des Balkens
            size = 5)+       # Optional: kleinere Schriftgröße
  labs(title = "all groups_labvalues after dismiss", 
       x = "Factor of reference value", 
       y = "number of patients") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
all_groups_gpt_dimension_labvalues_at_dismiss
#dir.create("plots_labvalue dimension of rise", showWarnings = FALSE)
#svg("plots_labvalue dimension of rise/alt_all_patients_labvalue_dimension_of_peak_ALT.svg", height = 8, width = 6.5)
#print(all_patients_labvalue_dimension_of_peak_ALT)
#dev.off()
```


