---
title: "SJS"
author: "Arun Kumar"
date: "2023-04-06"
output: html_document
---
## load the libraries for data analysis
```{r}
library(readxl)
library(tidyr)
library(dplyr)
```

```{r, echo=FALSE}
rawdata <- read_excel("Übersicht Laborwerte (Rohdaten für Interimsanalyse 03.05.2023).xlsx",sheet = 1,skip = 1)
```

## convert the data from tibble to data frame.
```{r}
rawdf1 <- as.data.frame(rawdata)
# # Remove leading and trailing spaces from column names
# names(rawdf1) <- trimws(names(rawdf1))
# rawdf1 <- as.data.frame(rawdf1)
```

## conversion of  from char to numeric values
```{r}
rawdf1$`Ck Day4` <- as.numeric(rawdf1$`Ck Day4`)
```
## data convert to longerformat

```{r}
rawdf1 %>% 
  select(1:28) %>% 
  pivot_longer(cols = 3:28,
               names_to = "attribute",
               values_to = "labreads") %>% 
  drop_na()->ck_long
```



```{r}
rawdf1 %>% 
  select(1:2,29:45)->ckmb_rawdata
ckmb_rawdata %>% 
  pivot_longer(cols = 3:19,
               names_to = "attribute",
                values_to = "labreads") %>% 
   drop_na()->ckmb_long

```


```{r}
rawdf1 %>% 
  select(1:2,46:82)->quick_rawdata

quick_rawdata %>%
  pivot_longer(cols = 3:39,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->quick_long

```



```{r}
rawdf1 %>% 
  select(1:2,83:112)->inr_rawdata

inr_rawdata %>%
  pivot_longer(cols = 3:32,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->inr_long

```


```{r}
rawdf1 %>% 
  select(1:2,112:117)->troponin_i_rawdata

troponin_i_rawdata %>%
  pivot_longer(cols = 3:8,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->troponin_i_long
```



```{r}
rawdf1 %>% 
  select(1:2,117:126)->prothrombin_rawdata

prothrombin_rawdata %>%
  pivot_longer(cols = 3:12,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->prothrombin_long
```



```{r}
rawdf1 %>% 
  select(1:2,127:159)->ptt_rawdata

ptt_rawdata$`PTT Day2`  <- as.numeric(ptt_rawdata$`PTT Day2`)


ptt_rawdata %>%
  pivot_longer(cols = 3:35,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ptt_long
```



```{r}
rawdf1 %>% 
  select(1:2,160:168)->tz_rawdata

tz_rawdata %>%
  pivot_longer(cols = 3:11,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->tz_long
```



```{r}
rawdf1 %>% 
  select(1:2,169:172)->antithrombin_3_rawdata

antithrombin_3_rawdata %>%
  pivot_longer(cols = 3:6,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->antithrombin_3_long
```



```{r}
rawdf1 %>% 
  select(1:2,173:179)->serummyoglobin_rawdata

serummyoglobin_rawdata %>%
  pivot_longer(cols = 3:9,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->serummyoglobin_long
```



```{r}
rawdf1 %>% 
  select(1:2,180:183)->d_dimer_rawdata

d_dimer_rawdata %>%
  pivot_longer(cols = 3:6,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->d_dimer_long
```



```{r}
rawdf1 %>% 
  select(1:2,180:183)->d_dimer_rawdata

d_dimer_rawdata %>%
  pivot_longer(cols = 3:6,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->d_dimer_long
```



```{r}
rawdf1 %>% 
  select(1:2,185:205)->fibrinogen_rawdata

fibrinogen_rawdata %>%
  pivot_longer(cols = 3:23,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->fibrinogen_long
```



```{r}
rawdf1 %>% 
  select(1:2,207:253)->leukozyten_rawdata

leukozyten_rawdata %>%
  pivot_longer(cols = 3:49,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->leukozyten_long
```



```{r}
rawdf1 %>% 
  select(1:2,254:343)->got_rawdata

got_rawdata %>%
  pivot_longer(cols = 3:92,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->got_long
```



```{r}
rawdf1 %>% 
  select(1:2,344:439)->gpt_rawdata


gpt_rawdata$`GPT Day11`  <- as.numeric(gpt_rawdata$`GPT Day11`)


gpt_rawdata %>%
  pivot_longer(cols = 3:98,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->gpt_long
```



```{r}
rawdf1 %>% 
  select(1:2,440:519)->ggt_rawdata

ggt_rawdata$`GGT Day22`  <- as.numeric(ggt_rawdata$`GGT Day22`)
ggt_rawdata$`GGT Day34`  <- as.numeric(ggt_rawdata$`GGT Day34`)



ggt_rawdata %>%
  pivot_longer(cols = 3:82,
               names_to = "attribute",
                values_to = "labreads")  %>%
    drop_na()->ggt_long
```



```{r}
rawdf1 %>% 
  select(1:2,520:557)->ldh_rawdata

ldh_rawdata %>%
  pivot_longer(cols = 3:40,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ldh_long
```



```{r}
rawdf1 %>% 
  select(1:2,558:581)->gldh_rawdata

gldh_rawdata %>%
  pivot_longer(cols = 3:26,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->gldh_long
```



```{r}
rawdf1 %>% 
  select(1:2,582:599)->triglyceride_rawdata

triglyceride_rawdata %>%
  pivot_longer(cols = 3:20,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->triglyceride_long
```



```{r}
rawdf1 %>% 
  select(1:2,599:611)->cholesterin_rawdata

cholesterin_rawdata %>%
  pivot_longer(cols = 3:14,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->cholesterin_long
```



```{r}
rawdf1 %>% 
  select(1:2,599:611)->cholesterin_rawdata

cholesterin_rawdata %>%
  pivot_longer(cols = 3:14,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->cholesterin_long
```



```{r}
rawdf1 %>% 
  select(1:2,611:618)->hdl_rawdata

hdl_rawdata %>%
  pivot_longer(cols = 3:10,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->hdl_long
```



```{r}
rawdf1 %>% 
  select(1:2,618:624)->ldl_rawdata

ldl_rawdata %>%
  pivot_longer(cols = 3:9,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ldl_long
```



```{r}
rawdf1 %>% 
  select(1:2,627:655)->lymphozyten_rawdata

lymphozyten_rawdata %>%
  pivot_longer(cols = 3:31,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->lymphozyten_long
```



```{r}
rawdf1 %>% 
  select(1:2,656:673)->monozyten_rawdata

monozyten_rawdata %>%
  pivot_longer(cols = 3:20,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->monozyten_long
```



```{r}
rawdf1 %>% 
  select(1:2,673:725)->hb_rawdata

hb_rawdata %>%
  pivot_longer(cols = 3:55,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->hb_long
```



```{r}
rawdf1 %>% 
  select(1:2,726:792)->total_bilirubin_rawdata

total_bilirubin_rawdata %>%
  pivot_longer(cols = 3:69,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->total_bilirubin_long
```



```{r}
rawdf1 %>% 
  select(1:2,793:820)->direct_bilirubin_rawdata

direct_bilirubin_rawdata %>%
  pivot_longer(cols = 3:30,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->direct_bilirubin_long
```


```{r}
rawdf1 %>% 
  select(1:2,823:842)->gesamteiweiß_rawdata

gesamteiweiß_rawdata %>%
  pivot_longer(cols = 3:22,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->gesamteiweiß_long
```



```{r}
rawdf1 %>% 
  select(1:2,843:915)->ap_rawdata

ap_rawdata %>%
  pivot_longer(cols = 3:75,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ap_long
```



```{r}
rawdf1 %>% 
  select(1:2,916:936)->cholinesterase_rawdata

cholinesterase_rawdata %>%
  pivot_longer(cols = 3:23,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->cholinesterase_long
```



```{r}
rawdf1 %>% 
  select(1:2,937:979)->kreatinin_rawdata

kreatinin_rawdata %>%
  pivot_longer(cols = 3:45,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->kreatinin_long
```



```{r}
rawdf1 %>% 
  select(1:2,980:982)->kreatinkinase_rawdata

kreatinkinase_rawdata %>%
  pivot_longer(cols = 3:5,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->kreatinkinase_long
```


```{r}
rawdf1 %>% 
  select(1:2,983:1004)->amylase_rawdata

amylase_rawdata %>%
  pivot_longer(cols = 3:14,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->amylase_long
```



```{r}
rawdf1 %>% 
  select(1:2,1005:1036)->lipase_rawdata

lipase_rawdata %>%
  pivot_longer(cols = 3:34,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->lipase_long
```




```{r}
rawdf1 %>% 
  select(1:2,1077:1106)->harnstoff_rawdata

harnstoff_rawdata %>%
  pivot_longer(cols = 3:32,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->harnstoff_long
```



```{r}
rawdf1 %>% 
  select(1:2,1107:1123)->harnsäure_rawdata

harnsäure_rawdata %>%
  pivot_longer(cols = 3:19,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->harnsäure_long
```




```{r}
rawdf1 %>% 
  select(1:2,1123:1158)->erythrozyten_rawdata

erythrozyten_rawdata %>%
  pivot_longer(cols = 3:38,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->erythrozyten_long
```




```{r}
rawdf1 %>% 
  select(1:2,1161:1205)->thrombozyten_rawdata

thrombozyten_rawdata %>%
  pivot_longer(cols = 3:47,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->thrombozyten_long
```




```{r}
rawdf1 %>% 
  select(1:2,1206:1210)->haptoglobin_rawdata

haptoglobin_rawdata %>%
  pivot_longer(cols = 3:7,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->haptoglobin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1210:1218)->bsg_rawdata

bsg_rawdata %>%
  pivot_longer(cols = 3:11,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->bsg_long
```



```{r}
rawdf1 %>% 
  select(1:2,1225:1242)->eosinophile_rawdata

eosinophile_rawdata %>%
  pivot_longer(cols = 3:9,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->eosinophile_long
```



```{r}
rawdf1 %>% 
  select(1:2,1242:1266)->neutrophile_rawdata

neutrophile_rawdata %>%
  pivot_longer(cols = 3:24,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->neutrophile_long
```



```{r}
rawdf1 %>% 
  select(1:2,1266:1282)->basophile_rawdata

basophile_rawdata %>%
  pivot_longer(cols = 3:19,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->basophile_long
```




```{r}
rawdf1 %>% 
  select(1:2,1282:1303)->albumin_rawdata

albumin_rawdata %>%
  pivot_longer(cols = 3:19,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->albumin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1304:1306)->ggtp_rawdata

ggtp_rawdata %>%
  pivot_longer(cols = 3:5,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ggtp_long
```



```{r}
rawdf1 %>% 
  select(1:2,1307:1308)->gamma_globulin_rawdata

gamma_globulin_rawdata %>%
  pivot_longer(cols = 3:4,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->gamma_globulin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1309:1311)->alpha_globulin_rawdata

alpha_globulin_rawdata %>%
  pivot_longer(cols = 3:5,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->alpha_globulin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1309:1311)->alpha_globulin_rawdata

alpha_globulin_rawdata %>%
  pivot_longer(cols = 3:5,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->alpha_globulin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1311:1321)->ph_blut_rawdata

ph_blut_rawdata %>%
  pivot_longer(cols = 3:13,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ph_blut_long
```



```{r}
rawdf1 %>% 
  select(1:2,1321:1327)->base_excess_rawdata

base_excess_rawdata %>%
  pivot_longer(cols = 3:9,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->base_excess_long
```



```{r}
rawdf1 %>% 
  select(1:2,1327:1336)->bicarbonat_rawdata

bicarbonat_rawdata %>%
  pivot_longer(cols = 3:12,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->bicarbonat_long
```



```{r}
rawdf1 %>% 
  select(1:2,1337:1341)->sauerstoffpartialdruck_rawdata

sauerstoffpartialdruck_rawdata %>%
  pivot_longer(cols = 3:7,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->sauerstoffpartialdruck_long
```



```{r}
rawdf1 %>% 
  select(1:2,1342:1350)->kohlendioxidpartialdruck_rawdata

kohlendioxidpartialdruck_rawdata %>%
  pivot_longer(cols = 3:11,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->kohlendioxidpartialdruck_long
```



```{r}
rawdf1 %>% 
  select(1:2,1351:1354)->sauerstoffsättigung_rawdata

sauerstoffsättigung_rawdata %>%
  pivot_longer(cols = 3:6,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->sauerstoffsättigung_long
```



```{r}
rawdf1 %>% 
  select(1:2,1355:1402)->hämatokrit_rawdata

hämatokrit_rawdata %>%
  pivot_longer(cols = 3:50,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->hämatokrit_long
```



```{r}
rawdf1 %>% 
  select(1:2,1403:1435)->mcv_rawdata

mcv_rawdata %>%
  pivot_longer(cols = 3:35,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->mcv_long
```



```{r}
rawdf1 %>% 
  select(1:2,1436:1464)->mch_rawdata

mch_rawdata %>%
  pivot_longer(cols = 3:31,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->mch_long
```



```{r}
rawdf1 %>% 
  select(1:2,1464:1494)->mchc_rawdata

mchc_rawdata %>%
  pivot_longer(cols = 3:33,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->mchc_long
```



```{r}
rawdf1 %>% 
  select(1:2,1524:1554)->natrium_rawdata

natrium_rawdata %>%
  pivot_longer(cols = 3:33,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->natrium_long
```


```{r}
rawdf1 %>% 
  select(1:2,1555:1584)->kalium_rawdata

kalium_rawdata %>%
  pivot_longer(cols = 3:32,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->kalium_long
```



```{r}
rawdf1 %>% 
  select(1:2,1585:1609)->kalzium_rawdata

kalzium_rawdata %>%
  pivot_longer(cols = 3:27,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->kalzium_long
```



```{r}
rawdf1 %>% 
  select(1:2,1610:1618)->magnesium_rawdata

magnesium_rawdata %>%
  pivot_longer(cols = 3:11,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->magnesium_long
```



```{r}
rawdf1 %>% 
  select(1:2,1619:1625)->chlorid_rawdata

chlorid_rawdata %>%
  pivot_longer(cols = 3:9,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->chlorid_long
```



```{r}
rawdf1 %>% 
  select(1:2,1626:1636)->serum_eisen_rawdata

serum_eisen_rawdata %>%
  pivot_longer(cols = 3:13,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->serum_eisen_long
```



```{r}
rawdf1 %>% 
  select(1:2,1637:1646)->ferritin_rawdata

ferritin_rawdata %>%
  pivot_longer(cols = 3:11,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ferritin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1651:1656)->fieber_rawdata

fieber_rawdata %>%
  pivot_longer(cols = 3:8,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->fieber_long
```

```{r}
rawdf1 %>% 
  select(1:2,1656:1660)->hba1c_rawdata

hba1c_rawdata %>%
  pivot_longer(cols = 3:7,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->hba1c_long
```

```{r}
rawdf1 %>% 
  select(1:2,1661:1689)->glucose_rawdata

glucose_rawdata %>%
  pivot_longer(cols = 3:31,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->glucose_long
```

```{r}
rawdf1 %>% 
  select(1:2,1689:1695)->ammonika_rawdata

ammonika_rawdata %>%
  pivot_longer(cols = 3:9,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ammonika_long
```

```{r}
rawdf1 %>% 
  select(1:2,1696:1700)->lactat_rawdata

lactat_rawdata %>%
  pivot_longer(cols = 3:7,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->lactat_long
```

```{r}
rawdf1 %>% 
  select(1:2,1702:1707)->phosphat_rawdata

phosphat_rawdata %>%
  pivot_longer(cols = 3:8,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->phosphat_long
```

