---
title: "malefemale"
output: html_document
date: "2024-05-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r} 
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(ggstatsplot)
```


```{r}
gender_data_para <-read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/gender_info.xlsx",
           sheet = 1, skip = 1)
```


```{r}
library(dplyr)
gender_data1 <- gender_data %>% 
  melt(cols = c("Male", "Female"),
       variable.name = "Gender") %>% 
  dplyr::filter(Treatment == "Leber_Ibu")


  
```

## patient data###
```{r}
patientidentifier_para <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Übersicht Laborwerte (Laborwerte fertig).xlsx",
           sheet = 4, skip = 1 ) %>% 
  filter(Treatment == "Leber_Para") %>% 
  pivot_longer(cols = 3:4,
               names_to = "gender",
               values_to = "numberofpatient") %>% 
  filter(numberofpatient== 1) 

## unknown gender dataframe
test_para <- tibble(`Edited_BfArM Nummer2`=c("9042861","9044899"),
                     Treatment=c("Leber_Para","Leber_Para"),
                     gender=c("Unknown","Unknown"),
                     numberofpatient=c(1,1))

patientidentifier_para1 <- rbind(patientidentifier_para,test_para)
  

```

##################################################################
##ALT##
```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier
gptaltdata_long <- gpt_rawdata %>%
  tidyr::pivot_longer(cols = -c("Edited_BfArM Nummer2", "Treatment"), 
               names_to = "Attribute", 
               values_to = "labreads")

# Step 2: Filter the data for the specified treatment
filtered_data <- gptaltdata_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
counts_data <- filtered_data %>%
  group_by(Attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
gptaltdata_with_counts <- filtered_data %>%
  left_join(counts_data, by = "Attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 filtered_data_with_min_counts <- gptaltdata_with_counts %>%
  filter(count >= 3) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(filtered_data_with_min_counts)

  
```

## alt data greater than 5 counts in all attribute###
```{r}
lpara_alt_data <- left_join(patientidentifier_para1,filtered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```


```{r}
lpara_alt_data %>% 
  group_by(gender) %>% normality(labreads)
```


```{r}
dd <- lpara_alt_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "ALT U/L",
  ggtheme = theme_classic()
)

```




##############################################################################
##ast##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier
astaltdata_long <- got_rawdata %>%
  tidyr::pivot_longer(cols = -c("Edited_BfArM Nummer2", "Treatment"), 
               names_to = "Attribute", 
               values_to = "labreads")

# Step 2: Filter the data for the specified treatment
filtered_data <- astaltdata_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
astcounts_data <- filtered_data %>%
  group_by(Attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
astdata_with_counts <- filtered_data %>%
  left_join(astcounts_data, by = "Attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 astfiltered_data_with_min_counts <- astdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(astfiltered_data_with_min_counts)

  
```




```{r}
lparaast_data <- left_join(patientidentifier_para1,astfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```


```{r}
lparaast_data %>% 
  group_by(gender) %>% normality(labreads)
```


```{r}
dd <- lparaast_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "AST U/L",
  ggtheme = theme_classic()
)

```





##############################################################################
##ck##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- ck_long %>%
  filter(Treatment == "Leber_Diclo")

# Step 3: Count occurrences, preserving the identifier
ckcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
ckdata_with_counts <- filtered_data %>%
  left_join(ckcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 ckfiltered_data_with_min_counts <- ckdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(ckfiltered_data_with_min_counts)

  
```



```{r}
ldck_data <- left_join(patientidentifier,ckfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```


```{r}
ldck_data %>% 
  group_by(gender) %>% normality(labreads)
```


```{r}
dd <- ldck_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "CK U/L",
  ggtheme = theme_classic()
)

```

##############################################################################
##quick##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- quick_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
quickcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
quickdata_with_counts <- filtered_data %>%
  left_join(quickcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 quickfiltered_data_with_min_counts <- quickdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(quickfiltered_data_with_min_counts)

  
```

```{r}
lparaquick_data <- left_join(patientidentifier_para1,quickfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```


```{r}
lparaquick_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaquick_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "quick %",
  ggtheme = theme_classic()
)

```


##############################################################################
##inr##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- inr_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
inrcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
inrdata_with_counts <- filtered_data %>%
  left_join(inrcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 inrfiltered_data_with_min_counts <- inrdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(inrfiltered_data_with_min_counts)

  
```

```{r}
lparainr_data <- left_join(patientidentifier_para1,inrfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```


```{r}
lparainr_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparainr_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "INR",
  ggtheme = theme_classic()
)

```


##############################################################################
##ptt##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- ptt_long %>%
  filter(Treatment == "Leber_Diclo")

# Step 3: Count occurrences, preserving the identifier
pttcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
pttdata_with_counts <- filtered_data %>%
  left_join(pttcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 pttfiltered_data_with_min_counts <- pttdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(pttfiltered_data_with_min_counts)

  
```


```{r}
pttdata_with_counts
```
```{r}
pttcounts_data
```

```{r}
ldptt_data <- left_join(patientidentifier,pttfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```


```{r}
ldptt_data %>% 
  group_by(gender) %>% normality(labreads)
```
```{r}
dd <- ldptt_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "PTT Sec.",
  ggtheme = theme_classic()
)

```
##############################################################################
##Leukozyten##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- leukozyten_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
leukozytencounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
leukozytendata_with_counts <- filtered_data %>%
  left_join(leukozytencounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 leukozytenfiltered_data_with_min_counts <- leukozytendata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(leukozytenfiltered_data_with_min_counts)

  
```

```{r}
lparaleukozyten_data <- left_join(patientidentifier_para1,leukozytenfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparaleukozyten_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaleukozyten_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "Leukozyten Zellen/ul",
  ggtheme = theme_classic()
)

```

##############################################################################
##ggt##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- ggt_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
ggtcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
ggtdata_with_counts <- filtered_data %>%
  left_join(ggtcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 ggtfiltered_data_with_min_counts <- ggtdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(ggtfiltered_data_with_min_counts)

  
```

```{r}
lparaggt_data <- left_join(patientidentifier_para1,ggtfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparaggt_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaggt_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "GGT U/L",
  ggtheme = theme_classic()
)

```

##############################################################################
##ldh##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- ldh_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
ldhcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
ldhdata_with_counts <- filtered_data %>%
  left_join(ldhcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 ldhfiltered_data_with_min_counts <- ldhdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(ldhfiltered_data_with_min_counts)

  
```

```{r}
lparaldh_data <- left_join(patientidentifier_para1,ldhfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparaldh_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaldh_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "LDH U/L",
  ggtheme = theme_classic()
)

```

##############################################################################
##hb##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- hb_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
hbcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
hbdata_with_counts <- filtered_data %>%
  left_join(hbcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 hbfiltered_data_with_min_counts <- hbdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(hbfiltered_data_with_min_counts)

  
```

```{r}
lparahb_data <- left_join(patientidentifier_para1,hbfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparahb_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparahb_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "HB g/dl",
  ggtheme = theme_classic()
)

```

##############################################################################
##totales Bilirubin##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- total_bilirubin_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
totbilicounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
totbilidata_with_counts <- filtered_data %>%
  left_join(totbilicounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 totbilifiltered_data_with_min_counts <- totbilidata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(totbilifiltered_data_with_min_counts)

  
```

```{r}
lparatotbili_data <- left_join(patientidentifier_para1,totbilifiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparatotbili_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparatotbili_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "totales Bilirubin mg/dl",
  ggtheme = theme_classic()
)

```
##############################################################################
##direktes Bilirubin##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- direct_bilirubin_long %>%
  filter(Treatment == "Leber_Ibu")

# Step 3: Count occurrences, preserving the identifier
dirbilicounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
dirbilidata_with_counts <- filtered_data %>%
  left_join(dirbilicounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 dirbilifiltered_data_with_min_counts <- dirbilidata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(dirbilifiltered_data_with_min_counts)

  
```

```{r}
libudirbili_data <- left_join(patientidentifier_ibu1,dirbilifiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
libudirbili_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- libudirbili_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "direktes Bilirubin mg/dl",
  ggtheme = theme_classic()
)

```


##############################################################################
##AP##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- ap_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
apcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
apdata_with_counts <- filtered_data %>%
  left_join(apcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 apfiltered_data_with_min_counts <- apdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(apfiltered_data_with_min_counts)

  
```

```{r}
lparaap_data <- left_join(patientidentifier_para1,apfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparaap_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparaap_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "AP U/L",
  ggtheme = theme_classic()
)

```


##############################################################################
##Keratinin##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- kreatinin_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
kreacounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
kreadata_with_counts <- filtered_data %>%
  left_join(kreacounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 kreafiltered_data_with_min_counts <- kreadata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(kreafiltered_data_with_min_counts)

  
```

```{r}
lparakrea_data <- left_join(patientidentifier_para1,kreafiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparakrea_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparakrea_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "Kreatinin mg/dl",
  ggtheme = theme_classic()
)

```

##############################################################################
##CRP##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- crp_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
crpcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
crpdata_with_counts <- filtered_data %>%
  left_join(crpcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 crpfiltered_data_with_min_counts <- crpdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(crpfiltered_data_with_min_counts)

  
```

```{r}
lparacrp_data <- left_join(patientidentifier_para1,crpfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparacrp_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparacrp_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "CRP mg/l",
  ggtheme = theme_classic()
)

```

##############################################################################
##Harnstoff##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- harnstoff_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
hstcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
hstdata_with_counts <- filtered_data %>%
  left_join(hstcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 hstfiltered_data_with_min_counts <- hstdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(hstfiltered_data_with_min_counts)

  
```

```{r}
lparahst_data <- left_join(patientidentifier_para1,hstfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparahst_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparahst_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "Harnstoff mg/dl",
  ggtheme = theme_classic()
)

```

##############################################################################
##Erythrozyten##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- erythrozyten_long %>%
  filter(Treatment == "Leber_Diclo")

# Step 3: Count occurrences, preserving the identifier
erycounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
erydata_with_counts <- filtered_data %>%
  left_join(erycounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 eryfiltered_data_with_min_counts <- erydata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(eryfiltered_data_with_min_counts)

  
```

```{r}
ldery_data <- left_join(patientidentifier,eryfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
ldery_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- ldery_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "Erythrozyten Zellen/ul",
  ggtheme = theme_classic()
)

```

##############################################################################
##Thrombozyten##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- thrombozyten_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
thrombcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
thrombdata_with_counts <- filtered_data %>%
  left_join(thrombcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 thrombfiltered_data_with_min_counts <- thrombdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(thrombfiltered_data_with_min_counts)

  
```

```{r}
lparathromb_data <- left_join(patientidentifier_para1,thrombfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparathromb_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparathromb_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "Thrombozyten Zellen/ul",
  ggtheme = theme_classic()
)

```

##############################################################################
##Hämatokrit##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- hämatokrit_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
hktcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
hktdata_with_counts <- filtered_data %>%
  left_join(hktcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 hktfiltered_data_with_min_counts <- hktdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(hktfiltered_data_with_min_counts)

  
```

```{r}
lparahkt_data <- left_join(patientidentifier_para1,hktfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparahkt_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparahkt_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "Hämatokrit %",
  ggtheme = theme_classic()
)

```

##############################################################################
##Natrium##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- natrium_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
natcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
natdata_with_counts <- filtered_data %>%
  left_join(natcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 natfiltered_data_with_min_counts <- natdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(natfiltered_data_with_min_counts)

  
```

```{r}
lparanat_data <- left_join(patientidentifier_para1,natfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparanat_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparanat_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "Natrium mmol/l",
  ggtheme = theme_classic()
)

```

##############################################################################
##Kalium##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- kalium_long %>%
  filter(Treatment == "Leber_Para")

# Step 3: Count occurrences, preserving the identifier
kalcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
kaldata_with_counts <- filtered_data %>%
  left_join(kalcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 kalfiltered_data_with_min_counts <- kaldata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(kalfiltered_data_with_min_counts)

  
```

```{r}
lparakal_data <- left_join(patientidentifier_para1,kalfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
lparakal_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- lparakal_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "Kalium mmol/l",
  ggtheme = theme_classic()
)

```

##############################################################################
##Kalzium##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- kalzium_long %>%
  filter(Treatment == "Leber_Diclo")

# Step 3: Count occurrences, preserving the identifier
calcounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
caldata_with_counts <- filtered_data %>%
  left_join(calcounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 calfiltered_data_with_min_counts <- caldata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(calfiltered_data_with_min_counts)

  
```

```{r}
ldcal_data <- left_join(patientidentifier,calfiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
ldcal_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- ldcal_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "Kalzium mmol/l",
  ggtheme = theme_classic()
)

```

##############################################################################
##Glucose##

```{r}

# gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
# gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

  

# Step 2: Filter the data for the specified treatment
filtered_data <- glucose_long %>%
  filter(Treatment == "Leber_Diclo")

# Step 3: Count occurrences, preserving the identifier
glucounts_data <- filtered_data %>%
  group_by(attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
gludata_with_counts <- filtered_data %>%
  left_join(glucounts_data, by = "attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 glufiltered_data_with_min_counts <- gludata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(glufiltered_data_with_min_counts)

  
```

```{r}
ldglu_data <- left_join(patientidentifier,glufiltered_data_with_min_counts, by = ("Edited_BfArM Nummer2")) %>% 
  select(1,2,3,6,7,8) %>% drop_na(count)
```

```{r}
ldglu_data %>% 
  group_by(gender) %>% normality(labreads)
```

```{r}
dd <- ldglu_data %>% 
  group_by(gender)

ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  ylab = "Glucose mg/dl",
  ggtheme = theme_classic()
)

```


####

