---
title: "Untitled"
author: "Arun Kumar"
date: "2026-05-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(here)

```

##===================
## Import Function
##===================
 
```{r}
source(here::here("R/diabetic/clean_data.R"))
source(here::here("R/comedication.R"))
```

##===================
## Raw data from Excel
##===================

```{r}
sheets <- excel_sheets(here::here(
  "RawData/new_raw_data/ubersicht_Laborwerte_laborwerte_fertig_aktuell_new.xlsx"
))

sheets <- sheets[
  sheets %in% c(
    "Fallberichte")]
sheets


labvalue_data <- map_dfr(
  sheets,
  ~ process_sheet(file = here::here("RawData/new_raw_data/ubersicht_Laborwerte_laborwerte_fertig_aktuell_new.xlsx"), .x)
  )
labvalue_data
```

```{r}
labvalue_data_new <- read_data(
  file = here::here("RawData/new_raw_data/ubersicht_Laborwerte_control_group_aktuell_new.xlsx"),
  sheet = "Controlgroup no time"
) %>% 
  janitor::clean_names() %>% 
  rename(
    bf_ar_m_nummer = edited_bf_ar_m_nummer2) %>% 
  pivot_longer(
    cols = -c(bf_ar_m_nummer, treatment),
    names_to = "attribute",
    values_to = "labreads"
  ) %>% 
  mutate(
  is_time_series = stringr::str_detect(attribute, "\\d+"),

  days = if_else(
    is_time_series,
    readr::parse_number(attribute),
    NA_real_
  ),

  day_raw = if_else(
    is.na(days),
    NA_character_,
    paste0("day", days)
  ),

  panel_id = if_else(
    is_time_series,
    sub("_[^_]+$", "", attribute),
    attribute
  ),

  panel = "control_no_time"
) %>% 
  dplyr::select(
    panel, panel_id, bf_ar_m_nummer, treatment,
    attribute, labreads,
    day_raw, days
  )
labvalue_data_new
```

```{r}
labvalue_data_neww <- read_data(
  file = here::here("RawData/new_raw_data/ubersicht_Laborwerte_control_group_aktuell_new.xlsx"),
  sheet = "Controlgroup time"
) %>% 
  janitor::clean_names() %>% 
  rename(
    bf_ar_m_nummer = edited_bf_ar_m_nummer2) %>% 
  pivot_longer(
    cols = -c(bf_ar_m_nummer, treatment),
    names_to = "attribute",
    values_to = "labreads"
  ) %>% 
  mutate(
  is_time_series = stringr::str_detect(attribute, "\\d+"),

  days = if_else(
    is_time_series,
    readr::parse_number(attribute),
    NA_real_
  ),

  day_raw = if_else(
    is.na(days),
    NA_character_,
    paste0("day", days)
  ),

  panel_id = if_else(
    is_time_series,
    sub("_[^_]+$", "", attribute),
    attribute
  ),

    panel = "Controlgroup time"
  ) %>% 
  dplyr::select(
    panel, panel_id, bf_ar_m_nummer, treatment,
    attribute, labreads,
    day_raw, days
  )
labvalue_data_neww
```


```{r}
library(dplyr)
library(readr)

labvalue_data_clean <- labvalue_data %>% 
  mutate(
    labreads = parse_number(as.character(labreads)),
    days     = as.numeric(days)
  )

labvalue_data_new_clean <- labvalue_data_new %>% 
  mutate(
    labreads = parse_number(as.character(labreads)),
    days     = as.numeric(days)
  )

labvalue_data_neww_clean <- labvalue_data_neww %>% 
  mutate(
    labreads = parse_number(as.character(labreads)),
    days     = as.numeric(days)
  )

all_data <- bind_rows(labvalue_data_clean, labvalue_data_new_clean,labvalue_data_neww_clean)
all_data
```



```{r}
#write_rds(all_data,(here::here("processed_data/all_data.rds")))
```











##================================
## filter Raw data as per choice
##===============================

```{r}
#gpt_full <- 
  all_data %>% 
  filter(bf_ar_m_nummer == "5015869") %>% 
  filter(grepl("gpt_day1", attribute))
  #filter(panel_id == "gpt") 
#gpt_full
```

##============
##Age data
##============

```{r}
Age_data_gender <- read_data(
  file = here::here("RawData/age plots full.xlsx"),
  sheet = 3,
  range = "A1:E422"
)
age_gender_data <- Age_data_gender %>% 
   mutate(
    gender = case_when(
      Männlich == 1 ~ "M",
      Weiblich == 1 ~ "F",
      TRUE ~ NA_character_
    ),
    gender = factor(gender, levels = c("M", "F"))
  ) %>%
  select(-Männlich, -Weiblich)
age_gender_data
```


##============
##BMI data
##============

```{r}
bmi_rawdata <- read_data(
  file = here::here("RawData/bmi_rawdata.xlsx"),
  sheet = "bmi_rawdata",
  range = "A1:C420"
)
bmi_rawdata
```

```{r}
obesity_rawdata <- read_data(
  file = here::here("RawData/bmi_rawdata.xlsx"),
  sheet = "obesity_rawdata",
  range = "A1:C236"
)
obesity_rawdata
```

##=================================================
## comedication data all sheet read and append
##=================================================

```{r}
data_comedication_TTOd <- 
process_comedication_sheet(
  file = here::here("RawData/co_medication_rawdata_full.xlsx"),
  sheet = "TTOd",
  skip_headers = 3
)
data_comedication_TTOd 
```



```{r}
data_comedication_TTOq_withtime <- 
read_data(
  file = here::here("RawData/co_medication_rawdata_full.xlsx"),
  sheet = "TTOq_withtime",
  skip = 4
) %>% 
   pivot_longer(
        cols = -c(1:2),
        names_to    = c("Medication", "kathegorie", "drug_group"),
        names_pattern = "([^_]+)_([^_]+)_(.*)",
        values_to   = "labreads") %>% 
  dplyr::rename("bfarm_nummer" = "BfArM Nummer_BfArM Nummer_BfArM Nummer",
                "treatment" = "Kathegorie_Kathegorie_Kathegorie") %>% 
  drop_na(labreads)
data_comedication_TTOq_withtime
```

```{r}
data_comedication_TTOq_withouttime <- 
read_data(
  file = here::here("RawData/co_medication_rawdata_full.xlsx"),
  sheet = "TTOq withouttime",
  skip = 4
) %>% 
   pivot_longer(
        cols = -c(1:2),
        names_to    = c("Medication", "kathegorie", "drug_group"),
        names_pattern = "([^_]+)_([^_]+)_(.*)",
        values_to   = "labreads") %>% 
  dplyr::rename("bfarm_nummer" = "BfArM Nummer_BfArM Nummer_BfArM Nummer",
                "treatment" = "Kathegorie_Kathegorie_Kathegorie") %>% 
  drop_na(labreads)
data_comedication_TTOq_withouttime
```

```{r}
comedication_full_clean_data <- bind_rows(data_comedication_TTOd ,
                                    data_comedication_TTOq_withtime,
                                    data_comedication_TTOq_withouttime )
comedication_full_clean_data
#write.csv(comedication_full_clean_data,"processed_data/comedication/comedication_full_clean_data.csv")
```


##=================================================
## Death_data
##=================================================

```{r}
death_data <- 
read_excel(here::here("RawData/death_statistic_full.xlsx"),
  range = "A1:D415"
) %>% 
  slice(-1) %>% 
  mutate(
    death = case_when(
      `Tod eingetreten` == 1 ~ "yes",
      `Tod nicht eingetreten` == 1 ~ "no",
      TRUE ~ NA_character_
    ),
    
    censor = factor(
      death,
      levels = c("yes", "no"),
      labels = c("Dead", "Alive")
    )
  ) %>% 
  select(Kathegorie, censor) %>% 
  group_by(Kathegorie,censor) %>% 
  summarise(n = n(), .groups = "drop") %>% 
  pivot_wider(
    names_from = censor,
    values_from = n,
    values_fill = 0
  ) %>% 
  dplyr::select(1,3,2,4)

death_data

```


##===========================
## comedication_liver_toxicity
##===========================

```{r}
comedicationdata_heptox <- read.csv(
  here::here("RawData/comedication_with_livertoxicity literature only.csv"),sep = ",",
  stringsAsFactors = FALSE) %>% 
  dplyr::rename( "patient_group" = "treatment",
                 "parameter_co" = "labreads",
                 "kathegorie_co" = "kathegorie",
                 "drug_group_co" = "drug_group",
                 "medication_co" = "Medication") %>% 
  filter(hep_tox == "tox") %>% 
  filter(evidence_level == "high")  %>% 
  select(1:7) 
comedicationdata_heptox
```



```{r}
dose_table_full <- 
read_data(
  file = here::here("RawData/Dose table_assumed_full.xlsx"),
  sheet = "Dose_table_full")
dose_table_full
```

















