---
title: "Untitled"
author: "Arun Kumar"
date: "2024-12-06"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(here)
library(readxl)
library(tidyr)
library(dplyr)
library(ggstatsplot)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
```


```{r}
comedicationdata <- read_csv(here::here("RawData/comedication_full_data.csv"))
comedicationdata1 <- comedicationdata %>% 
  dplyr::rename( "patient_group" = "treatment",
                 "parameter_co" = "labreads",
                 "kathegorie_co" = "kathegorie",
                 "drug_group_co" = "drug_group")

comedicationdata1
```


```{r}
main_medication <- read_excel(here::here("RawData/Dose table_assumed_full.xlsx"), 
                              sheet = 2) %>% janitor::clean_names()
main_medication_data <- main_medication %>% 
  dplyr::rename("bfarm_nummer" = "edited_bf_ar_m_nummer2",
                "parameter_M" = "parameter",
                "attribut_M" = "attribut",
                "medication_M" = "treatment",
                "kathegorie_M" = "kathegorie",
                "drug_group_M" = "drug_group")

  
main_medication
main_medication_data
```

```{r}
# Einlesen und Spaltennamen säubern
main_medication_data <- read_excel(here::here("RawData/Dose table_assumed_full.xlsx"), sheet = 2) %>%
  janitor::clean_names() %>%
  rename(
    bfarm_nummer   = edited_bf_ar_m_nummer2,
    parameter_M    = parameter,
    attribut_M     = attribut,
    medication_M   = treatment,
    kathegorie_M   = kathegorie,
    drug_group_M   = drug_group
  ) %>%
  filter(kathegorie_M != "Cummulative Dosis")

# Daten anzeigen
main_medication_data

```
```{r}
main_medication_data %>% 
  filter(
    kathegorie_M %in% c(
      "Zeitraum: erste Einnahme bis Krankheitsbeginn (Tage)",
      "Zeitraum: letzte Einnahme bis Krankheitsbeginn (Tage)"
    )
  )
```


```{r}
main_medication_count <- read_excel(here::here("RawData/main_medication_count.xlsx"))
main_medication_count
```
##===============
##main_data_comed
##===============

```{r}
main_data_comed <- left_join(main_medication_data,comedicationdata1, by = c( "bfarm_nummer"))
main_data_comed
```
```{r}
mainmed_comed_all <- left_join(main_data_comed,all_data,by = c("bfarm_nummer" = "bf_ar_m_nummer"),
          relationship = "many-to-many")%>% 
  drop_na() %>% 
  dplyr::select(-drug_group_co)
mainmed_comed_all
```


```{r}
# gpt_full2 <- gpt_full %>% 
#   dplyr::rename("bfarm_nummer" = "Edited_BfArM Nummer2",
#                 "patient_group" = "Treatment",
#                 "day_of_measurement" = "attribute") %>% 
#   mutate(bfarm_nummer = as.character(bfarm_nummer))%>%
#   filter(!str_detect(day_of_measurement, "_From Start|DBS"))
# gpt_full2 

```

```{r}
# mainmed_comed_gpt <- left_join(main_data_comed,gpt_full2 ,by = "bfarm_nummer") %>% 
#   drop_na() %>% 
#   dplyr::select(-drug_group_co,-patient_group.x,-patient_group.y)
# mainmed_comed_gpt
```




##===========================
## frequeny of medication ##
##===========================


```{r}
comedicationdata %>% 
  mutate( treatment = as.factor(treatment),
          Medication = as.factor(Medication),
          kathegorie = as.factor(kathegorie)) %>% 
  dplyr::select(treatment,Medication, labreads) %>% 
  group_by(Medication)%>% 
  summarise(count = n()) %>%   
  dplyr::arrange(desc(count))
```






##=====================================
## treatment and medication together 
##====================================


```{r}
comedicationdata %>% 
  mutate( treatment = as.factor(treatment),
          Medication = as.factor(Medication),
          kathegorie = as.factor(kathegorie)) %>% 
  dplyr::select(treatment,Medication, labreads) %>% 
  group_by(treatment,Medication)%>% 
  summarise(count = n(), .groups = "drop") %>%   
  dplyr::arrange(desc(count))
```

```{r, fig.width=100, fig.height= 20}
library(dplyr)
library(ggplot2)

# Summarize counts by Medication
med_counts <- comedicationdata %>%
  mutate(Medication = as.factor(Medication)) %>%
  group_by(Medication) %>%
  summarise(count = n(), .groups = "drop")

# Create pie chart
ggplot(med_counts, aes(x = "", y = count, fill = Medication)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  labs(title = "Medication Frequency (Pie Chart)", y = "", x = "") +
  theme_void() +
  theme(legend.position = "right")

```










```{r}
medication_headline <- read_excel(here::here("RawData/medication_headlines.xlsx"), 
                                  sheet = 3)
medication_headline_long <- medication_headline %>% 
  separate_rows(group_code, sep = ",") %>%
  mutate(drug_group = as.integer(group_code))

medication_headline

medication_headline_long

```

```{r, fig.width=8, fig.height=6}
pie_chart_drug_groups <-medication_headline_long %>% 
  mutate(drug_group = as.character(drug_group)) %>%
  left_join(comedicationdata %>% mutate(drug_group = as.character(drug_group)), by = "drug_group") %>% 
  drop_na() %>% 
  group_by(medication_headline) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  mutate(
    prop = count / sum(count),
    label = paste0(medication_headline, " (", round(prop * 100, 1), "%)")
  ) %>% 
  ggplot(aes(x = "", y = count, fill = medication_headline)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  labs(title = "Pie Chart of Drug Groups") +
  theme_void() +
  theme(
    plot.title = element_text(margin = margin(b = 10), 
                              color = "black", face = "bold", hjust = 0.5),
    legend.title = element_blank()
  ) +
  geom_text(aes(label = label), 
            position = position_stack(vjust = 0.5), size = 3)

#dir.create("pie chart of drug groups", showWarnings = FALSE)
#svg("pie chart of drug groups/pie_chart_drug_groups.svg", height = 8, width = 6.5)
print(pie_chart_drug_groups)
#dev.off()

```






```{r}
library(ggrepel)


left_join(medication_headline_long %>% 
            mutate(drug_group = as.character(drug_group)),
  comedicationdata %>% mutate(drug_group = as.character(drug_group)),
  by = "drug_group") %>% 
  drop_na() %>% 
  group_by(medication_headline) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  mutate(prop = count / sum(count),
         label = paste0(medication_headline, "\n", round(prop * 100, 1), "%"),
         ypos = cumsum(prop) - 0.5 * prop) %>%
  ggplot(aes(x = "", y = prop, fill = medication_headline)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  theme_void() +
  theme(
    plot.title = element_text(margin = margin(b=10), 
                              color="black", face="bold", hjust = 0.5),
    legend.position = "none") +
  geom_text_repel(aes(y = ypos, label = label), 
                  size = 4, 
                  nudge_x = 1,
                  show.legend = FALSE,
                  segment.color = "grey50",
                  direction = "y")

```



```{r}
library(dplyr)
library(ggplot2)

# Generate pie chart with simplified percentage labels
left_join(medication_headline_long %>% mutate(drug_group = as.character(drug_group)),
  comedicationdata %>% mutate(drug_group = as.character(drug_group)),
  by = "drug_group") %>% 
  drop_na() %>% 
  group_by(medication_headline) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  mutate(prop = count / sum(count),
         label = paste0(round(prop * 100, 1), "%")) %>% 
  ggplot(aes(x = "", y = count, fill = medication_headline)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  labs(title = "Pie Chart of Drug Groups by Count") +
  theme_void() +
  theme(legend.title = element_blank()) +
  geom_text(aes(label = label), 
            position = position_stack(vjust = 1), 
            size = 4)

```

#======================================================================
##comedicationcount_labvalue_comparison#
##======================================================================

```{r}
erste_zeitraum <- comedicationdata %>% 
  dplyr::filter(grepl("Zeitraum: erste Einnahme", kathegorie)) %>% 
  mutate(bfarm_nummer = as.numeric(bfarm_nummer))
erste_zeitraum <- janitor::clean_names(erste_zeitraum)
erste_zeitraum

#colnames(erste_zeitraum)
```

```{r}

#left_join(gpt_full1, erste_zeitraum, by = "bfarm_nummer")
```

###########################################################################################################################################

### 13 05 2025 ###

```{r}
#mainmed_comed_gpt%>% 
#  dplyr::filter(Medication == "Atenolol, Clortalidon (Hypertonus)")
  
```
  

```{r}
mainmed_comed_all_filter_before <- main_data_comed %>% 
  dplyr::filter(grepl("Zeitraum: erste Einnahme bis Krankheitsbeginn",kathegorie_M)) %>% 
  dplyr::filter(grepl("Zeitraum: letzte Einnahme bis Krankheitsbeginn",kathegorie_co)) %>% 
  mutate(parameter_M1 = parameter_M +91) %>% #das hier noch mal ändern weil es funktioniert nicht
  dplyr::filter(parameter_M1 >= parameter_co)

mainmed_comed_all_filter_before#%>% 
#  dplyr::filter(Medication == "Atenolol, Clortalidon (Hypertonus)")
  
```


```{r}
mainmed_comed_all_filter_after <- main_data_comed %>% 
  dplyr::filter(grepl("Zeitraum: letzte Einnahme bis Krankheitsbeginn",kathegorie_M)) %>% 
  dplyr::filter(grepl("Zeitraum: erste Einnahme bis Krankheitsbeginn",kathegorie_co)) %>% 
  mutate(parameter_M1 = parameter_M +91) %>% #das hier noch mal ändern weil es funktioniert nicht
  dplyr::filter(parameter_M1 >= parameter_co)

mainmed_comed_all_filter_after#%>% 
#  dplyr::filter(Medication == "Atenolol, Clortalidon (Hypertonus)")
  
```



```{r}

main_medication_count <- read_excel(here::here("RawData/main_medication_count.xlsx"))
main_medication_count
```


```{r}
mainmed_comed_all_filter_before1 <- mainmed_comed_all_filter_before %>% 
  dplyr::group_by(bfarm_nummer) %>% 
  summarise(number_comedication = n_distinct(Medication)) %>% 
  dplyr::arrange(desc(number_comedication)) 
mainmed_comed_all_filter_before1
  
```


```{r}
plotdata <- 
left_join(mainmed_comed_all_filter_before1,
                      mainmed_comed_all,
                      by = "bfarm_nummer") %>% 
  dplyr::select(1,2,labreads) %>% 
  mutate(number_comedication = as.factor(number_comedication)) %>% 
  distinct(labreads,.keep_all = TRUE)

plotdata
```

```{r}
plotdata %>% 
  ggplot(aes(x = number_comedication, y = labreads)) +
  geom_point() +
  geom_smooth() +
  labs(
    title = "All groups_labvalues for amount of different comedication",
    x = "number of comedication",
    y = "ALT (U/L)" )

```




```{r}
total_medication <- left_join(main_medication_count,
                              mainmed_comed_all_filter_before1, 
                              by = "bfarm_nummer") %>% 
   mutate(number_comedication = coalesce(number_comedication, 0)) %>% 
  mutate(total_medication = medication_M_count + number_comedication) %>% 
  dplyr::arrange(desc(total_medication))#%>% 
  #mutate(total_medication = as.factor(total_medication))

total_medication
```



```{r}
total_medication1 <- left_join(total_medication,mainmed_comed_all, 
                               by = "bfarm_nummer") %>% 
  dplyr::select(1,2,3,4,18) %>% 
  drop_na() %>% 
  distinct(bfarm_nummer, .keep_all = TRUE) %>% 
  mutate(labreads = as.numeric(labreads)) %>% 
  column_to_rownames(var = "bfarm_nummer")
  

total_medication1
```

```{r}
all_groups_gpt_labvalues_drug_count <-total_medication1 %>% 
  ggplot(aes(x = total_medication, y = labreads))+
  geom_point(position = position_dodge(width = 0.2))+
  geom_smooth()+
  scale_y_continuous(limits = c(0, 10000), breaks = seq(0, 10000, by = 500))+
labs(
    title = "All groups_comparison labvalues with drug count main and comedication",
    x = "number of all medicaments",
    y = "ALT (U/L)" )+
  theme_classic()
#dir.create("plots_labvalues_drug_count", showWarnings = FALSE)
#svg("plots_labvalues_drug_count/all_groups_gpt_labvalues_drug_count.svg", height = 8, width = 6.5)
print(all_groups_gpt_labvalues_drug_count)
#dev.off()
#all_groups_gpt_labvalues_drug_count
```

```{r}
total_medication1 <- left_join(total_medication,
                               mainmed_comed_all, 
                               by = "bfarm_nummer") %>% 
  dplyr::select(1,2,3,4,18) %>% 
  drop_na() %>% 
  distinct(bfarm_nummer, .keep_all = TRUE) %>% 
  mutate(labreads = as.numeric(labreads)) %>%  
  dplyr::select(4,5)
   

total_medication1

```

```{r}
#library(pzfx)
#write_pzfx(total_medication1,"total_medication1.pzfx", row_names = FALSE)
```


```{r}
mainmed_comed_all
```

```{r}
medication_labreads <- left_join(mainmed_comed_all_filter_before1,
                                 mainmed_comed_all, by = "bfarm_nummer") %>% 
  select(1,2,16) %>% 
  mutate(labreads = as.numeric(labreads)) %>% 
  distinct(labreads, .keep_all = TRUE)
medication_labreads
```

```{r}
all_groups_gpt_labvalues_comedication_count <- medication_labreads %>% 
  mutate(number_comedication = as.factor(number_comedication)) %>% 
  ggplot(aes(x =number_comedication, y = labreads))+
  geom_point()+
  geom_smooth()+
  labs(
    x = "number of comedication",
    y = "ALT (U/L)",
    title = "All groups_comparison labvalues with drug count main and comedication", hjust = 0.5)+
  scale_y_continuous(limits = c(0,4000))+
  theme_classic()+
  theme(
    plot.title = element_text(margin = margin(b=10), 
                              color="black", face="bold", hjust = 0.5),
    axis.title.x = element_text(face= "bold", size = 15, colour = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y = element_text(face = "bold", size = 15, colour = "black"),
    legend.position = c(0.2,0.9),
    legend.text = element_text(size = 15, face = "bold"))
#dir.create("plots_labvalues_drug_count", showWarnings = FALSE)
#svg("plots_labvalues_drug_count/all_groups_gpt_labvalues_comedication_count.svg", height = 8, width = 6.5)
print(all_groups_gpt_labvalues_comedication_count)
#dev.off()
#all_groups_gpt_labvalues_comedication_count
```










```{r}
mainmed_comed_all_filter_before_future <- mainmed_comed_all %>% 
  dplyr::filter(grepl("Zeitraum: erste Einnahme bis Krankheitsbeginn",kathegorie_M)) %>% 
  dplyr::filter(grepl("Zeitraum: letzte Einnahme bis Krankheitsbeginn",kathegorie_co)) %>% 
  mutate(parameter_M2 = parameter_M -91) %>% 
  dplyr::filter(parameter_M2 < parameter_co)


mainmed_comed_all_filter_before_future %>% 
  dplyr::filter(bfarm_nummer == "99001943")
  
```







#######################################################################################################



```{r}
library(dplyr)
library(purrr)

# Step 1: Summary of how many patients have how many medications

patient_comed <- comedicationdata1 %>%
  distinct(bfarm_nummer, Medication) %>% 
  group_by(bfarm_nummer) %>% 
  summarise(comedication = n(), .groups = "drop") %>% 
  group_by(comedication) %>% 
  summarise(patient_num_per_med = n(), .groups = "drop")

# Step 2: Get distinct patient-medication pairs
distinct_data <- comedicationdata1 %>%
  distinct(bfarm_nummer, Medication)

# Step 3: Create a list based on the actual `comedication` values from patient_comed

medication_groups <- map(patient_comed$comedication, function(n) {
  distinct_data %>%
    group_by(bfarm_nummer) %>%
    filter(n() == !!n) %>%
    arrange(bfarm_nummer)
})

# Step 4: Name the list elements based on the number of meds

names(medication_groups) <- paste0("patients_with_", patient_comed$comedication, "_meds")

# Example: show patients with 2 medications
medication_groups$patients_with_2_meds

```

### venn diagramm ###


```{r}
medication_sets <- map(medication_groups, ~ unique(.x$Medication))

```

```{r}
group_names <- names(medication_sets)

pairwise_combinations <- combn(group_names, 2, simplify = FALSE)

```

```{r}
library(VennDiagram)
library(ggvenn)
library(qPCRtools)

#dir.create("venn_plots", showWarnings = FALSE)

# Loop over all combinations
for (pair in pairwise_combinations) {
  group1 <- pair[1]
  group2 <- pair[2]

  meds1 <- medication_sets[[group1]]
  meds2 <- medication_sets[[group2]]

  venn.plot <- venn.diagram(
    x = list(
      Group1 = meds1,
      Group2 = meds2
    ),
    filename = paste0("venn_plots/", group1, "_vs_", group2, ".png"),
    output = TRUE,
    category.names = c(group1, group2),
    fill = c("blue", "yellow"),
    alpha = 0.5,
    cex = 1.5,                # Size of intersection counts
    fontface = "bold",

    cat.cex = 1.5,            # Size of category labels
    cat.fontface = "bold",
    cat.pos = c(-15, 15),     # Shift labels vertically
    cat.dist = c(0.05, 0.05), # Move labels slightly outward
    cat.just = list(c(0.5, 1), c(0.5, 1)), # Centered top alignment
    margin = 0.1
  )
}

```







########################################################################################

