---
title: "Untitled"
author: "Arun Kumar"
date: "2025-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
main_medication_full_assumed_rawdata <- read_excel("E:\\Daten(x)\\Daten(lw-r)\\Abc\\Doktorarbeit SJS\\Analyse R-Statistics\\Ergebnis Vergleich dosis_labvalues\\Dose table_assumed_full.xlsx",sheet = 1)
main_medication_full_assumed_rawdata
```

```{r}
main_medication_full_assumed_headers <- read_excel("E:\\Daten(x)\\Daten(lw-r)\\Abc\\Doktorarbeit SJS\\Analyse R-Statistics\\Ergebnis Vergleich dosis_labvalues\\Dose table_assumed_full.xlsx",sheet = 1,  n_max = 4, col_names = FALSE)
main_medication_full_assumed_headers
```

```{r}
main_medication_full_assumed_combined_names <- paste(headers[2, ],headers[3, ],headers[4, ], sep = "_") %>%
  str_replace_all("_NA", "")
main_medication_full_assumed_combined_names 
```


```{r}
main_medication_full_assumed_wide <- read_excel("E:\\Daten(x)\\Daten(lw-r)\\Abc\\Doktorarbeit SJS\\Analyse R-Statistics\\Ergebnis Vergleich dosis_labvalues\\Dose table_assumed_full.xlsx",
                   skip= 4,
                   col_names = combined_names)
main_medication_full_assumed_wide
```

```{r}
main_medication_full_assumed <- main_medication_full_assumed_wide %>% 
  pivot_longer(
        cols = 3:42,
        names_to    = c("drug", "medication", "group"),
        names_pattern = "([^_]+)_([^_]+)_(.*)",
        values_to   = "labreads") %>% 
  dplyr::rename("BfArM_Nummer2" = "BfArM Nummer_BfArM Nummer_Edited_BfArM Nummer2",
                "category" = "Kathegorie_Kathegorie_Treatment") %>% 
  drop_na(labreads)
  

main_medication_full_assumed 
```


























































