---
title: "linear regression"
author: "Arun Kumar"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(performance)
library(ggplot2)
library(dlookr)
library(ggstatsplot)

```

## Analysis for ALT liver Diclofenac####

```{r}
gptaltdata <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Arun Testversionen/SJS Arun 27.05.24.xlsx", sheet = 1,skip = 1) 
#gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier
gptaltdata_long <- gptaltdata %>%
  tidyr::pivot_longer(cols = -c("Edited_BfArM Nummer2", "Treatment"), 
               names_to = "Attribute", 
               values_to = "labreads")

# Step 2: Filter the data for the specified treatment
filtered_data <- gptaltdata_long %>%
  filter(Treatment == "Leber_Diclo")

# Step 3: Count occurrences, preserving the identifier
counts_data <- filtered_data %>%
  group_by(Attribute) %>%
  summarize(count = sum(!is.na(labreads)), .groups = 'drop')

# Step 4: Merge the counts back with the original data
gptaltdata_with_counts <- filtered_data %>%
  left_join(counts_data, by = "Attribute")


# Step 5: Filter the data where count is equal to or higher than 5
 filtered_data_with_min_counts <- gptaltdata_with_counts %>%
  filter(count >= 5) %>% 
  drop_na(labreads)

# Print the updated data with counts equal to or higher than 5
print(filtered_data_with_min_counts)

## patient data###
patientidentifier <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Arun Testversionen/SJS Arun 27.05.24.xlsx", sheet = 1, skip = 1) %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  pivot_longer(cols = 3:4,
               names_to = "gender",
               values_to = "numberofpatient") %>% 
  filter(numberofpatient== 1) 

## unknown gender dataframe
test <- tibble(`Edited_BfArM Nummer2`=c("9042861","9044899"),
                     Treatment=c("Leber_Diclo","Leber_Diclo"),
                     gender=c("Unknown","Unknown"),
                     numberofpatient=c(1,1))

patientidentifier <- rbind(patientidentifier,test)

#### joined both data(labread and patientdata)

gptalst_data <-  left_join(patientidentifier,filtered_data_with_min_counts,by = ("Edited_BfArM Nummer2")) %>% 
  dplyr::select(1,2,3,6,7,8) %>% drop_na(count)
print(gptalst_data)

####check normality of Data####

gptaltdata_normality <- gptalst_data %>% 
  group_by(gender) %>% 
  normality(labreads)

print(gptaltdata_normality)

###Plot for labreads based on Gender #######

dd <- gptalst_data %>% 
  group_by(gender)
ggbetweenstats(
  data = dd,
  x = gender,
  y = labreads,
  type = "np",
  effsize.type = "unbiased",
  ylab = "ALT U/L",
  ggtheme = theme_classic()
  
)

 ##### Make the line plot of labreads for male and female####
 ##### filter the male and female for individual plot #####

gpt_summary_data <- gptalst_data  %>% filter(gender == "Female") %>% ## change (male and female for data to make graph)
  group_by(Attribute) %>%
  summarize(
    mean_labread = mean(labreads, na.rm = TRUE),
    sd_labread = sd(labreads, na.rm = TRUE),
    sem_labread = sd(labreads, na.rm = TRUE) / sqrt(n())
  )
# Create the line plot with rotated x-axis labels and error bars for both SD and SEM
max_value <- max(gpt_summary_data$mean_labread + gpt_summary_data$sem_labread, na.rm = TRUE)
breaks_up_to_500 <- seq(0, 500, by = 100)
additional_breaks <- if (max_value > 500) seq(600, max_value, by = 300) else numeric(0)
all_breaks <- c(breaks_up_to_500, additional_breaks)


# Create a vector with the x-axis labels in the desired order

### for lineplot####
### need to write all days name manually

  gpt_summary_data$Attribute <- 
  factor(gpt_summary_data$Attribute,levels = c( "GPT Day1", "GPT Day2", 
              "GPT Day3", "GPT Day4", "GPT Day5", "GPT Day6", "GPT Day7", 
              "GPT Day8", "GPT Day9", "GPT Day10", "GPT Day11",
              "GPT Day12", "GPT Day16", "GPT Day17", "GPT Day20", 
              "GPT Day26","GPT Day_Unknown"))



ggplot(gpt_summary_data, aes(x = Attribute, y = mean_labread, group = 1)) +
  geom_line() +
  geom_point() +
  # geom_errorbar(aes(ymin = mean_labread, ymax = mean_labread + sd_labread),       ##width = 0.2, color = "blue") + 
  # SD error bars in blue
  geom_errorbar(aes(ymin = mean_labread, ymax = mean_labread + sd_labread), 
                width = 0.2, color = "red") +
  geom_smooth(method = "loess", color = "lightgrey", size = 1, se = FALSE) + 
  # SEM error bars in red
  labs(title = "Line Plot of Mean ALT for Female",
       x = "Attribute",
       y = "ALT U/L",
       caption = "Red error bars: SD") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(breaks = all_breaks,
                     limits = c(0, max_value))

###BoxPlot for both the gender(Male and Female)######

max_value <- max(gpt_summary_data$mean_labread + gpt_summary_data$sem_labread, na.rm = TRUE)
breaks_up_to_500 <- seq(0, 500, by = 100)
additional_breaks <- if (max_value > 500) seq(600, max_value, by = 300) else numeric(0)
all_breaks <- c(breaks_up_to_500, additional_breaks)

## here we took our joined data of both male and female with labreads##


gptalst_data$Attribute <- factor(gptalst_data$Attribute,
  levels = c( "GPT Day1", "GPT Day2", "GPT Day3", 
              "GPT Day4", "GPT Day5", "GPT Day6", "GPT Day7", 
              "GPT Day8", "GPT Day9", "GPT Day10", "GPT Day11",
              "GPT Day12", "GPT Day16", "GPT Day17", "GPT Day20", 
              "GPT Day26","GPT Day_Unknown"))

gptalst_data %>% 
  mutate(Attribute = as.factor(Attribute)) %>% 
  group_by(Attribute) %>% 
  ggplot(aes(x = Attribute, y = labreads)) +
  geom_boxplot() +
  labs(title = "Boxplot of ALT for both gender",
       x = "Attribute",
       y = "ALT U/L") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_y_continuous(breaks = all_breaks,
                     limits = c(0, max_value))


### Dose data ###

dose_data <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Arun Testversionen/SJS Arun 27.05.24.xlsx", sheet = 9)  
  
lvdiclo_dosedata <- dose_data %>% 
  filter(Attribute == "Leber_Diclo") %>% 
  rename( "Edited_BfArM Nummer2" ="BfArM Nummer_2" )

print(lvdiclo_dosedata)


### Joined the Labreads data with dose data###

lvdiclo_dosedata_gptalst <- left_join(gptalst_data,lvdiclo_dosedata,
                            by = ("Edited_BfArM Nummer2")) %>%
                            dplyr::select(!7)


##dailydose or numberofdose#####

dd_amount <- lvdiclo_dosedata_gptalst %>%
  filter(Kathegorie == "Häufigkeit der Einnahme pro Tag")%>%
  dplyr::rename(numberofdose = Dose_mg) %>%  
  dplyr::select(1,8,10)

print(dd_amount)

##joind the dailydose amount = dd_amount with liverdiclo_gptalst labread data ####


dose_result <- left_join(lvdiclo_dosedata_gptalst,dd_amount, 
                         by = ("Edited_BfArM Nummer2")) %>%
              filter(Kathegorie.x == "Dosis (Mg/Verabreichung)" &                             Drug == "Diclofenac") %>%
                         mutate(totaldose_mg = Dose_mg*numberofdose,
                         Dose_mg = as.factor(Dose_mg)) %>%
                         group_by(Dose_mg) %>%
                         distinct()
                        
## removed the highest dose 900mg for female 93008468##
## also merged the 200, 187.5, 175 mg dose in 150mg ###
## also merged the 10 , 25 mg dose in 50 mg ####
## as Prof. Borlak told ####
dose_result1 <- dose_result[dose_result$`Edited_BfArM Nummer2` != "93008468", ]

dose_result1 <- mutate(dose_result1, totaldose_mg = ifelse(totaldose_mg == 200, 150, totaldose_mg))
dose_result1 <- mutate(dose_result1, totaldose_mg = ifelse(totaldose_mg == 25, 50, totaldose_mg))
dose_result1 <- mutate(dose_result1, totaldose_mg = ifelse(totaldose_mg == 10, 50, totaldose_mg))
dose_result1 <- mutate(dose_result1, totaldose_mg = ifelse(totaldose_mg == 175, 150, totaldose_mg))
dose_result1 <- mutate(dose_result1, totaldose_mg = ifelse(totaldose_mg == 187.5, 150, totaldose_mg))



print(dose_result1)


##########################################
## dose time series for 50mg####


dd_50mg <- dose_result1 %>% 
  filter(totaldose_mg %in% c(50)) %>% 
  mutate(Attribute.x = as.factor(Attribute.x)) %>% 
  group_by(Attribute.x) %>% 
  summarize(
    mean_labread = mean(labreads, na.rm = TRUE),
    sd_labread = sd(labreads, na.rm = TRUE))
### for lineplot
dd_50mg$Attribute.x <- factor(dd_50mg$Attribute.x,
                              levels = c( "GPT Day1", "GPT Day2", "GPT Day3", 
                                          "GPT Day6", "GPT Day11","GPT Day12",                                               "GPT Day16","GPT Day20","GPT Day26"))
ggplot(dd_50mg, aes(x = Attribute.x, 
                    y = mean_labread, group = 1)) +
            geom_line() +
            geom_point() +
            geom_errorbar(aes(ymin = mean_labread, 
                              ymax = mean_labread + sd_labread), 
                              width = 0.2, color = "red") +
            geom_smooth(method = "loess", color = "lightgrey", 
                        size = 1, se = FALSE) + 
            labs(title = "Diclofenac 50mg drug",
                     x = "Attribute",
                     y = "ALT U/L",
               caption = "Red error bars: SD") +
                theme_classic() +
          theme(
          plot.title = element_text(margin = margin(b=10), 
               color = "black", face="bold", hjust = 0.5),
         axis.text.x = element_text(face="bold", angle = 45, hjust = 1)) +
  scale_y_continuous(breaks = all_breaks,
                     limits = c(0, max_value))
  


## line plot for 100mg####

dd_100mg <- dose_result1 %>% 
  filter(totaldose_mg %in% c(100)) %>% 
  mutate(Attribute.x = as.factor(Attribute.x)) %>% 
  group_by(Attribute.x) %>% 
  summarize(
    mean_labread = mean(labreads, na.rm = TRUE),
    sd_labread = sd(labreads, na.rm = TRUE))
  
### for lineplot
dd_100mg$Attribute.x <- 
  factor(dd_100mg$Attribute.x,levels = c( "GPT Day1", "GPT Day2", "GPT Day3", 
                                          "GPT Day4","GPT Day5", "GPT Day6",
                                          "GPT Day7","GPT Day8", "GPT Day9", 
                                          "GPT Day10","GPT Day11","GPT Day12",
                                          "GPT Day17","GPT Day20","GPT Day26",
                                          "GPT Day_Unknown"))


      ggplot(dd_100mg, aes(x = Attribute.x, y = mean_labread, group = 1)) +
      geom_line() +
      geom_point() +
      geom_errorbar(aes(ymin = mean_labread, 
                        ymax = mean_labread + sd_labread), 
                        width = 0.2, color = "red") +
      geom_smooth(method = "loess", color = "lightgrey", 
                    size = 1, se = FALSE) + # SEM error bars in red
       labs(title = "Diclofenac 100mg drug",
                x = "Attribute",
                y = "ALT U/L",
          caption = "Red error bars: SD") +
          theme_classic() +
          theme(
        plot.title = element_text(margin  = margin(b=10), 
                                    color = "black", 
                                    face  = "bold", 
                                    hjust = 0.5),
       axis.text.x = element_text(face = "bold", 
                                  angle = 45, 
                                  hjust = 1)) +
       scale_y_continuous(breaks = all_breaks,
                     limits = c(0, max_value))


###line plot for 150mg#### 


dd_150mg <- dose_result1 %>% 
  filter(totaldose_mg %in% c(150)) %>% 
  mutate(Attribute.x = as.factor(Attribute.x)) %>% 
  group_by(Attribute.x) %>% 
  summarize(
    mean_labread = mean(labreads, na.rm = TRUE),
    sd_labread = sd(labreads, na.rm = TRUE)) %>% 
  filter(!is.na(mean_labread) & is.finite(mean_labread) & is.finite(sd_labread))
  
### for lineplot
 dd_150mg$Attribute.x <- 
   factor(dd_150mg$Attribute.x,levels = c( "GPT Day1","GPT Day3", 
                                           "GPT Day4","GPT Day5", "GPT Day6",
                                           "GPT Day8", "GPT Day9", 
                                           "GPT Day10","GPT Day12",
                                           "GPT Day16","GPT Day26","GPT Day_Unknown"))


     ggplot(dd_150mg, aes(x = Attribute.x, 
                          y = mean_labread, group = 1)) +
    geom_line() +
    geom_point() +
    geom_errorbar(aes(ymin = mean_labread, 
                      ymax = mean_labread + sd_labread), 
                     width = 0.2, color = "red") +
    geom_smooth(method = "loess", color = "lightgrey", 
                  size = 1, se = FALSE) + 
            labs(title = "Diclofenac 150mg drug",
                     x = "Attribute",
                     y = "ALT U/L",
               caption = "Red error bars: SD") +
    theme_classic() +
    theme(
            plot.title = element_text(margin = margin(b=10), color="black", 
                                      face="bold", hjust = 0.5),
           axis.text.x = element_text(face="bold", angle = 45, 
                                      hjust = 1)) +
          scale_y_continuous(breaks = all_breaks,
                             limits = c(0, max_value))


###line plot for 200mg#### 


dd_200mg <- dose_result1 %>% 
  filter(totaldose_mg %in% c(200)) %>% 
  mutate(Attribute.x = as.factor(Attribute.x)) %>% 
  group_by(Attribute.x) %>% 
  summarize(
    mean_labread = mean(labreads, na.rm = TRUE),
    sd_labread = sd(labreads, na.rm = TRUE)) %>% 
  filter(!is.na(mean_labread) & is.finite(mean_labread) & is.finite(sd_labread))
  
### for lineplot
  dd_200mg$Attribute.x <- 
    factor(dd_200mg$Attribute.x,levels = c( "GPT Day5","GPT Day11", 
                                            "GPT Day26"))


ggplot(dd_200mg, aes(x = Attribute.x, 
                     y = mean_labread, group = 1)) +
   geom_line() +
    geom_point() +
    geom_errorbar(aes(ymin = mean_labread, 
                      ymax = mean_labread + sd_labread), 
                     width = 0.2, color = "red") +
    geom_smooth(method = "loess", color = "lightgrey", 
                  size = 1, se = FALSE) + 
            labs(title = "Diclofenac 200mg drug",
                     x = "Attribute",
                     y = "ALT U/L",
               caption = "Red error bars: SD") +
    theme_classic() +
    theme(
            plot.title = element_text(margin = margin(b=10), color="black", 
                                      face="bold", hjust = 0.5),
           axis.text.x = element_text(face="bold", angle = 45, 
                                      hjust = 1)) +
          scale_y_continuous(breaks = all_breaks,
                             limits = c(0, max_value))


##### linear regression###
### we prepare linear model###
### check model with performance library####


ww <- dose_result %>% 
  filter(Drug == "Diclofenac") %>% 
  distinct(`Edited_BfArM Nummer2`, .keep_all = TRUE) %>% 
  group_by(totaldose_mg)

print(ww)


ggplot(dose_result1, aes(x = totaldose_mg, y = labreads)) +
  geom_point(color = "blue", size = 2) +    # Scatter plot points
  geom_smooth()


library(performance)
library(ggplot2)

# Fit the linear model
lm_model <- lm(labreads ~ totaldose_mg, data = dose_result1)

check_model(lm_model)

# Extract the coefficients
intercept <- coef(lm_model)[1]
slope <- coef(lm_model)[2]

# Create the equation string
equation <- paste("y = ", round(intercept, 2), " + ", 
                  round(slope, 2), "x", sep = "")

r_squared <- summary(lm_model)$r.squared

# Create the scatter plot with linear regression line, R-squared, and equation
ggplot(dose_result1, aes(x = totaldose_mg, y = labreads)) +
  geom_point(color = "blue", size = 2) +    # Scatter plot points
  geom_smooth(method = "lm", se = TRUE, 
              color = "red", linetype = "dashed")+
  
  labs(title = "linerar regression for Diclofenac",
           x = "daily dose in mg",
           y = " ALT in U/L") +
  theme_classic() +
  theme(
    plot.title = element_text(margin = margin(b=10), color="black", 
                                      face="bold", hjust = 0.5),
           axis.text.x = element_text(face="bold", angle = 45, 
                                      hjust = 1)) +
  annotate("text", x = 150, y = 2500, 
               label = paste("R² =", round(r_squared, 2)), 
               hjust = 1.1, vjust = 2, 
               size  = 5, 
               color = "black") +
  annotate("text", x = 150, y = 2400, 
               label = equation, 
               hjust = 1.1, vjust = 3.5, 
                size = 5, 
               color = "black")

###################cumulative dose = CD #######


CD_dose <- lvdiclo_dosedata_gptalst %>% 
  filter(Kathegorie == "Kumulative Dosis" & Drug == "Diclofenac")

num_dosetaken <- lvdiclo_dosedata_gptalst %>% 
    filter(Kathegorie == "Dauer der Einnahme (Tage)" & Drug == "Diclofenac") %>% 
    rename("daysofintake" = "Dose_mg") %>% dplyr::select(1,10)

CD_dose_weekdata <- left_join(CD_dose, num_dosetaken, 
                              by = ("Edited_BfArM Nummer2")) %>% 
                    distinct(`Edited_BfArM Nummer2`, .keep_all = TRUE) %>% 
                    drop_na(daysofintake)


cumulativ_4week <- CD_dose_weekdata %>% 
           filter(daysofintake <= 28) %>% 
           mutate(daysofintake = as.factor(daysofintake)) %>% 
           drop_na(Dose_mg)  
  
  ###removed the 900mg dose "93008468"######

  cumulativ_4week <- cumulativ_4week[cumulativ_4week$`Edited_BfArM Nummer2` != "93008468", ]
  
 cumulativ_4week %>% 
      ggplot( aes(x = daysofintake, y = Dose_mg)) +
      geom_point(color = "blue", size = 2) +    # Scatter plot points
      geom_smooth(se = TRUE, color = "red", 
                  linetype = "dashed")+
      labs(title = "Diclofene cummulative dose for 4 weeks",
               x = "Number ofday",
                y = "Cummulative dose (mg)") +
  theme_classic() +
  theme(plot.title = element_text(margin = margin(b=10), color="black", 
                                      face="bold", hjust = 0.5),
           axis.text.x = element_text(face="bold", angle = 45, 
                                      hjust = 1))
  
   
### Cumulative Dose for 50-1000(mg)########


library(dplyr)
library(readxl)

# Read the Excel file and filter the data
CD_liverdiclo <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Arun Testversionen/SJS Arun 27.05.24.xlsx", sheet = 12, skip = 1) %>%
  filter(Cumulative_Dose > 0.0 & Cumulative_Dose <= 1000 & Treatment == "Leber_Diclo")

# Summarize the counts of each Cumulative_Dose
dose_counts <- CD_liverdiclo %>%
  group_by(Cumulative_Dose) %>%
  summarise(count = n())

# Add the count column back into the original data frame
CD_liverdiclo <- CD_liverdiclo %>%
  left_join(dose_counts, by = "Cumulative_Dose")

# View the result
print(CD_liverdiclo)

  
CD_liverdiclo %>% 
  mutate(Cumulative_Dose = as.factor(Cumulative_Dose)) %>% 
  ggplot(aes(x = Cumulative_Dose, y = count))+
  geom_point()+
  labs(title = "Cumultive Dose Diclofenac(50-1000)mg",
       x = "cumulative Dose(mg)",
       y = "Number of Patient") + ### label y axis according your sample name
  theme_classic() +
  theme(plot.title = element_text(margin = margin(b=10), color="black", 
                                     face ="bold", hjust = 0.5),
          axis.text.x = element_text(face ="bold", angle = 45, 
                                    hjust = 1))
### Cumulative Dose higer than 1000(mg)########


library(dplyr)
library(readxl)

# Read the Excel file and filter the data
CD_liverdiclo1k <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Arun Testversionen/SJS Arun 27.05.24.xlsx", sheet = 12, skip = 1) %>%
  filter(Cumulative_Dose >= 1000 & Treatment == "Leber_Diclo")

dose_counts1K <-CD_liverdiclo1k %>%
  group_by(Cumulative_Dose) %>%
  summarise(count = n())

# View the result
#print(CD_liverdiclo1k)

  
 dose_counts1K %>% 
  mutate(Cumulative_Dose = Cumulative_Dose/1000) %>% 
   mutate(Cumulative_Dose = as.factor(Cumulative_Dose)) %>% 
  ggplot(aes(x = Cumulative_Dose, y = count))+
  geom_point()+
  labs(title = "Cumultive Dose Diclofenac (1g and higher)",
       x = "cumulative Dose(g)",
       y = "Number of Patient") + ### label y axis according your sample name
  theme_classic() +
  theme(plot.title = element_text(margin = margin(b=10), color="black", 
                                     face ="bold", hjust = 0.5),
          axis.text.x = element_text(face ="bold", angle = 45, 
                                    hjust = 1))
  
library(dplyr)
library(readxl)
library(ggplot2)

# Read the Excel file and filter the data
CD_liverdiclo <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Arun Testversionen/SJS Arun 27.05.24.xlsx", sheet = 12, skip = 1) %>%
  filter(Cumulative_Dose > 0.0  & Treatment == "Leber_Diclo")

# Create dose groups
CD_liverdiclo <- CD_liverdiclo %>%
  mutate(Dose_Group = cut(Cumulative_Dose,
                          breaks = c(0, 1000, 5000, 20000, Inf),
                          labels = c("50mg to 1g", "1g to 5g", "5g to 20g", " Higher to 20"),
                          right = FALSE)) # right = FALSE to make intervals inclusive of lower bound and exclusive of upper bound

# View the result with dose groups
print(CD_liverdiclo)

# Plot frequency of each dose group
ggplot(CD_liverdiclo, aes(x = Dose_Group)) +
  geom_bar() +
  labs(title = "Frequency of Cumulative Dose Groups",
       x = "Dose Group",
       y = "Frequency") +
  theme_classic() +
  theme(
    plot.title = element_text(margin = margin(b = 10), color = "black", 
                              face = "bold", hjust = 0.5),
    axis.text.x = element_text(face = "bold", angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0, max(table(CD_liverdiclo$Dose_Group))))


CD_liverdiclo_labreads <- left_join(CD_liverdiclo,gptalst_data, 
                                    by = "Edited_BfArM Nummer2") %>% 
                          drop_na(count) %>% 
                          filter(Attribute == "GPT Day1") %>% 
                          dplyr::select(1,2,3,7,8,9,11,12,13)

print(CD_liverdiclo_labreads)

ggplot(CD_liverdiclo_labreads, aes(x = Dose_Group, y = labreads)) +
  geom_boxplot() +
  geom_jitter()+
  labs(title = "Diclofenac ALT (Day1)",
           x = "Dose Group",
           y = "ALT U/L") +
  theme_classic() +
  theme(
    plot.title = element_text(margin = margin(b = 10), color = "black",
                              face = "bold", hjust = 0.5),
    axis.text.x = element_text(face = "bold", angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0, max(CD_liverdiclo_labreads$labreads)))


CD_liverdiclo_labreadsall <- left_join(CD_liverdiclo,gptalst_data, 
                                       by = "Edited_BfArM Nummer2") %>% 
                              drop_na(count) %>% 
                              dplyr::select(1,2,3,7,8,9,11,12,13)

  print(CD_liverdiclo_labreadsall)

ggplot(CD_liverdiclo_labreadsall, aes(x = Dose_Group, y = labreads)) +
          geom_boxplot() +
          geom_jitter()+
          labs(title = "Diclofenac ALT (All Days)",
                   x = "Dose Group",
                   y = "ALT U/L") +
          theme_classic() +
  theme(
    plot.title = element_text(margin = margin(b = 10), color = "black", 
                              face = "bold", hjust = 0.5),
    axis.text.x = element_text(face = "bold", angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0, max(CD_liverdiclo_labreadsall$labreads)))

###TTO #####

TTO_liverdiclo <- left_join(CD_liverdiclo,gptalst_data,  by = "Edited_BfArM Nummer2") %>% 
  drop_na(count) %>% 
  dplyr::select(1,2,3,8,12,13) %>% 
  mutate(TTO = as.factor(TTO)) 
  
 TTO_liverdiclo  %>%  
  ggplot(aes(x = TTO, y = labreads)) +
          geom_point() +
          geom_jitter()+
          labs(title = "Diclofenac TTO",
                   x = "TTO",
                   y = "ALT U/L") +
          theme_classic() +
  theme(
    plot.title = element_text(margin = margin(b = 10), color = "black", 
                              face = "bold", hjust = 0.5),
    axis.text.x = element_text(face = "bold", angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0, max(CD_liverdiclo_labreadsall$labreads)))
  
 
############## TTO in Group #### 

library(dplyr)
library(ggplot2)

# Ensure TTO and labreads columns has no  NAs appropriately
TTO_liverdiclo1 <- left_join(CD_liverdiclo, gptalst_data, by = "Edited_BfArM Nummer2") %>%
  drop_na(TTO, labreads, count) %>%
  dplyr::select(1, 2, 3, 8, 12, 13)

# Create TTO_Group with appropriate breaks and labels
TTO_group <- TTO_liverdiclo1 %>%
  mutate(TTO_Group = cut(TTO,
                         breaks = c(0, 10, 100, 500, Inf),
                         labels = c("1 to 10", "1 to 100", "100 to 500", "Higher to 500"),
                         right = FALSE))


TTO_group %>%
  ggplot(aes(x = TTO_Group, y = labreads)) +
  geom_boxplot() +
  geom_jitter() +
  labs(title = "Diclofenac TTO",
       x = "TTO Group",
       y = "ALT U/L") +
  theme_classic() +
  theme(
    plot.title = element_text(margin = margin(b = 10), color = "black",
                              face = "bold", hjust = 0.5),
    axis.text.x = element_text(face = "bold", angle = 45, hjust = 1)
  ) +
  scale_y_continuous(limits = c(0, max(CD_liverdiclo_labreadsall$labreads, na.rm = TRUE)))

```


