---
title: "SJS"
author: "Arun Kumar"
date: "2023-04-06"
output: html_document
---
## load the libraries for data analysis
```{r}
library(readxl)
library(tidyr)
library(dplyr)
```

```{r, echo=TRUE}

rawdata <- read_excel("Übersicht Laborwerte (Laborwerte fertig).xlsx",
                      sheet = 1,skip = 2)
```

## convert the data from tibble to data frame.
```{r}
rawdf1 <- as.data.frame(rawdata)
# # Remove leading and trailing spaces from column names
# names(rawdf1) <- trimws(names(rawdf1))
# rawdf1 <- as.data.frame(rawdf1)
```

## conversion of  from char to numeric values
```{r}
rawdf1$`Ck Day4` <- as.numeric(rawdf1$`Ck Day4`)
```
## data convert to longerformat

```{r}
rawdf1 %>% 
  select(1:2,3:35) ->ck_rawdata
ck_rawdata %>% 
  pivot_longer(cols = 3:35,
               names_to = "attribute",
               values_to = "labreads") %>% 
  drop_na()->ck_long
```



```{r}
rawdf1 %>% 
  select(1:2,36:53)->ckmb_rawdata
ckmb_rawdata %>% 
  pivot_longer(cols = 3:20,
               names_to = "attribute",
                values_to = "labreads") %>% 
   drop_na()->ckmb_long

```


```{r}
rawdf1 %>% 
  select(1:2,54:104)->quick_rawdata

quick_rawdata %>%
  pivot_longer(cols = 3:53,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->quick_long

```



```{r}
rawdf1 %>% 
  select(1:2,105:150)->inr_rawdata

inr_rawdata %>%
  pivot_longer(cols = 3:48,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->inr_long

```


```{r}
rawdf1 %>% 
  select(1:2,151:159)->troponin_i_rawdata

troponin_i_rawdata %>%
  pivot_longer(cols = 3:11,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->troponin_i_long
```



```{r}
rawdf1 %>% 
  select(1:2,160:168)->prothrombin_rawdata

prothrombin_rawdata %>%
  pivot_longer(cols = 3:11,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->prothrombin_long
```



```{r}
rawdf1 %>% 
  select(1:2,169:211)->ptt_rawdata

ptt_rawdata$`PTT Day2`  <- as.numeric(ptt_rawdata$`PTT Day2`)


ptt_rawdata %>%
  tidyr::pivot_longer(.,cols = 3:45,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ptt_long
```



```{r}
rawdf1 %>% 
  select(1:2,212:222)->tz_rawdata

tz_rawdata %>%
  pivot_longer(cols = 3:13,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->tz_long
```



```{r}
rawdf1 %>% 
  select(1:2,223:231)->antithrombin_3_rawdata

antithrombin_3_rawdata %>%
  pivot_longer(cols = 3:11,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->antithrombin_3_long
```



```{r}
rawdf1 %>% 
  select(1:2,232:234)->serummyoglobin_rawdata

serummyoglobin_rawdata %>%
  pivot_longer(cols = 3:5,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->serummyoglobin_long
```



```{r}
rawdf1 %>% 
  select(1:2,235:238)->d_dimer_rawdata

d_dimer_rawdata %>%
  pivot_longer(cols = 3:6,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->d_dimer_long
```



```{r}
rawdf1 %>% 
  select(1:2,239:264)->fibrinogen_rawdata

fibrinogen_rawdata %>%
  pivot_longer(cols = 3:28,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->fibrinogen_long
```



```{r}
rawdf1 %>% 
  select(1:2,265:336)->leukozyten_rawdata

leukozyten_rawdata %>%
  pivot_longer(cols = 3:74,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->leukozyten_long
```



```{r}
rawdf1 %>% 
  select(1:2,337:463)->got_rawdata

got_rawdata %>%
  pivot_longer(cols = 3:129,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->got_long
```



```{r}
rawdf1 %>% 
  select(1:2,464:595)->gpt_rawdata


gpt_rawdata$`GPT Day11`  <- as.numeric(gpt_rawdata$`GPT Day11`)


gpt_rawdata %>%
  pivot_longer(cols = 3:134,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->gpt_long
```



```{r}
rawdf1 %>% 
  select(1:2,596:707)->ggt_rawdata

ggt_rawdata$`GGT Day22`  <- as.numeric(ggt_rawdata$`GGT Day22`)
ggt_rawdata$`GGT Day34`  <- as.numeric(ggt_rawdata$`GGT Day34`)



ggt_rawdata %>%
  pivot_longer(cols = 3:114,
               names_to = "attribute",
                values_to = "labreads")  %>%
    drop_na()->ggt_long
```



```{r}
rawdf1 %>% 
  select(1:2,708:757)->ldh_rawdata

ldh_rawdata$`LDH Day22` <- as.numeric(ldh_rawdata$`LDH Day22`)
ldh_rawdata$`LDH Day24` <- as.numeric(ldh_rawdata$`LDH Day24`)

ldh_rawdata %>%
  pivot_longer(cols = 3:52,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ldh_long
```



```{r}
rawdf1 %>% 
  select(1:2,758:794)->gldh_rawdata

gldh_rawdata %>%
  pivot_longer(cols = 3:39,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->gldh_long
```



```{r}
rawdf1 %>% 
  select(1:2,795:827)->triglyceride_rawdata

triglyceride_rawdata %>%
  pivot_longer(cols = 3:35,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->triglyceride_long
```



```{r}
rawdf1 %>% 
  select(1:2,828:852)->cholesterin_rawdata

cholesterin_rawdata %>%
  pivot_longer(cols = 3:27,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->cholesterin_long
```



```{r}
rawdf1 %>% 
  select(1:2,853:865)->hdl_rawdata

hdl_rawdata %>%
  pivot_longer(cols = 3:15,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->hdl_long
```



```{r}
rawdf1 %>% 
  select(1:2,866:876)->ldl_rawdata

ldl_rawdata %>%
  pivot_longer(cols = 3:13,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ldl_long
```



```{r}
rawdf1 %>% 
  select(1:2,877:908)->lymphozyten_rawdata

lymphozyten_rawdata %>%
  pivot_longer(cols = 3:34,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->lymphozyten_long
```



```{r}
rawdf1 %>% 
  select(1:2,909:974)->hb_rawdata

hb_rawdata$`Hb Day_Unknown` <- as.numeric(hb_rawdata$`Hb Day_Unknown`)

hb_rawdata %>%
  pivot_longer(cols = 3:68,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->hb_long
```



```{r}
rawdf1 %>% 
  select(1:2,975:1068)->total_bilirubin_rawdata

total_bilirubin_rawdata$`TotalBilirubin Day1` <- as.numeric(total_bilirubin_rawdata$`TotalBilirubin Day1`)
total_bilirubin_rawdata$`TotalBilirubin Day5` <- as.numeric(total_bilirubin_rawdata$`TotalBilirubin Day5`)
total_bilirubin_rawdata$`TotalBilirubin Day15` <- as.numeric(total_bilirubin_rawdata$`TotalBilirubin Day15`)

total_bilirubin_rawdata %>%
  pivot_longer(cols = 3:96,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->total_bilirubin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1069:1111)->direct_bilirubin_rawdata

direct_bilirubin_rawdata$`DirectBilirubin Day4` <- as.numeric(direct_bilirubin_rawdata$`DirectBilirubin Day4`)

direct_bilirubin_rawdata %>%
  pivot_longer(cols = 3:45,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->direct_bilirubin_long
```


```{r}
rawdf1 %>% 
  select(1:2,1112:1121)->indirect_bilirubin_rawdata

#indirect_bilirubin_rawdata$`IndirectBilirubin Day4` <- as.numeric(indirect_bilirubin_rawdata$`IndirectBilirubin Day4`)

indirect_bilirubin_rawdata %>%
  pivot_longer(cols = 3:12,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->indirect_bilirubin_long
```


```{r}
rawdf1 %>% 
  select(1:2,1122:1148)->gesamteiweiß_rawdata

gesamteiweiß_rawdata$`Gesamteiweiß Day_Unknown` <- as.numeric(gesamteiweiß_rawdata$`Gesamteiweiß Day_Unknown`)
gesamteiweiß_rawdata$`Gesamteiweiß Day9` <- as.numeric(gesamteiweiß_rawdata$`Gesamteiweiß Day9`)

gesamteiweiß_rawdata %>%
  pivot_longer(cols = 3:29,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->gesamteiweiß_long
```



```{r}
rawdf1 %>% 
  select(1:2,1149:1246)->ap_rawdata

ap_rawdata$`AP Day13` <- as.numeric(ap_rawdata$`AP Day13`)
ap_rawdata$`AP Day16` <- as.numeric(ap_rawdata$`AP Day16`)
ap_rawdata$`AP Day24` <- as.numeric(ap_rawdata$`AP Day24`)

ap_rawdata %>%
  pivot_longer(cols = 3:100,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ap_long
```



```{r}
rawdf1 %>% 
  select(1:2,1247:1280)->cholinesterase_rawdata

cholinesterase_rawdata$`Cholinesterase Day_Unknown` <- as.numeric(cholinesterase_rawdata$`Cholinesterase Day_Unknown`)

cholinesterase_rawdata$`Cholinesterase Day2` <- as.numeric(cholinesterase_rawdata$`Cholinesterase Day2`)

cholinesterase_rawdata %>%
  pivot_longer(cols = 3:36,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->cholinesterase_long
```



```{r}
rawdf1 %>% 
  select(1:2,1281:1339)->kreatinin_rawdata


kreatinin_rawdata$`Kreatinin Day_Unknown` <- as.numeric(kreatinin_rawdata$`Kreatinin Day_Unknown`)

kreatinin_rawdata %>%
  pivot_longer(cols = 3:61,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->kreatinin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1340:1364)->amylase_rawdata

amylase_rawdata %>%
  pivot_longer(cols = 3:27,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->amylase_long
```



```{r}
rawdf1 %>% 
  select(1:2,1365:1402)->lipase_rawdata

lipase_rawdata %>%
  pivot_longer(cols = 3:40,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->lipase_long
```


```{r}
rawdf1 %>% 
  select(1:2,1403:1451)->crp_rawdata
crp_rawdata$`CRP Day2` <- as.numeric(crp_rawdata$`CRP Day2`)

crp_rawdata %>%
  pivot_longer(cols = 3:51,
               names_to = "attribute",
                values_to = "labreads")%>%
 drop_na()->crp_long
```


```{r}
rawdf1 %>% 
  select(1:2,1452:1498)->harnstoff_rawdata

harnstoff_rawdata %>%
  pivot_longer(cols = 3:49,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->harnstoff_long
```



```{r}
rawdf1 %>% 
  select(1:2,1490:1523)->harnsäure_rawdata

harnsäure_rawdata %>%
  pivot_longer(cols = 3:27,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->harnsäure_long
```



```{r}
rawdf1 %>% 
  select(1:2,1524:1568)->erythrozyten_rawdata
  
  
  #erythrozyten_rawdata$`Erythrozyten Day18` <- as.numeric(erythrozyten_rawdata$v)

erythrozyten_rawdata %>%
  pivot_longer(cols = 3:47,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->erythrozyten_long
```




```{r}
rawdf1 %>% 
  select(1:2,1569:1627)->thrombozyten_rawdata

thrombozyten_rawdata$`Thrombozyten Day2` <- as.numeric(thrombozyten_rawdata$`Thrombozyten Day2`)

thrombozyten_rawdata$`Thrombozyten Day13` <- as.numeric(thrombozyten_rawdata$`Thrombozyten Day13`)



thrombozyten_rawdata %>%
  pivot_longer(cols = 3:61,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->thrombozyten_long
```




```{r}
rawdf1 %>% 
  select(1:2,1628:1634)->haptoglobin_rawdata

haptoglobin_rawdata %>%
  pivot_longer(cols = 3:9,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->haptoglobin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1635:1646)->bsg_rawdata

bsg_rawdata %>%
  pivot_longer(cols = 3:14,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->bsg_long
```



```{r}
rawdf1 %>% 
  select(1:2,1647:1671)->monozyten_rawdata

monozyten_rawdata %>%
  pivot_longer(cols = 3:27,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->monozyten_long
```



```{r}
rawdf1 %>% 
  select(1:2,1672:1713)->eosinophile_rawdata

eosinophile_rawdata %>%
  pivot_longer(cols = 3:44,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->eosinophile_long
```



```{r}
rawdf1 %>% 
  select(1:2,1714:1750)->neutrophile_rawdata

neutrophile_rawdata %>%
  pivot_longer(cols = 3:39,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->neutrophile_long
```



```{r}
rawdf1 %>% 
  select(1:2,1751:1762)->stabkernige_rawdata

stabkernige_rawdata %>%
  pivot_longer(cols = 3:14,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->stabkernige_long
```



```{r}
rawdf1 %>% 
  select(1:2,1763:1778)->segmentkernige_rawdata

segmentkernige_rawdata %>%
  pivot_longer(cols = 3:18,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->segmentkernige_long
```



```{r}
rawdf1 %>% 
  select(1:2,1779:1798)->basophile_rawdata

basophile_rawdata %>%
  pivot_longer(cols = 3:22,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->basophile_long
```




```{r}
rawdf1 %>% 
  select(1:2,1799:1833)->albumin_rawdata

albumin_rawdata %>%
  pivot_longer(cols = 3:37,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->albumin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1834:1837)->gamma_globulin_rawdata

gamma_globulin_rawdata %>%
  pivot_longer(cols = 3:6,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->gamma_globulin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1838:1841)->alpha_globulin_rawdata

alpha_globulin_rawdata %>%
  pivot_longer(cols = 3:6,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->alpha_globulin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1842:1844)->beta_globulin_rawdata

beta_globulin_rawdata %>%
  pivot_longer(cols = 3:5,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->beta_globulin_long
```



```{r}
rawdf1 %>% 
  select(1:2,1845:1855)->ph_blut_rawdata

ph_blut_rawdata %>%
  pivot_longer(cols = 3:13,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ph_blut_long
```



```{r}
rawdf1 %>% 
  select(1:2,1856:1916)->hämatokrit_rawdata

hämatokrit_rawdata %>%
  pivot_longer(cols = 3:63,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->hämatokrit_long
```



```{r}
rawdf1 %>% 
  select(1:2,1917:1962)->mcv_rawdata

mcv_rawdata %>%
  pivot_longer(cols = 3:48,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->mcv_long
```



```{r}
rawdf1 %>% 
  select(1:2,1963:2002)->mch_rawdata


mch_rawdata$`MCH Day1` <- as.numeric(mch_rawdata$`MCH Day1`)
mch_rawdata$`MCH Day4` <- as.numeric(mch_rawdata$`MCH Day4`)

mch_rawdata %>%
  pivot_longer(cols = 3:42,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->mch_long
```



```{r}
rawdf1 %>% 
  select(1:2,2003:2039)->mchc_rawdata

mchc_rawdata %>%
  pivot_longer(cols = 3:39,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na() ->mchc_long
```



```{r}
rawdf1 %>% 
  select(1:2,2040:2078)->natrium_rawdata

natrium_rawdata %>%
  pivot_longer(cols = 3:41,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->natrium_long
```


```{r}
rawdf1 %>% 
  select(1:2,2079:2118)->kalium_rawdata

kalium_rawdata %>%
  pivot_longer(cols = 3:42,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->kalium_long
```



```{r}
rawdf1 %>% 
  select(1:2,2119:2155)->kalzium_rawdata

kalzium_rawdata %>%
  pivot_longer(cols = 3:39,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->kalzium_long
```



```{r}
rawdf1 %>% 
  select(1:2,2156:2169)->magnesium_rawdata

magnesium_rawdata %>%
  pivot_longer(cols = 3:16,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->magnesium_long
```



```{r}
rawdf1 %>% 
  select(1:2,2170:2184)->chlorid_rawdata

chlorid_rawdata %>%
  pivot_longer(cols = 3:17,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->chlorid_long
```



```{r}
rawdf1 %>% 
  select(1:2,2185:2204)->serum_eisen_rawdata

serum_eisen_rawdata %>%
  pivot_longer(cols = 3:22,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->serum_eisen_long
```


```{r}
rawdf1 %>% 
  select(1:2,2205:2208)->transferrin_rawdata

transferrin_rawdata %>%
  pivot_longer(cols = 3:6,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->transferrin_long
```


```{r}
rawdf1 %>% 
  select(1:2,2209:2228)->ferritin_rawdata


ferritin_rawdata$`Ferritin Day4` <- as.numeric(ferritin_rawdata$`Ferritin Day4`)
ferritin_rawdata$`Ferritin Day10` <- as.numeric(ferritin_rawdata$`Ferritin Day10`)

ferritin_rawdata %>%
  pivot_longer(cols = 3:22,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ferritin_long
```



```{r}
rawdf1 %>% 
  select(1:2,2229:2236)->fieber_rawdata

fieber_rawdata %>%
  pivot_longer(cols = 3:10,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->fieber_long
```

```{r}
rawdf1 %>% 
  select(1:2,2237:2242)->hba1c_rawdata

hba1c_rawdata %>%
  pivot_longer(cols = 3:8,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->hba1c_long
```

```{r}
rawdf1 %>% 
  select(1:2,2243:2277)->glucose_rawdata

glucose_rawdata %>%
  pivot_longer(cols = 3:37,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->glucose_long
```

```{r}
rawdf1 %>% 
  select(1:2,2278:2295)->ammonika_rawdata

ammonika_rawdata %>%
  pivot_longer(cols = 3:20,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->ammonika_long
```

```{r}
rawdf1 %>% 
  select(1:2,2296:2303)->lactat_rawdata


lactat_rawdata$`Lactat Day1` <- as.numeric(lactat_rawdata$`Lactat Day1`)

lactat_rawdata %>%
  pivot_longer(cols = 3:10,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->lactat_long
```

```{r}
rawdf1 %>% 
  select(1:2,2304:2315)->phosphat_rawdata

phosphat_rawdata %>%
  pivot_longer(cols = 3:14,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->phosphat_long
```

```{r}
rawdf1 %>% 
  select(1:2,2316:2334)->gfr_rawdata

gfr_rawdata %>%
  pivot_longer(cols = 3:21,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->gfr_long
```


```{r}
rawdf1 %>% 
  select(1:2,2335:2338)->blut_IgA_rawdata

blut_IgA_rawdata %>%
  pivot_longer(cols = 3:6,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->blut_IgA_long
```


```{r}
rawdf1 %>% 
  select(1:2,2339:2343)->blut_IgG_rawdata

blut_IgG_rawdata %>%
  pivot_longer(cols = 3:7,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->blut_IgG_long
```


```{r}
rawdf1 %>% 
  select(1:2,2344:2346)->blut_IgM_rawdata

blut_IgM_rawdata %>%
  pivot_longer(cols = 3:5,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->blut_IgM_long
```


```{r}
rawdf1 %>% 
  select(1:2,2347:2347)->blut_IgE_rawdata

blut_IgE_rawdata %>%
  pivot_longer(cols = 3:3,
               names_to = "attribute",
                values_to = "labreads") %>%
   drop_na()->blut_IgE_long
```