---
title: "Untitled"
author: "Arun Kumar"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r} 
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(ggstatsplot)
```

```{r}
##Please change the path according your source file ##
#gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
#gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

#gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier
gptaltraw_data_long <- gpt_rawdata %>%
  tidyr::pivot_longer(cols = -c("Edited_BfArM Nummer2", "Treatment"), 
               names_to = "Attribute", 
               values_to = "labreads")

gptaltraw_data_long

## to clean the backticks from header##
## use janitor library##
library(janitor)
gptaltraw_data_long <- janitor::clean_names(gptaltraw_data_long)
gptaltraw_data_long



control_2_data <- gptaltraw_data_long %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)



control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "GPT_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
#gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier
#gptaltraw_data_long <- gpt_rawdata %>%
#  tidyr::pivot_longer(cols = -c("Edited_BfArM Nummer2", "Treatment"), 
#               names_to = "Attribute", 
#               values_to = "labreads")

#gptaltraw_data_long

## to clean the backticks from header##
## use janitor library##
#library(janitor)
#gptaltraw_data_long <- janitor::clean_names(gptaltraw_data_long)
#gptaltraw_data_long

data_with_cleaned_name <- janitor::clean_names(got_long)


control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)



control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "GOT_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(ck_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "ck_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```
```{r}
data_with_cleaned_name <- janitor::clean_names(quick_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "quick_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(inr_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "inr_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(ptt_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "ptt_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```
```{r}
data_with_cleaned_name <- janitor::clean_names(antithrombin_3_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "antithrombin_3_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(fibrinogen_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "fibrinogen_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(leukozyten_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "leukozyten_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(ggt_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "ggt_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(ldh_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "ldh_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(cholesterin_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "cholesterin_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(lymphozyten_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "lymphozyten_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(hb_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "hb_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(total_bilirubin_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "total_bilirubin_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(gesamteiweiß_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "gesamteiweiß_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(ap_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "ap_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(kreatinin_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "kreatinin_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(amylase_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "amylase_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```
```{r}
data_with_cleaned_name <- janitor::clean_names(lipase_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "lipase_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```
```{r}
data_with_cleaned_name <- janitor::clean_names(crp_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "crp_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```
```{r}
data_with_cleaned_name <- janitor::clean_names(harnstoff_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "harnstoff_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(harnsäure_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "harnsäure_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```
```{r}
data_with_cleaned_name <- janitor::clean_names(erythrozyten_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "erythrozyten_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(thrombozyten_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "thrombozyten_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(monozyten_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "monozyten_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(eosinophile_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "eosinophile_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


```{r}
data_with_cleaned_name <- janitor::clean_names(neutrophile_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "neutrophile_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```



```{r}
data_with_cleaned_name <- janitor::clean_names(basophile_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "basophile_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(albumin_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "albumin_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


```{r}
data_with_cleaned_name <- janitor::clean_names(hämatokrit_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "hämatokrit_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(mcv_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "mcv_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


```{r}
data_with_cleaned_name <- janitor::clean_names(mch_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "mch_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


```{r}
data_with_cleaned_name <- janitor::clean_names(mchc_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "mchc_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


```{r}
data_with_cleaned_name <- janitor::clean_names(natrium_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "natrium_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(kalium_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "kalium_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(kalzium_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "kalzium_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


```{r}
data_with_cleaned_name <- janitor::clean_names(ferritin_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "ferritin_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(fieber_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "fieber_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```



```{r}
data_with_cleaned_name <- janitor::clean_names(glucose_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "glucose_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
data_with_cleaned_name <- janitor::clean_names(gfr_long)

control_2_data <- data_with_cleaned_name %>%
  filter(str_detect(attribute, "_From start|_From Start")) %>% 
  filter(treatment == "Leber_Diclo") %>% 
  drop_na(labreads)

## change in factor ##
control_2_data$edited_bf_ar_m_nummer2 <- as.factor(control_2_data$edited_bf_ar_m_nummer2)

control_2_data %>%
  # Count occurrences for each attribute
  group_by(edited_bf_ar_m_nummer2) %>%
  mutate(attribute_count = n()) %>%
  ungroup() %>%
  # Arrange attributes by their counts
  mutate(edited_bf_ar_m_nummer2 = fct_reorder(edited_bf_ar_m_nummer2, attribute_count)) %>%
  ggplot(aes(x = edited_bf_ar_m_nummer2, y = labreads)) +
  geom_point() +
  labs(title = "liver_diclo Control visit group amount of labreads",
       x = "BfArM-Number",
       y = "gfr_Labreads") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```







