---
title: "linear regression"
author: "Arun Kumar"
date: "`r Sys.Date()`"
output: html_document
---

!!!!!not relevant -> this data is with the filtered values (only 3 or more values per timepoint) but its not supposed to be filtered!!!!


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(performance)
library(ggplot2)
library(dlookr)
library(ggstatsplot)

```


```{r}
filtered_data %>%
  filter(attribute == "CK Day_Unknown" | attribute == "CK Day 185_From Start") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "ALT")


```

```{r}
quickfiltered_data_with_min_counts %>%
  filter(attribute == "Quick Day_Unknown" ) %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "quick")


```


```{r}
pttfiltered_data_with_min_counts %>%
  filter(attribute == "PTT Day_Unknown") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "ptt")


```


```{r}
leukozytenfiltered_data_with_min_counts %>%
  filter(attribute == "Leukozyten Day_Unknown"| attribute == "Leukozyten Day2_From Start") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "Leukocytes")


```

```{r}
astfiltered_data_with_min_counts %>%
  filter(Attribute == "GOT Day_Unknown"| Attribute == "GOT Day7_From Start") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= Attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "GOT")


```

```{r}
filtered_data_with_min_counts %>%
  filter(Attribute == "GPT Day_Unknown"| Attribute == "GPT Day7_From Start") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= Attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "GPT")


```


```{r}
ggtfiltered_data_with_min_counts %>%
  filter(attribute == "GGT Day_Unknown"| attribute == "GGT Day7_From Start"| attribute =="GGT Day1_From Start") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "GGT")


```

```{r}
ldhfiltered_data_with_min_counts %>%
  filter(attribute == "LDH Day_Unknown") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "ldh")


```

```{r}
hbfiltered_data_with_min_counts %>%
  filter(attribute == "Hb Day_Unknown"| attribute == "Hb Day2_From Start") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "hb")


```

```{r}
apfiltered_data_with_min_counts %>%
  filter(attribute == "AP Day_Unknown") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "ap")


```

```{r}
totbilifiltered_data_with_min_counts %>%
  filter(attribute == "TotalBilirubin Day_Unknown") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "totbili")


```

```{r}
kreafiltered_data_with_min_counts %>%
  filter(attribute == "Kreatinin Day_Unknown") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "Creatinine")


```

```{r}
crpfiltered_data_with_min_counts %>%
  filter(attribute == "CRP Day_Unknown") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "crp")


```

```{r}
hstfiltered_data_with_min_counts %>%
  filter(attribute == "Harnstoff Day_Unknown") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "hst")


```

```{r}
eryfiltered_data_with_min_counts %>%
  filter(attribute == "Erythrozyten Day_Unknown") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "ery")


```

```{r}
thrombfiltered_data_with_min_counts %>%
  filter(attribute == "Thrombozyten Day_Unknown") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "thromb")


```

```{r}
hktfiltered_data_with_min_counts %>%
  filter(attribute == "Hämatokrit Day_Unknown"| attribute == "Hämatokrit Day2_From Start") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "hkt")


```

```{r}
natfiltered_data_with_min_counts %>%
  filter(attribute == "Natrium Day_Unknown") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "nat")


```

```{r}
kalfiltered_data_with_min_counts %>%
  filter(attribute == "Kalium Day_Unknown") %>%
  drop_na(labreads) %>%
  ggplot(aes(x= attribute, y= labreads))+
  geom_point()+
labs(title = "Labvalues for control group (timepoints before start of reaction)",
       x = "timepoint",
       y = "kal")


```



