---
title: "Untitled"
author: "Arun Kumar"
date: "`r Sys.Date()`"
output: html_document
---

## patient which have >= 3 attribute or labvalues ##
```{r}
#gptaltdata <- read_excel("Data/SJS Arun 27.05.24.xlsx", sheet = 2,skip = 2) 
#gptaltdata$`GPT Day11` <- as.numeric(gptaltdata$`GPT Day11`)

# gptaltdata is raw data from excle
# Step 1: Pivot the data to long format, preserving the identifier

# gptaltdata_long <- gptaltdata %>%
#   tidyr::pivot_longer(cols = -c("Edited_BfArM Nummer2", "Treatment"), 
#                names_to = "Attribute", 
#                values_to = "labreads")
gptaltdata_long <- janitor::clean_names(gpt_long)
gptaltdata_long

patient_data_with_min_3attribute <- gptaltdata_long %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "GPT Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(got_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "GOT Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(ap_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "ap Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```


```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(total_bilirubin_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "total_bilirubin Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(quick_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "quick Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```
```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(lymphozyten_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "lymphozyten Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(eosinophile_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "eosinophile Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(lymphozyten_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "lymphozyten Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(eosinophile_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "eosinophile Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(ck_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "ck Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```
```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(inr_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "inr Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(ptt_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "ptt Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(leukozyten_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "leukozyten Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(ldh_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "ldh Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(hb_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "hb Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(direct_bilirubin_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "direct_bilirubin Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(kreatinin_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "kreatinin Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(lipase_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "lipase Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(crp_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "crp Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```
```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(harnstoff_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "hst Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```
```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(erythrozyten_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "erythrozyten Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```
```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(thrombozyten_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "thrombozyten Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```
```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(monozyten_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "monozyten Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```
```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(eosinophile_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "eosinophile Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```
```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(hämatokrit_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "hkt Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```
```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(natrium_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "sodium Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```
```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(kalium_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "potassium Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```

```{r}
data_with_clean_names_for_time_course_group <- janitor::clean_names(kalzium_long)


patient_data_with_min_3attribute <- data_with_clean_names_for_time_course_group %>% 
  filter(treatment == "Leber_Ibu") %>%
  filter(!str_detect(attribute, "_From Start|_From start|Day_Unknown")) %>% 
  drop_na(labreads) %>% 
  group_by(edited_bf_ar_m_nummer2) %>% 
  mutate(attribute_count = n()) %>% 
  filter(attribute_count >= 3)
  
patient_data_with_min_3attribute 

# Extract Day information and count number of patients per Day
 patient_Number_same_day <- patient_data_with_min_3attribute %>%
  mutate(Day = str_extract(attribute, "\\d+")) %>% 
   group_by(Day) %>% 
    summarise(num_patients = n_distinct(edited_bf_ar_m_nummer2)) %>%
  ungroup()
  
## convert days into numeric ##
patient_Number_same_day$Day <- as.numeric(patient_Number_same_day$Day)

patient_Number_same_day

##plot data##
patient_Number_same_day %>% 
  ggplot( aes(x = Day, y = num_patients)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    breaks = c(seq(0, 50, by = 5), seq(50, 200, by = 20)))+
  labs(title = "liver_ibu number of labvalues from different patients with time-course per day",
       x = "calcium Day",
       y = "Number of Patients/Labvalues") +
  theme_minimal()
```












