---
title: "NSAID Indikation"
output: html_document
date: "2025-05-12"
---

```{r}
library(readxl)
library(tidyr)
library(dplyr)
library(ggstatsplot)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
```





```{r}
library(readxl)
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/NSAID indications")
nsaid_indications <- read_excel("NSAID indications.xlsx", sheet = 1)

nsaid_indications
```



```{r}
nsaid_indications_count <- nsaid_indications %>% 
  group_by(diagnose_code) %>%
  summarize(n = n(), .groups = "drop")

nsaid_indications_count
```

```{r}
library(readxl)
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/NSAID indications")
diagnose_codes <- read_excel("NSAID indications.xlsx", sheet = 2)

diagnose_codes
```




```{r}
nsaid_indications_count$diagnose_code <- as.character(nsaid_indications_count$diagnose_code)
diagnose_codes$diagnose_code <- as.character(diagnose_codes$diagnose_code)

nsaid_count <- left_join(nsaid_indications_count, diagnose_codes, c = "diagnose_code") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "GPT Day_Unknown") %>% 
# filter(!str_detect(attribute, "_From Start"))%>% 
# filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(diagnose_code) 
nsaid_count
```



```{r}
library(readxl)
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/NSAID indications")
nsaid_headlines <- read_excel("NSAID indications.xlsx", sheet = 3)


nsaid_headlines_long <- nsaid_headlines %>%
  pivot_longer(cols = everything(), names_to = "kategorie", values_to = "diagnose_code") %>%
  filter(!is.na(diagnose_code))

nsaid_headlines_long <- nsaid_headlines_long %>%
  mutate(diagnose_code = as.character(diagnose_code)) 

nsaid_count_headlines <- nsaid_count %>%
  left_join(nsaid_headlines_long, by = "diagnose_code")

nsaid_count_headlines
```



```{r,fig.width=8, fig.height= 6}
pie_chart_nsaid_indications <- nsaid_count_headlines %>% 
  group_by(kategorie) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  mutate(prop = count / sum(count),
         label = paste0(kategorie, " (", round(prop * 100, 1), "%)")) %>% 
  ggplot(aes(x = "", y = count, fill = kategorie)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  labs(title = "Pie Chart of nsaid-indication") +
  theme_void() +  # Clean theme for pie chart
  theme(
    plot.title = element_text(margin = margin(b=10), 
                              color="black", face="bold", hjust = 1.5),
    legend.title = element_blank()) +
  geom_text(aes(label = label), 
            position = position_stack(vjust = 0.5), size = 3)

dir.create("plot", showWarnings = FALSE)
svg("plot/pie chart of nsaid indications.svg", height = 8, width = 6.5)
print(pie_chart_nsaid_indications)
dev.off()
```


