---
title: "Untitled"
output: html_document
date: "2026-04-15"
---


```{r} 
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(ggstatsplot)
library(dplyr)
library(ggplot2)
library(performance)
library(car)
```

### gpt ##########################################################

```{r}
gpt_full_peak <- gpt_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```


```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_gpt_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = gpt_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver gpt_peak_comparison of gpt between NSAID groups", 
       xlab = "NSAID group",
       ylab = "gpt (U/L)", )

liver_gpt_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver gpt_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_gpt_peak_comparison_of_nsaid_groups)
dev.off()
```



### got ##########################################################

```{r}
got_full_peak <- got_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_got_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = got_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver got_peak_comparison of got between NSAID groups", 
       xlab = "NSAID group",
       ylab = "got (U/L)", )

liver_got_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver got_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_got_peak_comparison_of_nsaid_groups)
dev.off()
```



### ggt ##########################################################

```{r}
ggt_full_peak <- ggt_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```


```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_ggt_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = ggt_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver ggt_peak_comparison of ggt between NSAID groups", 
       xlab = "NSAID group",
       ylab = "ggt (U/L)", )

liver_ggt_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver ggt_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_ggt_peak_comparison_of_nsaid_groups)
dev.off()
```


### ldh ##########################################################

```{r}
ldh_full_peak <- ldh_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```


```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_ldh_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = ldh_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver ldh_peak_comparison of ldh between NSAID groups", 
       xlab = "NSAID group",
       ylab = "ldh (U/L)", )

liver_ldh_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver ldh_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_ldh_peak_comparison_of_nsaid_groups)
dev.off()
```


### ck ##########################################################

```{r}
ck_full_peak <- ck_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```


```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_ck_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = ck_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver ck_peak_comparison of ck between NSAID groups", 
       xlab = "NSAID group",
       ylab = "ck (U/L)", )

liver_ck_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver ck_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_ck_peak_comparison_of_nsaid_groups)
dev.off()
```


### ap ##########################################################

```{r}
ap_full_peak <- ap_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```


```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_ap_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = ap_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver ap_peak_comparison of ap between NSAID groups", 
       xlab = "NSAID group",
       ylab = "ap (U/L)", )

liver_ap_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver ap_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_ap_peak_comparison_of_nsaid_groups)
dev.off()
```


### quick ##########################################################

```{r}
quick_full_peak <- quick_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```


```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_quick_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = quick_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver quick_peak_comparison of quick between NSAID groups", 
       xlab = "NSAID group",
       ylab = "quick (%)", )

liver_quick_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver quick_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_quick_peak_comparison_of_nsaid_groups)
dev.off()
```


### hämatokrit ##########################################################

```{r}
hämatokrit_full_peak <- hämatokrit_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```


```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_hämatokrit_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = hämatokrit_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver hämatokrit_peak_comparison of hämatokrit between NSAID groups", 
       xlab = "NSAID group",
       ylab = "hämatokrit (%)", )

liver_hämatokrit_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver hämatokrit_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_hämatokrit_peak_comparison_of_nsaid_groups)
dev.off()
```


### ptt ##########################################################

```{r}
ptt_full_peak <- ptt_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_ptt_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = ptt_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver ptt_peak_comparison of ptt between NSAID groups", 
       xlab = "NSAID group",
       ylab = "ptt (Sec.)", )

liver_ptt_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver ptt_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_ptt_peak_comparison_of_nsaid_groups)
dev.off()
```


### leukozyten ##########################################################

```{r}
leukozyten_full_peak <- leukozyten_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_leukozyten_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = leukozyten_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver leukozyten_peak_comparison of leukozyten between NSAID groups", 
       xlab = "NSAID group",
       ylab = "leukozyten (cells/ul)", )

liver_leukozyten_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver leukozyten_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_leukozyten_peak_comparison_of_nsaid_groups)
dev.off()
```


### thrombozyten ##########################################################

```{r}
thrombozyten_full_peak <- thrombozyten_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_thrombozyten_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = thrombozyten_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver thrombozyten_peak_comparison of thrombozyten between NSAID groups", 
       xlab = "NSAID group",
       ylab = "thrombozyten (cells/ul)", )

liver_thrombozyten_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver thrombozyten_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_thrombozyten_peak_comparison_of_nsaid_groups)
dev.off()
```


### erythrozyten ##########################################################

```{r}
erythrozyten_full_peak <- erythrozyten_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_erythrozyten_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = erythrozyten_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver erythrozyten_peak_comparison of erythrozyten between NSAID groups", 
       xlab = "NSAID group",
       ylab = "erythrozyten (cells/ul)", )

liver_erythrozyten_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver erythrozyten_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_erythrozyten_peak_comparison_of_nsaid_groups)
dev.off()
```


### hb ##########################################################

```{r}
hb_full_peak <- hb_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_hb_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = hb_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver hb_peak_comparison of hb between NSAID groups", 
       xlab = "NSAID group",
       ylab = "hb (g/dl)", )

liver_hb_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver hb_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_hb_peak_comparison_of_nsaid_groups)
dev.off()
```


### gesamteiweiß ##########################################################

```{r}
gesamteiweiß_full_peak <- gesamteiweiß_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_gesamteiweiß_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = gesamteiweiß_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver gesamteiweiß_peak_comparison of gesamteiweiß between NSAID groups", 
       xlab = "NSAID group",
       ylab = "gesamteiweiß (g/dl)", )

liver_gesamteiweiß_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver gesamteiweiß_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_gesamteiweiß_peak_comparison_of_nsaid_groups)
dev.off()
```


### total_bilirubin ##########################################################

```{r}
total_bilirubin_full_peak <- total_bilirubin_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_total_bilirubin_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = total_bilirubin_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver total_bilirubin_peak_comparison of total_bilirubin between NSAID groups", 
       xlab = "NSAID group",
       ylab = "total_bilirubin (mg/dl)", )

liver_total_bilirubin_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver total_bilirubin_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_total_bilirubin_peak_comparison_of_nsaid_groups)
dev.off()
```


### direct_bilirubin ##########################################################

```{r}
direct_bilirubin_full_peak <- direct_bilirubin_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_direct_bilirubin_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = direct_bilirubin_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver direct_bilirubin_peak_comparison of direct_bilirubin between NSAID groups", 
       xlab = "NSAID group",
       ylab = "direct_bilirubin (mg/dl)", )

liver_direct_bilirubin_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver direct_bilirubin_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_direct_bilirubin_peak_comparison_of_nsaid_groups)
dev.off()
```


### kreatinin ##########################################################

```{r}
kreatinin_full_peak <- kreatinin_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_kreatinin_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = kreatinin_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver kreatinin_peak_comparison of kreatinin between NSAID groups", 
       xlab = "NSAID group",
       ylab = "kreatinin (mg/dl)", )

liver_kreatinin_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver kreatinin_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_kreatinin_peak_comparison_of_nsaid_groups)
dev.off()
```


### harnstoff ##########################################################

```{r}
harnstoff_full_peak <- harnstoff_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_harnstoff_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = harnstoff_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver harnstoff_peak_comparison of harnstoff between NSAID groups", 
       xlab = "NSAID group",
       ylab = "harnstoff (mg/dl)", )

liver_harnstoff_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver harnstoff_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_harnstoff_peak_comparison_of_nsaid_groups)
dev.off()
```


### crp ##########################################################

```{r}
crp_full_peak <- crp_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_crp_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = crp_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver crp_peak_comparison of crp between NSAID groups", 
       xlab = "NSAID group",
       ylab = "crp (mg/dl)", )

liver_crp_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver crp_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_crp_peak_comparison_of_nsaid_groups)
dev.off()
```


### crp ##########################################################

```{r}
crp_full_peak <- crp_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_crp_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = crp_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver crp_peak_comparison of crp between NSAID groups", 
       xlab = "NSAID group",
       ylab = "crp (mg/l)", )

liver_crp_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver crp_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_crp_peak_comparison_of_nsaid_groups)
dev.off()
```


### natrium ##########################################################

```{r}
natrium_full_peak <- natrium_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_natrium_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = natrium_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver natrium_peak_comparison of natrium between NSAID groups", 
       xlab = "NSAID group",
       ylab = "natrium (mmol/l)", )

liver_natrium_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver natrium_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_natrium_peak_comparison_of_nsaid_groups)
dev.off()
```


### kalium ##########################################################

```{r}
kalium_full_peak <- kalium_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_kalium_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = kalium_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver kalium_peak_comparison of kalium between NSAID groups", 
       xlab = "NSAID group",
       ylab = "kalium (mmol/l)", )

liver_kalium_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver kalium_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_kalium_peak_comparison_of_nsaid_groups)
dev.off()
```


### kalzium ##########################################################

```{r}
kalzium_full_peak <- kalzium_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_kalzium_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = kalzium_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver kalzium_peak_comparison of kalzium between NSAID groups", 
       xlab = "NSAID group",
       ylab = "kalzium (mmol/l)", )

liver_kalzium_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver kalzium_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_kalzium_peak_comparison_of_nsaid_groups)
dev.off()
```


### inr ##########################################################

```{r}
inr_full_peak <- inr_full %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(grepl("Leber", Treatment)) %>% 
  group_by(Treatment) %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
```

```{r}
# Step 5: Create the base plot (can use all data or filtered data)
liver_inr_peak_comparison_of_nsaid_groups <- ggbetweenstats(
  data = inr_full_peak,
  x = Treatment,
  y = labreads,
  type = "np",
  title = "liver inr_peak_comparison of inr between NSAID groups", 
       xlab = "NSAID group",
       ylab = "inr ", )

liver_inr_peak_comparison_of_nsaid_groups

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/liver inr_peak_comparison of nsaid groups.svg", height = 6, width = 8)
print(liver_inr_peak_comparison_of_nsaid_groups)
dev.off()
```













### normality, variance, levene, welch summary ###
```{r}
while (sink.number() > 0) sink()

files <- list(
  gpt_full_peak = gpt_full_peak,
  got_full_peak = got_full_peak,
  ggt_full_peak = ggt_full_peak,
  ap_full_peak = ap_full_peak,
  total_bilirubin_full_peak = total_bilirubin_full_peak,
  direct_bilirubin_full_peak = direct_bilirubin_full_peak,
  ldh_full_peak = ldh_full_peak,
  ck_full_peak = ck_full_peak,
  quick_full_peak = quick_full_peak,
  inr_full_peak = inr_full_peak,
  ptt_full_peak = ptt_full_peak,
  leukozyten_full_peak = leukozyten_full_peak,
  erythrozyten_full_peak = erythrozyten_full_peak,
  thrombozyten_full_peak = thrombozyten_full_peak,
  hb_full_peak = hb_full_peak,
  hämatokrit_full_peak = hämatokrit_full_peak,
  gesamteiweiß_full_peak = gesamteiweiß_full_peak,
  crp_full_peak = crp_full_peak,
  kreatinin_full_peak = kreatinin_full_peak,
  harnstoff_full_peak = harnstoff_full_peak,
  natrium_full_peak = natrium_full_peak,
  kalium_full_peak = kalium_full_peak,
  kalzium_full_peak = kalzium_full_peak
)

sink("plots peak/peak_results normality, variance, levene, welch.txt")

for (name in names(files)) {
  
  data <- files[[name]]
  
  cat("\n============================\n")
  cat("Datensatz:", name, "\n")
  cat("============================\n\n")
  
  var <- "labreads"
  formula <- as.formula(paste(var, "~ Treatment"))
  
  cat("Normality Test (Shapiro-Wilk, abgesichert):\n")
  
  norm_res <- by(data[[var]], data$Treatment, function(x) {
    if (length(x) >= 3) {
      shapiro.test(x)
    } else {
      list(W = NA, p.value = NA)
    }
  })
  
  print(norm_res)
  
  cat("\nVarianz pro Gruppe:\n")
  print(tapply(data[[var]], data$Treatment, FUN = stats::var))
  
  cat("\nLevene-Test:\n")
  print(leveneTest(formula, data = data))
  
  cat("\nWelch ANOVA:\n")
  print(oneway.test(formula, data = data))
}

sink()
while (sink.number() > 0) sink()
```

### Kruskal-Wallis-Test summary ###
```{r}
while (sink.number() > 0) sink()
files <- list(
  gpt_full_peak = gpt_full_peak,
  got_full_peak = got_full_peak,
  ggt_full_peak = ggt_full_peak,
  ap_full_peak = ap_full_peak,
  total_bilirubin_full_peak = total_bilirubin_full_peak,
  direct_bilirubin_full_peak = direct_bilirubin_full_peak,
  ldh_full_peak = ldh_full_peak,
  ck_full_peak = ck_full_peak,
  quick_full_peak = quick_full_peak,
  inr_full_peak = inr_full_peak,
  ptt_full_peak = ptt_full_peak,
  leukozyten_full_peak = leukozyten_full_peak,
  erythrozyten_full_peak = erythrozyten_full_peak,
  thrombozyten_full_peak = thrombozyten_full_peak,
  hb_full_peak = hb_full_peak,
  hämatokrit_full_peak = hämatokrit_full_peak,
  gesamteiweiß_full_peak = gesamteiweiß_full_peak,
  crp_full_peak = crp_full_peak,
  kreatinin_full_peak = kreatinin_full_peak,
  harnstoff_full_peak = harnstoff_full_peak,
  natrium_full_peak = natrium_full_peak,
  kalium_full_peak = kalium_full_peak,
  kalzium_full_peak = kalzium_full_peak
)

results <- data.frame()

for (name in names(files)) {
  
  data <- files[[name]]
  
  var <- "labreads"
  formula <- as.formula(paste(var, "~ Treatment"))
  
  kw <- kruskal.test(formula, data = data)
  
  results <- rbind(
    results,
    data.frame(
      Dataset = name,
      Variable = var,
      Chi2 = unname(kw$statistic),
      df = unname(kw$parameter),
      p_value = kw$p.value
    )
  )
}

results
setwd("plots peak/")
write.table(results,
            file = "peak_kruskal_results.txt",
            sep = "\t",
            row.names = FALSE,
            quote = FALSE)
while (sink.number() > 0) sink()
```

