---
title: "Untitled"
author: "Arun Kumar"
date: "2025-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
```

```{r}
rawdata_sheet1 <- read_excel("co_medication_rawdata_full.xlsx", 
                           sheet = 3, col_names = FALSE)
rawdata_sheet1
```


```{r}
headers <- read_excel("co_medication_rawdata_full.xlsx", 
                           sheet = 1,
                      n_max = 3, col_names = FALSE)
headers
```

```{r}
combined_names_sheet1 <- paste(headers[1, ],headers[2, ],headers[3, ], sep = "_") %>%
  str_replace_all("_NA", "")
combined_names_sheet1 
```


```{r}
data_sheet1 <- read_excel("co_medication_rawdata_full.xlsx", 
                           sheet = 1,
                   skip= 3,
                   col_names = combined_names_sheet1)
data_sheet1
```

```{r}
data_comedication_clean_sheet1 <- data_sheet1 %>% 
  pivot_longer(
        cols = 3:3940,
        names_to    = c("Medication", "kathegorie", "drug_group"),
        names_pattern = "([^_]+)_([^_]+)_(.*)",
        values_to   = "labreads") %>% 
  dplyr::rename("bfarm_nummer" = "BfArM Nummer_BfArM Nummer_Edited_BfArM Nummer2",
                "treatment" = "Kathegorie_Kathegorie_Treatment") %>% 
  drop_na(labreads)
  

data_comedication_clean_sheet1 
```

################ sheet2################



```{r}
rawdata_sheet2 <- read_excel("co_medication_rawdata_full.xlsx", 
                           sheet = 4, skip = 1)
rawdata_sheet2
```


```{r}
# headers_sheet2 <- read_excel("comedication_rawdata/co-medication rawdata.xlsx",sheet = 2,
#                       n_max = 3, col_names = FALSE)
# headers_sheet2
```

```{r}
# combined_names_sheet2 <- paste(headers_sheet2[1, ],headers_sheet2[2, ],headers_sheet2[3, ], sep = "_") %>%
#   str_replace_all("_NA", "")
# combined_names_sheet2 
```


```{r}
# #data_sheet2 <- 
#   read_excel("comedication_rawdata/co-medication rawdata.xlsx",sheet = 2, 
#              skip = 3,
#              col_names = combined_names_sheet2)
# #data_sheet2
```


```{r}
data_comedication_clean_sheet2 <- rawdata_sheet2 %>% 
  pivot_longer(
        cols = 3:434,
        names_to    = c("Medication", "kathegorie", "drug_group"),
        names_pattern = "([^_]+)_([^_]+)_(.*)",
        values_to   = "labreads") %>% 
  dplyr::rename("bfarm_nummer" = "BfArM Nummer_BfArM Nummer_BfArM Nummer",
                "treatment" = "Kathegorie_Kathegorie_Kathegorie") %>% 
  drop_na(labreads)
  

data_comedication_clean_sheet2 
```

```{r}
rawdata_sheet3 <- read_excel("co_medication_rawdata_full.xlsx", 
                           sheet = 5)
rawdata_sheet3
```

```{r}
data_comedication_clean_sheet3 <- rawdata_sheet3 %>% 
  pivot_longer(
        cols = 3:338,
        names_to    = c("Medication", "kathegorie", "drug_group"),
        names_pattern = "([^_]+)_([^_]+)_(.*)",
        values_to   = "labreads") %>% 
  dplyr::rename("bfarm_nummer" = "BfArM Nummer_BfArM Nummer_BfArM Nummer",
                "treatment" = "Kathegorie_Kathegorie_Kathegorie") %>% 
  drop_na(labreads)
  

data_comedication_clean_sheet3
```


```{r}
comedication_full_data <- bind_rows(data_comedication_clean_sheet1,data_comedication_clean_sheet2,data_comedication_clean_sheet3)
comedication_full_data
```


```{r}
write.csv(comedication_full_data,"comedication_full_data.csv", row.names = FALSE)
```

##################################################################################



```{r}
#test_table <- read.csv("comedication_full_data.csv")
#test_table
```


































