---
title: "Untitled"
output: html_document
date: "2026-03-11"
---

```{r} 
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(ggstatsplot)
library(dplyr)
library(ggplot2)
library(performance)
library(car)
library(flextable)
library(GGally)
```

```{r}
comedicationdata_livertox <- read.csv(
  "E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/co-medication/comedication_with_livertoxicity literature only.csv",
  sep = ",",
  stringsAsFactors = FALSE
)
comedicationdata_livertox2 <- comedicationdata_livertox %>% 
  dplyr::rename( "patient_group" = "treatment",
                 "parameter_co" = "labreads",
                 "kathegorie_co" = "kathegorie",
                 "drug_group_co" = "drug_group",
                 "medication_co" = "Medication")

comedicationdata_heptox <- comedicationdata_livertox2 %>% 
  filter(hep_tox == "tox") %>% 
  filter(evidence_level == "high")  %>% 
  select(1:7) 
comedicationdata_heptox
```

```{r}
# Einlesen und Spaltennamen säubern
main_medication_data <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/comp dose_labvalues/Dose table_assumed_full.xlsx", sheet = 2) %>%
  janitor::clean_names() %>%
  rename(
    bfarm_nummer   = edited_bf_ar_m_nummer2,
    parameter_M    = parameter,
    Treatment.x     = attribut,
    medication_M   = treatment,
    kathegorie_M   = kathegorie,
    drug_group_M   = drug_group
  ) %>%
  filter(kathegorie_M != "Cummulative Dosis")

# Daten anzeigen
main_medication_data

```

```{r}
main_data_comed_heptox <- left_join(main_medication_data,comedicationdata_heptox, by = "bfarm_nummer")
main_data_comed_heptox
```



### gpt_all_groups_comedication_count_intake_at_same_timespan #######################################################

```{r}
gpt_full2 <- gpt_full %>% 
  dplyr::rename("bfarm_nummer" = "Edited_BfArM Nummer2",
                "patient_group" = "Treatment",
                "attribute" = "attribute") %>% 
  mutate(bfarm_nummer = as.character(bfarm_nummer))%>%
  filter(!str_detect(attribute, "_From Start|_From start|DBS"))
gpt_full2 

```

```{r}
mainmed_comed_gpt <- left_join(main_data_comed_heptox,gpt_full2 ,by = "bfarm_nummer") %>% 
  drop_na() %>% 
  dplyr::select(-drug_group_co,-patient_group.x,-patient_group.y)
mainmed_comed_gpt
```


```{r}
mainmed_comed_gpt_filter_before <- mainmed_comed_gpt %>% 
  dplyr::filter(grepl("Zeitraum: erste Einnahme bis Krankheitsbeginn",kathegorie_M)) %>% 
  dplyr::filter(grepl("Zeitraum: letzte Einnahme bis Krankheitsbeginn",kathegorie_co)) %>% 
  mutate(parameter_M1 = parameter_M +91) %>%
  dplyr::filter(parameter_M1 > parameter_co)

mainmed_comed_gpt_filter_before#%>% 
#  dplyr::filter(Medication == "Atenolol, Clortalidon (Hypertonus)")
  
```


```{r}
mainmed_comed_gpt_filter_after <- mainmed_comed_gpt %>% 
  dplyr::filter(grepl("Zeitraum: letzte Einnahme bis Krankheitsbeginn",kathegorie_M)) %>% 
  dplyr::filter(grepl("Zeitraum: erste Einnahme bis Krankheitsbeginn",kathegorie_co)) %>% 
  mutate(parameter_M1 = parameter_M -91) %>% 
  filter(!(parameter_M1 < 0)) %>% 
  dplyr::filter(parameter_M1 < parameter_co)

mainmed_comed_gpt_filter_after#%>% 
#  dplyr::filter(Medication == "Atenolol, Clortalidon (Hypertonus)")
  
```

```{r}
main_medication_count_sit <- read_excel("main_medication_count.xlsx", sheet = 2)
main_medication_count_sit
```



```{r}
# Beispielcode für deine Tabelle
# df <- your_dataframe_name

mainmed_comed_gpt_all_counts <- mainmed_comed_gpt_filter_before %>%
  # Schritt 1: Beide Spalten in eine lange Form bringen
  pivot_longer(cols = c(medication_co), 
               names_to = "source", values_to = "medication_co") %>%
  # Schritt 2: Duplikate entfernen (jede Medikamenten-Patient-Kombination nur einmal)
  distinct(bfarm_nummer, medication_co) %>%
  # Schritt 3: Pro Patient (bfarm_nummer) zählen, wie viele verschiedene Medikamente es gibt
  group_by(bfarm_nummer) %>%
  summarise(number_comedication = n(), .groups = "drop")

# Ausgabe ansehen
mainmed_comed_gpt_all_counts

```


### gpt ########################################################################

```{r}
plotdata_gpt_livertox <- left_join(mainmed_comed_gpt_all_counts, mainmed_comed_gpt, by = "bfarm_nummer") %>% 
  mutate(number_comedication = as.numeric(as.character(number_comedication))) %>% 
  distinct(bfarm_nummer, attribute, labreads, .keep_all = TRUE) %>% 
  dplyr::select(1,2,6,12,13)

plotdata_gpt_livertox
```



### peak ##############################################################################

```{r}
ld_gpt_dose_result1_peak <- ld_gpt_dose_result1 %>% 
  drop_na() %>% 
 # filter(Diabetes == "Diabetic") %>% 
  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()

ld_gpt_dose_result1_peak
```



```{r}
#setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Ergebnis Vergleich dosis_labvalues/plots_cumulative dose counts")
all_labvalues_gpt_correlation_labvalue_with_numbercomed <- plotdata_gpt_livertox %>% 
  select(number_comedication,labreads) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "all labvalues_gpt_correlation labvalue and number of livertoxic comedication")

all_labvalues_gpt_correlation_labvalue_with_numbercomed
#dir.create("plots/gpt", showWarnings = FALSE)
#svg("plots/gpt/all_labvalues_gpt_correlation_labvalue_with_numbercomed.svg", height = 6, width = 8)
#print(all_labvalues_gpt_correlation_labvalue_with_numbercomed)
#dev.off()
```

```{r}
# Overall Spearman correlation
cor.test(
  plotdata_gpt_livertox$labreads,
  plotdata_gpt_livertox$number_comedication,
  method = "spearman"
)

# Spearman correlation by Gender
plotdata_gpt_livertox %>%
  summarise(
    Spearman = cor(labreads, number_comedication, method = "spearman"),
    p_value  = cor.test(labreads, number_comedication, method = "spearman")$p.value
  )
```



#### Linear regression ###
```{r}
# Fit model
model <- lm(labreads ~ number_comedication, data = plotdata_gpt_livertox)
summary(model)
```


```{r}
dose_counts <- plotdata_gpt_livertox %>%
  group_by(number_comedication) %>%
  summarise(
    N = n_distinct(bfarm_nummer),
    y_pos = max(labreads, na.rm = TRUE) * 1.05)

dose_labels <- paste0(
  dose_counts$number_comedication, " \n",
  "N=", dose_counts$N)
names(dose_labels) <- dose_counts$number_comedication

# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(labreads ~ poly(number_comedication, 2, raw = TRUE), data = plotdata_gpt_livertox)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- plotdata_gpt_livertox %>% 
  ggplot(aes(x = number_comedication, y = labreads)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  scale_x_continuous(
    breaks = dose_counts$number_comedication,
    labels = dose_labels) +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  labs(
    title = paste0("ld_gpt_Polynomial regression of lavalue and number of livertoxic comedication"),
    x = "Number of livertoxic comedication",
    y = "gpt (U/L)"
  )

print(p_reg)

# Speichern
#ggsave(
#  filename = paste0("plots/gpt/ld_poly regression labvalue_daily dose on_", my_attribute, "_", my_gender, ".svg"),
#  plot = p_reg,
#  width = 8, height = 6
#)
```


# peak - number livertoxic comedication

```{r}
plotdata_gpt_livertox_peak <- plotdata_gpt_livertox  %>%
  group_by(number_comedication) %>%  group_by(bfarm_nummer) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup()

all_labvalues_gpt_correlation_labvalue_with_numbercomed_peak <- plotdata_gpt_livertox_peak %>% 
  select(number_comedication,labreads) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "all labvalues_gpt_peak_correlation labvalue and number of livertoxic comedication")

all_labvalues_gpt_correlation_labvalue_with_numbercomed_peak
#dir.create("plots/gpt", showWarnings = FALSE)
#svg("plots/gpt/all_labvalues_gpt_correlation_labvalue_with_numbercomed_peak.svg", height = 6, width = 8)
#print(all_labvalues_gpt_correlation_labvalue_with_numbercomed_peak)
#dev.off()
```


```{r}
plotdata_gpt_livertox
```


```{r}
dose_counts <- plotdata_gpt_livertox_peak %>%
  group_by(number_comedication) %>%
  summarise(
    N = n_distinct(bfarm_nummer),
    y_pos = max(labreads, na.rm = TRUE) * 1.05)

dose_labels <- paste0(
  dose_counts$number_comedication, " \n",
  "N=", dose_counts$N)
names(dose_labels) <- dose_counts$number_comedication

# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(labreads ~ poly(number_comedication, 2, raw = TRUE), data = plotdata_gpt_livertox_peak)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- plotdata_gpt_livertox_peak %>% 
  ggplot(aes(x = number_comedication, y = labreads)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  scale_x_continuous(
    breaks = dose_counts$number_comedication,
    labels = dose_labels) +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  labs(
    title = paste0("ld_gpt_peak_Polynomial regression of lavalue and number of livertoxic comedication"),
    x = "Number of livertoxic comedication",
    y = "gpt (U/L)"
  )

print(p_reg)

# Speichern
#ggsave(
#  filename = paste0("plots/gpt/ld_poly regression labvalue_daily dose on_", my_attribute, "_", my_gender, ".svg"),
#  plot = p_reg,
#  width = 8, height = 6
#)
```




###dose data##
```{r}
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/comp dose_labvalues")

dose_data <- read_excel("Dose table_assumed_full.xlsx", sheet = 2)  
```

```{r}
gpt_dosedata <- left_join(gpt_full,dose_data, by = ("Edited_BfArM Nummer2")) %>% 
  dplyr::select(!8)
gpt_dosedata
```

```{r}
dd_amount <- gpt_dosedata %>%
  filter(Kathegorie == "Häufigkeit der Einnahme pro Tag")%>%
  rename("numberofdose" = "Parameter") %>%  
  dplyr::select(1,6,8)
dd_amount
```

```{r}
ld_gpt_dose_result <- left_join(gpt_dosedata,dd_amount, by = ("Edited_BfArM Nummer2")) %>%
  filter(Treatment.x == "Leber_Diclo") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(Kathegorie.x == "Dosis (Mg/Verabreichung)" & Treatment.y == "Diclofenac") %>%
  mutate(dailydose = Parameter*numberofdose) %>%
  mutate(dailydose = as.numeric(as.character(dailydose))) %>%
  group_by(dailydose) %>%
  distinct()
  #drop_na(numberofdose)

ld_gpt_dose_result1 <- ld_gpt_dose_result[
  ld_gpt_dose_result$`Edited_BfArM Nummer2` != "93008468" & 
  ld_gpt_dose_result$`Edited_BfArM Nummer2` != "4000702", 
]

ld_gpt_dose_result1 <- mutate(ld_gpt_dose_result1, dailydose = ifelse(dailydose == 200, 150, dailydose))
ld_gpt_dose_result1 <- mutate(ld_gpt_dose_result1, dailydose = ifelse(dailydose == 25, 50, dailydose))
ld_gpt_dose_result1 <- mutate(ld_gpt_dose_result1, dailydose = ifelse(dailydose == 10, 50, dailydose))
ld_gpt_dose_result1 <- mutate(ld_gpt_dose_result1, dailydose = ifelse(dailydose == 175, 150, dailydose))
ld_gpt_dose_result1 <- mutate(ld_gpt_dose_result1, dailydose = ifelse(dailydose == 187.5, 200, dailydose))



print(ld_gpt_dose_result1)


```

# diclo monotreat ####

```{r}
dose_data_diclo <- dose_data %>% 
  filter(Treatment == "Diclofenac") %>% 
  filter(Attribut == "Leber_Diclo") %>% 
  filter(Kathegorie != "Cummulative Dosis")

dose_data_diclo 
```

```{r}
diclo_monotreat_unfinished <- anti_join(dose_data_diclo,comedicationdata2, by = c("Edited_BfArM Nummer2" = "bfarm_nummer"))
diclo_monotreat_unfinished
```

```{r}
diclo_monotreat <- diclo_monotreat_unfinished %>%
  anti_join(patientid_mainmed_multi, by = "Edited_BfArM Nummer2")
diclo_monotreat
```

```{r}
diclo_mono_gpt_dd <- left_join(diclo_monotreat,ld_gpt_dose_result1, by = "Edited_BfArM Nummer2") %>% 
  distinct(`Edited_BfArM Nummer2`, dailydose, attribute, labreads, .keep_all = TRUE) %>% 
  dplyr::select(1,2,7,8,9,16) %>% 
  drop_na(dailydose) 

diclo_mono_gpt_dd
```

```{r}
liver_diclo_gpt_correlation_diclomono <- diclo_mono_gpt_dd %>% 
  select(dailydose,labreads) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "ld_gpt_diclomono: correlation labvalue and dailydose")

liver_diclo_gpt_correlation_diclomono
#dir.create("plots/gpt", showWarnings = FALSE)
#svg("plots/gpt/liver_diclo_gpt_correlation_diclomono.svg", height = 6, width = 8)
#print(liver_diclo_gpt_correlation_diclomono)
#dev.off()
```

```{r}
diclo_mono_gpt_dd_peak <- diclo_mono_gpt_dd %>% 
  group_by(dailydose) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%      slice(1) %>% ungroup()

liver_diclo_gpt_correlation_diclomono_peak <- diclo_mono_gpt_dd_peak %>% 
  select(dailydose,labreads) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "ld_gpt_peak_diclomono: correlation labvalue and dailydose")

liver_diclo_gpt_correlation_diclomono_peak
#dir.create("plots/gpt", showWarnings = FALSE)
#svg("liver_diclo_gpt_correlation_diclomono_peak.svg", height = 6, width = 8)
#print(liver_diclo_gpt_correlation_diclomono_peak)
#dev.off()
```


```{r}
dose_counts <- diclo_mono_gpt_dd %>%
  group_by(dailydose) %>%
  summarise(
    N = n_distinct(`Edited_BfArM Nummer2`),
    y_pos = max(labreads, na.rm = TRUE) * 1.05)

dose_labels <- paste0(
  dose_counts$dailydose, " mg\n",
  "N=", dose_counts$N)
names(dose_labels) <- dose_counts$dailydose

# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(labreads ~ poly(dailydose, 2, raw = TRUE), data = diclo_mono_gpt_dd)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- diclo_mono_gpt_dd %>% 
  ggplot(aes(x = dailydose, y = labreads)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  scale_x_continuous(
    breaks = dose_counts$dailydose,
    labels = dose_labels) +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  labs(
    title = paste0("ld_gpt_diclomono: Polynomial regression of lavalue and dailydose"),
    x = "Daily Dose (mg)",
    y = "gpt (U/L)"
  )

print(p_reg)

# Speichern
#ggsave(
#  filename = paste0("plots/gpt/ld_poly regression labvalue_daily dose on_", my_attribute, "_", my_gender, ".svg"),
#  plot = p_reg,
#  width = 8, height = 6
#)
```


```{r}
dose_counts <- diclo_mono_gpt_dd_peak %>%
  group_by(dailydose) %>%
  summarise(
    N = n_distinct(`Edited_BfArM Nummer2`),
    y_pos = max(labreads, na.rm = TRUE) * 1.05)

dose_labels <- paste0(
  dose_counts$dailydose, " mg\n",
  "N=", dose_counts$N)
names(dose_labels) <- dose_counts$dailydose

# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(labreads ~ poly(dailydose, 2, raw = TRUE), data = diclo_mono_gpt_dd_peak)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- diclo_mono_gpt_dd_peak %>% 
  ggplot(aes(x = dailydose, y = labreads)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  scale_x_continuous(
    breaks = dose_counts$dailydose,
    labels = dose_labels) +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  labs(
    title = paste0("ld_gpt_peak_diclomono: Polynomial regression of lavalue and dailydose"),
    x = "Daily Dose (mg)",
    y = "gpt (U/L)"
  )

print(p_reg)

# Speichern
#ggsave(
#  filename = paste0("plots/gpt/ld_poly regression labvalue_daily dose on_", my_attribute, "_", my_gender, ".svg"),
#  plot = p_reg,
#  width = 8, height = 6
#)
```


# diclo + 1 hepatotoxin ###

```{r}
plotdata_gpt_livertox_reduced <- plotdata_gpt_livertox %>%
  dplyr::select(1,2) %>% 
  distinct(bfarm_nummer,number_comedication)
  
diclo_plotdata_gpt_livertox <- left_join(plotdata_gpt_livertox_reduced,ld_gpt_dose_result1, by = c("bfarm_nummer" = "Edited_BfArM Nummer2")) %>% 
  distinct(bfarm_nummer, dailydose, attribute, labreads, .keep_all = TRUE) %>%
  drop_na(dailydose) %>% 
  filter(Treatment.x == "Leber_Diclo") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute))

diclo_1tox <- diclo_plotdata_gpt_livertox %>% 
  filter(number_comedication == "1")
diclo_1tox
```



```{r}
liver_diclo_gpt_correlation_diclo_1hepatotoxin <-diclo_1tox %>% 
  select(dailydose,labreads) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "ld_gpt_diclo + 1 heaptotoxin: correlation labvalue and dailydose")

liver_diclo_gpt_correlation_diclo_1hepatotoxin
#dir.create("plots/gpt", showWarnings = FALSE)
#svg("plots/gpt/liver_diclo_gpt_correlation_diclo_1hepatotoxin.svg", height = 6, width = 8)
#print(liver_diclo_gpt_correlation_diclo_1hepatotoxin)
#dev.off()
```


```{r}
dose_counts <- diclo_1tox %>%
  group_by(dailydose) %>%
  summarise(
    N = n_distinct(bfarm_nummer),
    y_pos = max(labreads, na.rm = TRUE) * 1.05)

dose_labels <- paste0(
  dose_counts$dailydose, " mg\n",
  "N=", dose_counts$N)
names(dose_labels) <- dose_counts$dailydose

# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(labreads ~ poly(dailydose, 2, raw = TRUE), data = diclo_1tox)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- diclo_1tox %>% 
  ggplot(aes(x = dailydose, y = labreads)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  scale_x_continuous(
    breaks = dose_counts$dailydose,
    labels = dose_labels) +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  labs(
    title = paste0("ld_gpt_diclo + 1 hepatotoxin: Polynomial regression of lavalue and dailydose"),
    x = "Daily Dose (mg)",
    y = "gpt (U/L)"
  )

print(p_reg)

# Speichern
#ggsave(
#  filename = paste0("plots/gpt/ld_poly regression labvalue_daily dose on_", my_attribute, "_", my_gender, ".svg"),
#  plot = p_reg,
#  width = 8, height = 6
#)
```


# diclo + 2 hepatotoxin ###

```{r}
diclo_2tox <- diclo_plotdata_gpt_livertox %>% 
  filter(number_comedication == "2")
diclo_2tox
```

```{r}
#setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Ergebnis Vergleich dosis_labvalues/plots_cumulative dose counts")
liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin <-diclo_2tox %>% 
  select(dailydose,labreads) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "ld_gpt_diclo + 2 hepatotoxins: correlation labvalue and dailydose")

liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin
#dir.create("plots/gpt", showWarnings = FALSE)
#svg("plots/gpt/liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin.svg", height = 6, width = 8)
#print(liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin)
#dev.off()
```

```{r}
dose_counts <- diclo_2tox %>%
  group_by(dailydose) %>%
  summarise(
    N = n_distinct(bfarm_nummer),
    y_pos = max(labreads, na.rm = TRUE) * 1.05)

dose_labels <- paste0(
  dose_counts$dailydose, " mg\n",
  "N=", dose_counts$N)
names(dose_labels) <- dose_counts$dailydose

# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(labreads ~ poly(dailydose, 2, raw = TRUE), data = diclo_2tox)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- diclo_2tox %>% 
  ggplot(aes(x = dailydose, y = labreads)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  scale_x_continuous(
    breaks = dose_counts$dailydose,
    labels = dose_labels) +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  labs(
    title = paste0("ld_gpt_diclo + 2 hepatotoxins: Polynomial regression of lavalue and dailydose"),
    x = "Daily Dose (mg)",
    y = "gpt (U/L)"
  )

print(p_reg)

# Speichern
#ggsave(
#  filename = paste0("plots/gpt/ld_poly regression labvalue_daily dose on_", my_attribute, "_", my_gender, ".svg"),
#  plot = p_reg,
#  width = 8, height = 6
#)
```


# diclo + 3 hepatotoxin ###

```{r}
diclo_3tox <- diclo_plotdata_gpt_livertox %>% 
  filter(number_comedication == "3")
diclo_3tox
```

```{r}
#setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Ergebnis Vergleich dosis_labvalues/plots_cumulative dose counts")
liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin <-diclo_3tox %>% 
  select(dailydose,labreads) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "ld_gpt_diclo + 3 hepatotoxins: correlation labvalue and dailydose")

liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin
#dir.create("plots/gpt", showWarnings = FALSE)
#svg("plots/gpt/liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin.svg", height = 6, width = 8)
#print(liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin)
#dev.off()
```

```{r}
dose_counts <- diclo_3tox %>%
  group_by(dailydose) %>%
  summarise(
    N = n_distinct(bfarm_nummer),
    y_pos = max(labreads, na.rm = TRUE) * 1.05)

dose_labels <- paste0(
  dose_counts$dailydose, " mg\n",
  "N=", dose_counts$N)
names(dose_labels) <- dose_counts$dailydose

# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(labreads ~ poly(dailydose, 2, raw = TRUE), data = diclo_3tox)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- diclo_3tox %>% 
  ggplot(aes(x = dailydose, y = labreads)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  scale_x_continuous(
    breaks = dose_counts$dailydose,
    labels = dose_labels) +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  labs(
    title = paste0("ld_gpt_diclo + 3 hepatotoxins: Polynomial regression of lavalue and dailydose"),
    x = "Daily Dose (mg)",
    y = "gpt (U/L)"
  )

print(p_reg)

# Speichern
#ggsave(
#  filename = paste0("plots/gpt/ld_poly regression labvalue_daily dose on_", my_attribute, "_", my_gender, ".svg"),
#  plot = p_reg,
#  width = 8, height = 6
#)
```


# peak_diclo + 1 hepatotoxin ###

```{r}
plotdata_gpt_livertox_reduced <- plotdata_gpt_livertox %>%
  dplyr::select(1,2) %>% 
  distinct(bfarm_nummer,number_comedication)
  
diclo_plotdata_gpt_livertox_peak <- left_join(plotdata_gpt_livertox_reduced,ld_gpt_dose_result1, by = c("bfarm_nummer" = "Edited_BfArM Nummer2")) %>% 
  distinct(bfarm_nummer, dailydose, attribute, labreads, .keep_all = TRUE) %>%
  drop_na(dailydose) %>% 
  filter(Treatment.x == "Leber_Diclo") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>%
  group_by(dailydose) %>%  group_by(bfarm_nummer) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup()

diclo_1tox_peak <- diclo_plotdata_gpt_livertox_peak %>% 
  filter(number_comedication == "1")
diclo_1tox_peak
```



```{r}
liver_diclo_gpt_correlation_diclo_1hepatotoxin <-diclo_1tox_peak %>% 
  select(dailydose,labreads) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "ld_gpt_peak_diclo + 1 heaptotoxin: correlation labvalue and dailydose")

liver_diclo_gpt_correlation_diclo_1hepatotoxin
#dir.create("plots/gpt", showWarnings = FALSE)
#svg("plots/gpt/liver_diclo_gpt_correlation_diclo_1hepatotoxin.svg", height = 6, width = 8)
#print(liver_diclo_gpt_correlation_diclo_1hepatotoxin)
#dev.off()
```


```{r}
dose_counts <- diclo_1tox_peak %>%
  group_by(dailydose) %>%
  summarise(
    N = n_distinct(bfarm_nummer),
    y_pos = max(labreads, na.rm = TRUE) * 1.05)

dose_labels <- paste0(
  dose_counts$dailydose, " mg\n",
  "N=", dose_counts$N)
names(dose_labels) <- dose_counts$dailydose

# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(labreads ~ poly(dailydose, 2, raw = TRUE), data = diclo_1tox_peak)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- diclo_1tox_peak %>% 
  ggplot(aes(x = dailydose, y = labreads)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  scale_x_continuous(
    breaks = dose_counts$dailydose,
    labels = dose_labels) +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  labs(
    title = paste0("ld_gpt_peak_diclo + 1 hepatotoxin: Polynomial regression of lavalue and dailydose"),
    x = "Daily Dose (mg)",
    y = "gpt (U/L)"
  )

print(p_reg)

# Speichern
#ggsave(
#  filename = paste0("plots/gpt/ld_poly regression labvalue_daily dose on_", my_attribute, "_", my_gender, ".svg"),
#  plot = p_reg,
#  width = 8, height = 6
#)
```


# diclo + 2 hepatotoxin ###

```{r}
diclo_2tox_peak <- diclo_plotdata_gpt_livertox %>% 
  filter(number_comedication == "2")
diclo_2tox_peak
```

```{r}
#setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Ergebnis Vergleich dosis_labvalues/plots_cumulative dose counts")
liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin <-diclo_2tox_peak %>% 
  select(dailydose,labreads) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "ld_gpt_peak_diclo + 2 hepatotoxins: correlation labvalue and dailydose")

liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin
#dir.create("plots/gpt", showWarnings = FALSE)
#svg("plots/gpt/liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin.svg", height = 6, width = 8)
#print(liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin)
#dev.off()
```

```{r}
dose_counts <- diclo_2tox_peak %>%
  group_by(dailydose) %>%
  summarise(
    N = n_distinct(bfarm_nummer),
    y_pos = max(labreads, na.rm = TRUE) * 1.05)

dose_labels <- paste0(
  dose_counts$dailydose, " mg\n",
  "N=", dose_counts$N)
names(dose_labels) <- dose_counts$dailydose

# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(labreads ~ poly(dailydose, 2, raw = TRUE), data = diclo_2tox_peak)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- diclo_2tox_peak %>% 
  ggplot(aes(x = dailydose, y = labreads)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  scale_x_continuous(
    breaks = dose_counts$dailydose,
    labels = dose_labels) +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  labs(
    title = paste0("ld_gpt_peak_diclo + 2 hepatotoxins: Polynomial regression of lavalue and dailydose"),
    x = "Daily Dose (mg)",
    y = "gpt (U/L)"
  )

print(p_reg)

# Speichern
#ggsave(
#  filename = paste0("plots/gpt/ld_poly regression labvalue_daily dose on_", my_attribute, "_", my_gender, ".svg"),
#  plot = p_reg,
#  width = 8, height = 6
#)
```


# diclo + 3 hepatotoxin ###

```{r}
diclo_3tox_peak <- diclo_plotdata_gpt_livertox %>% 
  filter(number_comedication == "3")
diclo_3tox_peak
```

```{r}
#setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Ergebnis Vergleich dosis_labvalues/plots_cumulative dose counts")
liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin <-diclo_3tox_peak %>% 
  select(dailydose,labreads) %>% 
  ggpairs(columns = 1:2,
          lower = list(continuous = "smooth"),
          upper = list(continuous = wrap("cor", method = "spearman")))+
  labs(title = "ld_gpt_peak_diclo + 3 hepatotoxins: correlation labvalue and dailydose")

liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin
#dir.create("plots/gpt", showWarnings = FALSE)
#svg("plots/gpt/liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin.svg", height = 6, width = 8)
#print(liver_diclo_gpt_correlation_labvalue_with_diclo_1hepatotoxin)
#dev.off()
```

```{r}
dose_counts <- diclo_3tox_peak %>%
  group_by(dailydose) %>%
  summarise(
    N = n_distinct(bfarm_nummer),
    y_pos = max(labreads, na.rm = TRUE) * 1.05)

dose_labels <- paste0(
  dose_counts$dailydose, " mg\n",
  "N=", dose_counts$N)
names(dose_labels) <- dose_counts$dailydose

# Polynomiale Regression 2. Ordnung (quadratisch)
lm_model_poly_dd <- lm(labreads ~ poly(dailydose, 2, raw = TRUE), data = diclo_3tox_peak)

# Koeffizienten extrahieren
coefs <- coef(lm_model_poly_dd)
summary_model <- summary(lm_model_poly_dd)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  
pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)

# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)} 
  else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   
    "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  
    "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation
p_reg <- diclo_3tox_peak %>% 
  ggplot(aes(x = dailydose, y = labreads)) +
  geom_point(color = "blue", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "red", linetype = "dashed") +
  annotate("text", x = Inf, y = Inf, 
           label = info_text, 
           hjust = 1.1, vjust = 1.2, size = 5, color = "black") +
  scale_x_continuous(
    breaks = dose_counts$dailydose,
    labels = dose_labels) +
  theme_minimal(base_size = 14) +
  coord_cartesian(clip = "off") +
  labs(
    title = paste0("ld_gpt_peak_diclo + 3 hepatotoxins: Polynomial regression of lavalue and dailydose"),
    x = "Daily Dose (mg)",
    y = "gpt (U/L)"
  )

print(p_reg)

# Speichern
#ggsave(
#  filename = paste0("plots/gpt/ld_poly regression labvalue_daily dose on_", my_attribute, "_", my_gender, ".svg"),
#  plot = p_reg,
#  width = 8, height = 6
#)
```










































