---
title: "Untitled"
output: html_document
date: "2025-10-01"
---

```{r}
library(GGally)
library(dplyr)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(ggstatsplot)
library(ggplot2)
library(performance)
library(car)
```


### "plotdata" from "labvalues drug count.Rmd"


```{r}


plotdata_gpt1 <- plotdata_gpt %>%
  mutate(number_comedication = as.numeric(number_comedication)) %>%  # Spalte umwandeln
  select(1:2) %>%   # nur Spalten 1 und 2 behalten
  distinct(`bfarm_nummer`, .keep_all = TRUE) 
plotdata_gpt1
```



```{r}

setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/comp dose_labvalues")

dose_data <- read_excel("Dose table_assumed_full.xlsx", sheet = 2)  

#lvdiclo_dosedata <- dose_data %>% 
#  filter(Attribut == "Leber_Diclo") %>% 
#  rename( "Edited_BfArM Nummer2" ="BfArM Nummer_2" )

#lvdiclo_dosedata
dose_data
```


```{r}
gpt_dosedata <- left_join(gpt_full,dose_data, by = ("Edited_BfArM Nummer2")) %>% 
  dplyr::select(!8)
gpt_dosedata
```

```{r}
dd_amount <- gpt_dosedata %>%
  filter(Kathegorie == "Häufigkeit der Einnahme pro Tag")%>%
  rename("numberofdose" = "Parameter") %>%  
  dplyr::select(1,6,8)

dd_amount
```



```{r}
ld_gpt_dose_result <- left_join(gpt_dosedata,dd_amount, by = ("Edited_BfArM Nummer2")) %>%
  filter(Treatment.x == "Leber_Diclo") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  filter(Kathegorie.x == "Dosis (Mg/Verabreichung)" & Treatment.y == "Diclofenac") %>%
  mutate(dailydose = Parameter*numberofdose) %>%
  mutate(dailydose = as.numeric(as.character(dailydose))) %>%
  group_by(dailydose) %>%
  distinct()
  #drop_na(numberofdose)

ld_gpt_dose_result1 <- ld_gpt_dose_result[
  ld_gpt_dose_result$`Edited_BfArM Nummer2` != "93008468" & 
  ld_gpt_dose_result$`Edited_BfArM Nummer2` != "4000702", 
]

ld_gpt_dose_result1 <- mutate(ld_gpt_dose_result1, dailydose = ifelse(dailydose == 200, 150, dailydose))
ld_gpt_dose_result1 <- mutate(ld_gpt_dose_result1, dailydose = ifelse(dailydose == 25, 50, dailydose))
ld_gpt_dose_result1 <- mutate(ld_gpt_dose_result1, dailydose = ifelse(dailydose == 10, 50, dailydose))
ld_gpt_dose_result1 <- mutate(ld_gpt_dose_result1, dailydose = ifelse(dailydose == 175, 150, dailydose))
ld_gpt_dose_result1 <- mutate(ld_gpt_dose_result1, dailydose = ifelse(dailydose == 187.5, 200, dailydose))



print(ld_gpt_dose_result1)
```


### intake at same simespan ###########################################################

# daily dose ##########################################################################
```{r}
choosedose <- 50

# filter
gpt_dose_result_filtered <- ld_gpt_dose_result1 %>%
  filter(dailydose == choosedose) %>%
  group_by(`Edited_BfArM Nummer2`) %>%
  slice_max(order_by = labreads, n = 1, with_ties = FALSE) %>%
  ungroup()

# join
dd50_comed <- left_join(gpt_dose_result_filtered,  plotdata_gpt1,  by = c("Edited_BfArM Nummer2" = "bfarm_nummer")) %>%
  drop_na(number_comedication)

# make ggpairs plot
p1 <- dd50_comed %>% 
  select(labreads, number_comedication) %>% 
  drop_na() %>% 
  ggpairs(
    columns = 2:1,
    lower = list(continuous = "smooth"),
    upper = list(continuous = wrap("cor", method = "spearman"))
  )+
  labs(title = paste0("liver diclo_correlation of medicationnumber and peak-gpt\n for ", choosedose, " daily dose.svg"))
    
print (p1)
# save as SVG
dir.create("plots_corr and reg/diclofenac", showWarnings = FALSE)
ggsave(
  filename = paste0("plots_corr and reg/diclofenac/ld_ists_corr of mednumber and peak-gpt for ", choosedose, "mg daily dose.svg"),
  plot = p1,
  width = 7, height = 6
  )
```

```{r}
# Polynomiale Regression 2. Ordnung (quadratisch)
model <- lm(labreads ~ poly(number_comedication, 2, raw = TRUE), data = dd50_comed)

# Koeffizienten extrahieren
summary_model <- summary(model)
coefs <- coef(model)
r_squared <- summary_model$r.squared
p_values <- summary_model$coefficients[, "Pr(>|t|)"]

# P-Wert berechnen
fstat <- summary_model$fstatistic  

pvalue_raw <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)
# Dynamische Formatierung des P-Werts
format_pvalue <- function(p) {
  if (p < 0.001) {format(p, scientific = TRUE, digits = 2)
  } else {format(round(p, 4), nsmall = 4)}}
pvalue <- format_pvalue(pvalue_raw)

# Info-Text für die Grafik
info_text <- paste0(   "y = ", round(coefs[1], 2), " + ", round(coefs[2], 2), "x + ", round(coefs[3], 7),  "\n", "R² = ", round(r_squared, 2), "\n",  "p = ", pvalue )

# Plot mit Annotation und log-log-Achsen
p_reg <- dd50_comed %>% 
  ggplot(aes(x = number_comedication, y = labreads)) +
  geom_point(color = "steelblue", size = 2) +
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2, raw = TRUE),
              se = TRUE, 
              color = "black", 
              linetype = "dashed") +
  scale_y_log10(
  breaks = c(10, 50, 100, 500, 1000, 5000, 10000),
  labels = scales::label_number(big.mark = ".", decimal.mark = ",")
  ) +
  labs(
    title = paste0("Polynomial regression of medicationnumber and peak-gpt\n for ", choosedose, "mg daily dose"),
    x = "Number of medicaments",
    y = "GPT (U/L) (log-scale)")+
  coord_cartesian(clip = "off") +
  annotate("text",  x = max(dd50_comed$number_comedication, na.rm = TRUE),  # rechte Seite
    y = max(dd50_comed$labreads, na.rm = TRUE) * 0.9,     # etwas unterhalb der oberen Kante
    label = info_text,
    hjust = 1, vjust = 1, size = 5, color = "black") +
  theme_classic() +
  theme(theme(axis.text.x = element_text(size = 14)),
  plot.margin = margin(t = 30, r = 30, b = 20, l = 20))

print(p_reg)

# Speichern
ggsave(
  filename = paste0("plots_corr and reg/diclofenac/ld_ists_poly regression of mednumber and peak-gpt for ", choosedose, "mg daily dose.svg"),
  plot = p_reg,
  width = 8, height = 6
)
```










