---
title: "hospitalisation labvalues at time of dismiss"
output: html_document
date: "2024-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(readxl)
library(tidyr)
library(dplyr)
library(ggstatsplot)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
```



```{r}
library(readxl)
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/flupirtin cases")

flupirtin_basicdata <- read_excel("flupirtin dosedata.xlsx", sheet = 3)
flupirtin_basicdata
```



```{r}
gpt_flupirtin <- left_join(gpt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") 
  
gpt_flupirtin
```

###gpt###


```{r}
gpt_flupirtinbasic_peak <- left_join(gpt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "GPT Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
gpt_flupirtinbasic_peak
```


```{r}
library(dlookr)
gpt_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```

```{r}
t.test(
   labreads ~ flupirtin,
  data = gpt_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- gpt_flupirtinbasic_peak %>%
  distinct(bf_ar_m_nummer, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = gpt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_gpt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-GPT U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_gpt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(gpt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

#dir.create("plots peak", showWarnings = FALSE)
#svg("plots peak/all groups_gpt_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_gpt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
#dev.off()

#all_groups_gpt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake
```



```{r}

f1_diclo <- gpt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- gpt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(gpt_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-GPT U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- gpt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- gpt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(gpt_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-GPT U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- gpt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- gpt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(gpt_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-GPT U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_gpt_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```



### got ####################################################################################


```{r}
got_flupirtinbasic_peak <- left_join(got_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "got Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
got_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = got_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- got_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = got_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_got for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-got U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_got_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(got_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_got_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_got_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- got_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- got_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(got_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-got U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- got_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- got_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(got_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-got U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- got_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- got_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(got_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-got U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_got_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### ggt ####################################################################################


```{r}
ggt_flupirtinbasic_peak <- left_join(ggt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "ggt Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
ggt_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = ggt_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ggt_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ggt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_ggt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ggt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_ggt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ggt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_ggt_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_ggt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- ggt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- ggt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(ggt_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ggt U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- ggt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- ggt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(ggt_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ggt U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- ggt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- ggt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(ggt_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ggt U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_ggt_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```



### ldh ####################################################################################


```{r}
ldh_flupirtinbasic_peak <- left_join(ldh_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "ldh Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
ldh_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = ldh_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ldh_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ldh_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_ldh for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ldh U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_ldh_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ldh_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_ldh_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_ldh_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- ldh_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- ldh_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(ldh_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ldh U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- ldh_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- ldh_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(ldh_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ldh U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- ldh_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- ldh_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(ldh_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ldh U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_ldh_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### ck ####################################################################################


```{r}
ck_flupirtinbasic_peak <- left_join(ck_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "ck Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
ck_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = ck_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ck_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ck_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_ck for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ck U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_ck_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ck_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_ck_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_ck_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- ck_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- ck_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(ck_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ck U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- ck_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- ck_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(ck_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ck U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- ck_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- ck_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(ck_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ck U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_ck_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### ptt ####################################################################################


```{r}
ptt_flupirtinbasic_peak <- left_join(ptt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "ptt Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
ptt_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = ptt_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ptt_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ptt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_ptt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ptt sec.",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_ptt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ptt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_ptt_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_ptt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- ptt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- ptt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(ptt_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ptt sec.",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- ptt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- ptt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(ptt_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ptt sec.",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- ptt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- ptt_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(ptt_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ptt sec.",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_ptt_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### leukozyten ####################################################################################


```{r}
leukozyten_flupirtinbasic_peak <- left_join(leukozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "leukozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
leukozyten_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = leukozyten_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- leukozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = leukozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_leukozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-leukozyten cells/ul",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_leukozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(leukozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_leukozyten_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_leukozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- leukozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- leukozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(leukozyten_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-leukozyten cells/ul",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- leukozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- leukozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(leukozyten_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-leukozyten cells/ul",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- leukozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- leukozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(leukozyten_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-leukozyten cells/ul",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_leukozyten_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### thrombozyten ####################################################################################


```{r}
thrombozyten_flupirtinbasic_peak <- left_join(thrombozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "thrombozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
thrombozyten_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = thrombozyten_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- thrombozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = thrombozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_thrombozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-thrombozyten cells/ul",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_thrombozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(thrombozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_thrombozyten_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_thrombozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- thrombozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- thrombozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(thrombozyten_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-thrombozyten cells/ul",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- thrombozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- thrombozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(thrombozyten_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-thrombozyten cells/ul",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- thrombozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- thrombozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(thrombozyten_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-thrombozyten cells/ul",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_thrombozyten_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### erythrozyten ####################################################################################


```{r}
erythrozyten_flupirtinbasic_peak <- left_join(erythrozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "erythrozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
erythrozyten_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = erythrozyten_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- erythrozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = erythrozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_erythrozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-erythrozyten cells/ul",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_erythrozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(erythrozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_erythrozyten_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_erythrozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- erythrozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- erythrozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(erythrozyten_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-erythrozyten cells/ul",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- erythrozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- erythrozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(erythrozyten_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-erythrozyten cells/ul",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- erythrozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- erythrozyten_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(erythrozyten_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-erythrozyten cells/ul",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_erythrozyten_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### hb ####################################################################################


```{r}
hb_flupirtinbasic_peak <- left_join(hb_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "hb Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
hb_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = hb_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- hb_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = hb_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_hb for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-hb g/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_hb_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(hb_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_hb_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_hb_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- hb_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- hb_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(hb_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-hb g/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- hb_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- hb_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(hb_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-hb g/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- hb_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- hb_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(hb_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-hb g/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_hb_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### gesamteiweiß ####################################################################################


```{r}
gesamteiweiß_flupirtinbasic_peak <- left_join(gesamteiweiß_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "gesamteiweiß Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
gesamteiweiß_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = gesamteiweiß_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- gesamteiweiß_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = gesamteiweiß_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_gesamteiweiß for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-gesamteiweiß g/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_gesamteiweiß_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(gesamteiweiß_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_gesamteiweiß_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_gesamteiweiß_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- gesamteiweiß_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- gesamteiweiß_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(gesamteiweiß_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-gesamteiweiß g/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- gesamteiweiß_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- gesamteiweiß_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(gesamteiweiß_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-gesamteiweiß g/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- gesamteiweiß_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- gesamteiweiß_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(gesamteiweiß_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-gesamteiweiß g/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_gesamteiweiß_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### ap ####################################################################################


```{r}
ap_flupirtinbasic_peak <- left_join(ap_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "ap Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
ap_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = ap_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ap_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ap_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_ap for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ap U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_ap_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ap_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_ap_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_ap_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- ap_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- ap_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(ap_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ap U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- ap_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- ap_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(ap_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ap U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- ap_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- ap_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(ap_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-ap U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_ap_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```

### total_bilirubin ####################################################################################


```{r}
total_bilirubin_flupirtinbasic_peak <- left_join(total_bilirubin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "total_bilirubin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
total_bilirubin_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = total_bilirubin_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- total_bilirubin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = total_bilirubin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_total_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-total_bilirubin mg/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_total_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(total_bilirubin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_total_bilirubin_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_total_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- total_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- total_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(total_bilirubin_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-total_bilirubin mg/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- total_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- total_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(total_bilirubin_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-total_bilirubin mg/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- total_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- total_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(total_bilirubin_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-total_bilirubin mg/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_total_bilirubin_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### direct_bilirubin ####################################################################################


```{r}
direct_bilirubin_flupirtinbasic_peak <- left_join(direct_bilirubin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "direct_bilirubin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
direct_bilirubin_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = direct_bilirubin_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- direct_bilirubin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = direct_bilirubin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_direct_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-direct_bilirubin mg/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_direct_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(direct_bilirubin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_direct_bilirubin_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_direct_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- direct_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- direct_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(direct_bilirubin_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-direct_bilirubin mg/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- direct_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- direct_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(direct_bilirubin_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-direct_bilirubin mg/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- direct_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- direct_bilirubin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(direct_bilirubin_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-direct_bilirubin mg/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_direct_bilirubin_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### kreatinin ####################################################################################


```{r}
kreatinin_flupirtinbasic_peak <- left_join(kreatinin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "kreatinin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
kreatinin_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = kreatinin_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- kreatinin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = kreatinin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_kreatinin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kreatinin mg/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_kreatinin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(kreatinin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_kreatinin_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_kreatinin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- kreatinin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- kreatinin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(kreatinin_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-kreatinin mg/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- kreatinin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- kreatinin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(kreatinin_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-kreatinin mg/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- kreatinin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- kreatinin_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(kreatinin_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-kreatinin mg/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_kreatinin_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### harnstoff ####################################################################################


```{r}
harnstoff_flupirtinbasic_peak <- left_join(harnstoff_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "harnstoff Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
harnstoff_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = harnstoff_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- harnstoff_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = harnstoff_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_harnstoff for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-harnstoff mg/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_harnstoff_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(harnstoff_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_harnstoff_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_harnstoff_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- harnstoff_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- harnstoff_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(harnstoff_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-harnstoff mg/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- harnstoff_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- harnstoff_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(harnstoff_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-harnstoff mg/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- harnstoff_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- harnstoff_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(harnstoff_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-harnstoff mg/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_harnstoff_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### crp ####################################################################################


```{r}
crp_flupirtinbasic_peak <- left_join(crp_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "crp Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
crp_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = crp_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- crp_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = crp_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_crp for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-crp mg/l",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_crp_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(crp_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_crp_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_crp_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- crp_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- crp_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(crp_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-crp mg/l",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- crp_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- crp_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(crp_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-crp mg/l",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- crp_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- crp_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(crp_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-crp mg/l",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_crp_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### natrium ####################################################################################


```{r}
natrium_flupirtinbasic_peak <- left_join(natrium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "natrium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
natrium_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = natrium_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- natrium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = natrium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_natrium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-natrium mmol/l",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_natrium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(natrium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_natrium_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_natrium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- natrium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- natrium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(natrium_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-natrium mmol/l",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- natrium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- natrium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(natrium_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-natrium mmol/l",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- natrium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- natrium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(natrium_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-natrium mmol/l",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_natrium_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### kalium ####################################################################################


```{r}
kalium_flupirtinbasic_peak <- left_join(kalium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "kalium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
kalium_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = kalium_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- kalium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = kalium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_kalium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kalium mmol/l",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_kalium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(kalium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_kalium_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_kalium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- kalium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- kalium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(kalium_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-kalium mmol/l",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- kalium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- kalium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(kalium_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-kalium mmol/l",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- kalium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- kalium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(kalium_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-kalium mmol/l",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_kalium_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### kalzium ####################################################################################


```{r}
kalzium_flupirtinbasic_peak <- left_join(kalzium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "kalzium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
kalzium_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = kalzium_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- kalzium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = kalzium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_kalzium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kalzium mmol/l",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_kalzium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(kalzium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_kalzium_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_kalzium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- kalzium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- kalzium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(kalzium_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-kalzium mmol/l",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- kalzium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- kalzium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(kalzium_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-kalzium mmol/l",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- kalzium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- kalzium_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(kalzium_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-kalzium mmol/l",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_kalzium_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### quick ####################################################################################


```{r}
quick_flupirtinbasic_peak <- left_join(quick_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "quick Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
quick_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = quick_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- quick_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = quick_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_quick for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-quick %",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_quick_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(quick_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_quick_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_quick_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- quick_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- quick_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(quick_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-quick %",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- quick_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- quick_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(quick_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-quick %",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- quick_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- quick_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(quick_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-quick %",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_quick_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```



### hämatokrit ####################################################################################


```{r}
hämatokrit_flupirtinbasic_peak <- left_join(hämatokrit_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "hämatokrit Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
hämatokrit_flupirtinbasic_peak %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = hämatokrit_flupirtinbasic_peak
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- hämatokrit_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = hämatokrit_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion peak_hämatokrit for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-hämatokrit %",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_hämatokrit_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(hämatokrit_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/all groups_hämatokrit_peak_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_hämatokrit_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- hämatokrit_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- hämatokrit_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(hämatokrit_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-hämatokrit %",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- hämatokrit_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- hämatokrit_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(hämatokrit_flupirtinbasic_peak$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-hämatokrit %",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- hämatokrit_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- hämatokrit_flupirtinbasic_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(hämatokrit_flupirtinbasic_peak$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "peak-hämatokrit %",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots peak", showWarnings = FALSE)
svg("plots peak/leber_hämatokrit_peak_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```