---
title: "Untitled"
output: html_document
date: "2026-02-27"
---

```{r}
library(readxl)
library(tidyr)
library(dplyr)
library(ggstatsplot)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
```

```{r}
library(readxl)
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/flupirtin cases")

flupirtin_basicdata <- read_excel("flupirtin dosedata.xlsx", sheet = 3)
flupirtin_basicdata
```

### gpt #########################################################################
```{r}
gpt_flupirtinbasic_peak <- left_join(gpt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "gpt Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_gpt_flupirtinbasic_peak <- gpt_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_gpt_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_gpt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_gpt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-gpt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_gpt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_gpt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_gpt_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_gpt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_gpt_flupirtinbasic_peak <- gpt_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_gpt_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_gpt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-gpt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-gpt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_gpt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_gpt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_gpt_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_gpt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_gpt_flupirtinbasic_peak <- gpt_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_gpt_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_gpt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-gpt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-gpt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_gpt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_gpt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_gpt_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_gpt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### got #########################################################################
```{r}
got_flupirtinbasic_peak <- left_join(got_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "got Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_got_flupirtinbasic_peak <- got_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_got_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_got_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_got for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-got U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_got_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_got_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_got_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_got_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_got_flupirtinbasic_peak <- got_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_got_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_got_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-got for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-got U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_got_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_got_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_got_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_got_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_got_flupirtinbasic_peak <- got_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_got_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_got_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-got for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-got U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_got_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_got_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_got_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_got_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



### ggt #########################################################################
```{r}
ggt_flupirtinbasic_peak <- left_join(ggt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "ggt Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_ggt_flupirtinbasic_peak <- ggt_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_ggt_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_ggt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_ggt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ggt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_ggt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_ggt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_ggt_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_ggt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_ggt_flupirtinbasic_peak <- ggt_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_ggt_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_ggt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-ggt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ggt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_ggt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_ggt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_ggt_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_ggt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_ggt_flupirtinbasic_peak <- ggt_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_ggt_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_ggt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-ggt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ggt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_ggt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_ggt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_ggt_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_ggt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### ldh #########################################################################
```{r}
ldh_flupirtinbasic_peak <- left_join(ldh_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "ldh Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_ldh_flupirtinbasic_peak <- ldh_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_ldh_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_ldh_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_ldh for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ldh U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_ldh_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_ldh_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_ldh_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_ldh_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_ldh_flupirtinbasic_peak <- ldh_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_ldh_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_ldh_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-ldh for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ldh U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_ldh_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_ldh_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_ldh_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_ldh_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_ldh_flupirtinbasic_peak <- ldh_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_ldh_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_ldh_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-ldh for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ldh U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_ldh_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_ldh_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_ldh_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_ldh_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### ck #########################################################################
```{r}
ck_flupirtinbasic_peak <- left_join(ck_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "ck Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_ck_flupirtinbasic_peak <- ck_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_ck_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_ck_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_ck for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ck U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_ck_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_ck_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_ck_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_ck_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_ck_flupirtinbasic_peak <- ck_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_ck_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_ck_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-ck for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ck U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_ck_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_ck_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_ck_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_ck_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_ck_flupirtinbasic_peak <- ck_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_ck_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_ck_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-ck for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ck U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_ck_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_ck_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_ck_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_ck_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### ap #########################################################################
```{r}
ap_flupirtinbasic_peak <- left_join(ap_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "ap Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_ap_flupirtinbasic_peak <- ap_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_ap_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_ap_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_ap for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ap U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_ap_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_ap_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_ap_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_ap_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_ap_flupirtinbasic_peak <- ap_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_ap_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_ap_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-ap for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ap U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_ap_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_ap_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_ap_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_ap_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_ap_flupirtinbasic_peak <- ap_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_ap_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_ap_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-ap for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ap U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_ap_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_ap_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_ap_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_ap_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### quick #########################################################################
```{r}
quick_flupirtinbasic_peak <- left_join(quick_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "quick Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_quick_flupirtinbasic_peak <- quick_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_quick_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_quick_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_quick for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-quick (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_quick_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_quick_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_quick_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_quick_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_quick_flupirtinbasic_peak <- quick_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_quick_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_quick_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-quick for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-quick (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_quick_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_quick_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_quick_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_quick_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_quick_flupirtinbasic_peak <- quick_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_quick_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_quick_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-quick for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-quick (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_quick_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_quick_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_quick_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_quick_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### hämatokrit #########################################################################
```{r}
hämatokrit_flupirtinbasic_peak <- left_join(hämatokrit_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "hämatokrit Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_hämatokrit_flupirtinbasic_peak <- hämatokrit_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_hämatokrit_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_hämatokrit_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_hämatokrit for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-hämatokrit (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_hämatokrit_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_hämatokrit_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_hämatokrit_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_hämatokrit_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_hämatokrit_flupirtinbasic_peak <- hämatokrit_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_hämatokrit_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_hämatokrit_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-hämatokrit for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-hämatokrit (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_hämatokrit_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_hämatokrit_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_hämatokrit_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_hämatokrit_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_hämatokrit_flupirtinbasic_peak <- hämatokrit_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_hämatokrit_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_hämatokrit_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-hämatokrit for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-hämatokrit (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_hämatokrit_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_hämatokrit_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_hämatokrit_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_hämatokrit_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### ptt #########################################################################
```{r}
ptt_flupirtinbasic_peak <- left_join(ptt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "ptt Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_ptt_flupirtinbasic_peak <- ptt_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_ptt_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_ptt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_ptt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ptt (Sec.)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_ptt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_ptt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_ptt_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_ptt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_ptt_flupirtinbasic_peak <- ptt_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_ptt_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_ptt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-ptt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ptt (Sec.)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_ptt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_ptt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_ptt_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_ptt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_ptt_flupirtinbasic_peak <- ptt_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_ptt_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_ptt_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-ptt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-ptt (Sec.)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_ptt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_ptt_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_ptt_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_ptt_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### leukozyten #########################################################################
```{r}
leukozyten_flupirtinbasic_peak <- left_join(leukozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "leukozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_leukozyten_flupirtinbasic_peak <- leukozyten_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_leukozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_leukozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_leukozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-leukozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_leukozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_leukozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_leukozyten_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_leukozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_leukozyten_flupirtinbasic_peak <- leukozyten_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_leukozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_leukozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-leukozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-leukozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_leukozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_leukozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_leukozyten_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_leukozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_leukozyten_flupirtinbasic_peak <- leukozyten_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_leukozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_leukozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-leukozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-leukozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_leukozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_leukozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_leukozyten_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_leukozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### erythrozyten #########################################################################
```{r}
erythrozyten_flupirtinbasic_peak <- left_join(erythrozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "erythrozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_erythrozyten_flupirtinbasic_peak <- erythrozyten_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_erythrozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_erythrozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_erythrozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-erythrozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_erythrozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_erythrozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_erythrozyten_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_erythrozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_erythrozyten_flupirtinbasic_peak <- erythrozyten_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_erythrozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_erythrozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-erythrozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-erythrozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_erythrozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_erythrozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_erythrozyten_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_erythrozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_erythrozyten_flupirtinbasic_peak <- erythrozyten_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_erythrozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_erythrozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-erythrozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-erythrozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_erythrozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_erythrozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_erythrozyten_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_erythrozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### thrombozyten #########################################################################
```{r}
thrombozyten_flupirtinbasic_peak <- left_join(thrombozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "thrombozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_thrombozyten_flupirtinbasic_peak <- thrombozyten_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_thrombozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_thrombozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_thrombozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-thrombozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_thrombozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_thrombozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_thrombozyten_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_thrombozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_thrombozyten_flupirtinbasic_peak <- thrombozyten_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_thrombozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_thrombozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-thrombozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-thrombozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_thrombozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_thrombozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_thrombozyten_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_thrombozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_thrombozyten_flupirtinbasic_peak <- thrombozyten_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_thrombozyten_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_thrombozyten_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-thrombozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-thrombozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_thrombozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_thrombozyten_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_thrombozyten_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_thrombozyten_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### hb #########################################################################
```{r}
hb_flupirtinbasic_peak <- left_join(hb_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "hb Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_hb_flupirtinbasic_peak <- hb_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_hb_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_hb_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_hb for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-hb (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_hb_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_hb_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_hb_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_hb_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_hb_flupirtinbasic_peak <- hb_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_hb_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_hb_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-hb for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-hb (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_hb_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_hb_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_hb_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_hb_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_hb_flupirtinbasic_peak <- hb_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_hb_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_hb_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-hb for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-hb (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_hb_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_hb_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_hb_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_hb_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### gesamteiweiß #########################################################################
```{r}
gesamteiweiß_flupirtinbasic_peak <- left_join(gesamteiweiß_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "gesamteiweiß Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_gesamteiweiß_flupirtinbasic_peak <- gesamteiweiß_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_gesamteiweiß_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_gesamteiweiß_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_gesamteiweiß for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-gesamteiweiß (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_gesamteiweiß_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_gesamteiweiß_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_gesamteiweiß_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_gesamteiweiß_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_gesamteiweiß_flupirtinbasic_peak <- gesamteiweiß_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_gesamteiweiß_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_gesamteiweiß_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-gesamteiweiß for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-gesamteiweiß (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_gesamteiweiß_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_gesamteiweiß_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_gesamteiweiß_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_gesamteiweiß_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_gesamteiweiß_flupirtinbasic_peak <- gesamteiweiß_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_gesamteiweiß_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_gesamteiweiß_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-gesamteiweiß for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-gesamteiweiß (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_gesamteiweiß_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_gesamteiweiß_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_gesamteiweiß_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_gesamteiweiß_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### total_bilirubin #########################################################################
```{r}
total_bilirubin_flupirtinbasic_peak <- left_join(total_bilirubin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "total_bilirubin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_total_bilirubin_flupirtinbasic_peak <- total_bilirubin_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_total_bilirubin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_total_bilirubin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_total_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-total_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_total_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_total_bilirubin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_total_bilirubin_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_total_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_total_bilirubin_flupirtinbasic_peak <- total_bilirubin_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_total_bilirubin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_total_bilirubin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-total_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-total_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_total_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_total_bilirubin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_total_bilirubin_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_total_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_total_bilirubin_flupirtinbasic_peak <- total_bilirubin_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_total_bilirubin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_total_bilirubin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-total_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-total_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_total_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_total_bilirubin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_total_bilirubin_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_total_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### direct_bilirubin #########################################################################
```{r}
direct_bilirubin_flupirtinbasic_peak <- left_join(direct_bilirubin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "direct_bilirubin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_direct_bilirubin_flupirtinbasic_peak <- direct_bilirubin_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_direct_bilirubin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_direct_bilirubin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_direct_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-direct_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_direct_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_direct_bilirubin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_direct_bilirubin_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_direct_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_direct_bilirubin_flupirtinbasic_peak <- direct_bilirubin_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_direct_bilirubin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_direct_bilirubin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-direct_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-direct_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_direct_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_direct_bilirubin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_direct_bilirubin_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_direct_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_direct_bilirubin_flupirtinbasic_peak <- direct_bilirubin_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_direct_bilirubin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_direct_bilirubin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-direct_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-direct_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_direct_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_direct_bilirubin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_direct_bilirubin_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_direct_bilirubin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### kreatinin #########################################################################
```{r}
kreatinin_flupirtinbasic_peak <- left_join(kreatinin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "kreatinin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_kreatinin_flupirtinbasic_peak <- kreatinin_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_kreatinin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_kreatinin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_kreatinin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kreatinin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_kreatinin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_kreatinin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_kreatinin_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_kreatinin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_kreatinin_flupirtinbasic_peak <- kreatinin_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_kreatinin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_kreatinin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-kreatinin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kreatinin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_kreatinin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_kreatinin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_kreatinin_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_kreatinin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_kreatinin_flupirtinbasic_peak <- kreatinin_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_kreatinin_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_kreatinin_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-kreatinin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kreatinin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_kreatinin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_kreatinin_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_kreatinin_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_kreatinin_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### harnstoff #########################################################################
```{r}
harnstoff_flupirtinbasic_peak <- left_join(harnstoff_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "harnstoff Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_harnstoff_flupirtinbasic_peak <- harnstoff_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_harnstoff_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_harnstoff_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_harnstoff for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-harnstoff (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_harnstoff_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_harnstoff_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_harnstoff_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_harnstoff_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_harnstoff_flupirtinbasic_peak <- harnstoff_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_harnstoff_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_harnstoff_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-harnstoff for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-harnstoff (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_harnstoff_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_harnstoff_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_harnstoff_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_harnstoff_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_harnstoff_flupirtinbasic_peak <- harnstoff_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_harnstoff_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_harnstoff_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-harnstoff for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-harnstoff (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_harnstoff_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_harnstoff_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_harnstoff_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_harnstoff_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### crp #########################################################################
```{r}
crp_flupirtinbasic_peak <- left_join(crp_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "crp Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_crp_flupirtinbasic_peak <- crp_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_crp_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_crp_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_crp for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-crp (mg/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_crp_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_crp_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_crp_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_crp_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_crp_flupirtinbasic_peak <- crp_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_crp_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_crp_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-crp for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-crp (mg/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_crp_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_crp_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_crp_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_crp_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_crp_flupirtinbasic_peak <- crp_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_crp_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_crp_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-crp for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-crp (mg/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_crp_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_crp_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_crp_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_crp_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### natrium #########################################################################
```{r}
natrium_flupirtinbasic_peak <- left_join(natrium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "natrium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_natrium_flupirtinbasic_peak <- natrium_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_natrium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_natrium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_natrium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-natrium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_natrium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_natrium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_natrium_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_natrium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_natrium_flupirtinbasic_peak <- natrium_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_natrium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_natrium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-natrium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-natrium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_natrium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_natrium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_natrium_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_natrium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_natrium_flupirtinbasic_peak <- natrium_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_natrium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_natrium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-natrium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-natrium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_natrium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_natrium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_natrium_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_natrium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### kalium #########################################################################
```{r}
kalium_flupirtinbasic_peak <- left_join(kalium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "kalium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_kalium_flupirtinbasic_peak <- kalium_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_kalium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_kalium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_kalium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kalium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_kalium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_kalium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_kalium_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_kalium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_kalium_flupirtinbasic_peak <- kalium_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_kalium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_kalium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-kalium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kalium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_kalium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_kalium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_kalium_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_kalium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_kalium_flupirtinbasic_peak <- kalium_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_kalium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_kalium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-kalium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kalium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_kalium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_kalium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_kalium_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_kalium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### kalzium #########################################################################
```{r}
kalzium_flupirtinbasic_peak <- left_join(kalzium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "kalzium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_kalzium_flupirtinbasic_peak <- kalzium_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_kalzium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_kalzium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_kalzium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kalzium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_kalzium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_kalzium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_kalzium_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_kalzium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_kalzium_flupirtinbasic_peak <- kalzium_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_kalzium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_kalzium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-kalzium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kalzium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_kalzium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_kalzium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_kalzium_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_kalzium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_kalzium_flupirtinbasic_peak <- kalzium_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_kalzium_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_kalzium_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-kalzium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-kalzium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_kalzium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_kalzium_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_kalzium_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_kalzium_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### inr #########################################################################
```{r}
inr_flupirtinbasic_peak <- left_join(inr_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
 group_by(flupirtin) %>%  group_by(`Edited_BfArM Nummer2`) %>%   filter(labreads == max(labreads, na.rm = TRUE)) %>%  slice(1) %>% ungroup() %>%
#  filter(!attribute == "inr Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_inr_flupirtinbasic_peak <- inr_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_inr_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_inr_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion peak_inr for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-inr ",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_inr_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_inr_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/ld_inr_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_inr_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_inr_flupirtinbasic_peak <- inr_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_inr_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_inr_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion peak-inr for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-inr ",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_inr_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_inr_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/li_inr_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_inr_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_inr_flupirtinbasic_peak <- inr_flupirtinbasic_peak %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_inr_flupirtinbasic_peak %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_inr_flupirtinbasic_peak,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion peak-inr for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "peak-inr ",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_inr_peak_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_inr_flupirtinbasic_peak$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots peak/nsaid seperated", showWarnings = FALSE)
svg("plots peak/nsaid seperated/lp_inr_peak_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_inr_peak_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


