---
title: "hospitalisation labvalues at time of dismiss"
output: html_document
date: "2024-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(readxl)
library(tidyr)
library(dplyr)
library(ggstatsplot)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
```



```{r}
library(readxl)
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/flupirtin cases")

flupirtin_basicdata <- read_excel("flupirtin dosedata.xlsx", sheet = 3)
flupirtin_basicdata
```



```{r}
gpt_flupirtin <- left_join(gpt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") 
  
gpt_flupirtin
```

###gpt###


```{r}
gpt_flupirtinbasic <- left_join(gpt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "GPT Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
gpt_flupirtinbasic
```


```{r}
library(dlookr)
gpt_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```

```{r}
t.test(
   labreads ~ flupirtin,
  data = gpt_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- gpt_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = gpt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion gpt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "GPT U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_gpt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(gpt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_gpt_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_gpt_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()

all_groups_gpt_comparison_of_flupirtin_vs_no_flupirtin_intake
```



```{r}

f1_diclo <- gpt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- gpt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(gpt_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "GPT U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- gpt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- gpt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(gpt_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "GPT U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- gpt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- gpt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(gpt_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "GPT U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_gpt_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```



### got ####################################################################################


```{r}
got_flupirtinbasic <- left_join(got_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "got Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
got_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = got_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- got_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = got_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion got for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "got U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_got_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(got_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_got_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_got_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- got_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- got_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(got_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "got U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- got_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- got_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(got_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "got U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- got_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- got_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(got_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "got U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_got_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### ggt ####################################################################################


```{r}
ggt_flupirtinbasic <- left_join(ggt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "ggt Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
ggt_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = ggt_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ggt_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ggt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion ggt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ggt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_ggt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ggt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_ggt_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_ggt_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- ggt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- ggt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(ggt_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ggt U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- ggt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- ggt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(ggt_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ggt U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- ggt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- ggt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(ggt_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ggt U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_ggt_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```



### ldh ####################################################################################


```{r}
ldh_flupirtinbasic <- left_join(ldh_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "ldh Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
ldh_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = ldh_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ldh_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ldh_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion ldh for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ldh U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_ldh_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ldh_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_ldh_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_ldh_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- ldh_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- ldh_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(ldh_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ldh U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- ldh_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- ldh_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(ldh_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ldh U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- ldh_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- ldh_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(ldh_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ldh U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_ldh_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### ck ####################################################################################


```{r}
ck_flupirtinbasic <- left_join(ck_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "ck Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
ck_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = ck_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ck_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ck_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion ck for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ck U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_ck_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ck_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_ck_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_ck_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- ck_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- ck_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(ck_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ck U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- ck_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- ck_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(ck_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ck U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- ck_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- ck_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(ck_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ck U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_ck_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### ptt ####################################################################################


```{r}
ptt_flupirtinbasic <- left_join(ptt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "ptt Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
ptt_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = ptt_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ptt_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ptt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion ptt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ptt sec.",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_ptt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ptt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_ptt_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_ptt_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- ptt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- ptt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(ptt_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ptt sec.",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- ptt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- ptt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(ptt_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ptt sec.",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- ptt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- ptt_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(ptt_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ptt sec.",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_ptt_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### leukozyten ####################################################################################


```{r}
leukozyten_flupirtinbasic <- left_join(leukozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "leukozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
leukozyten_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = leukozyten_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- leukozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = leukozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion leukozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "leukozyten cells/ul",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_leukozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(leukozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_leukozyten_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_leukozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- leukozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- leukozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(leukozyten_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "leukozyten cells/ul",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- leukozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- leukozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(leukozyten_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "leukozyten cells/ul",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- leukozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- leukozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(leukozyten_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "leukozyten cells/ul",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_leukozyten_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### thrombozyten ####################################################################################


```{r}
thrombozyten_flupirtinbasic <- left_join(thrombozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "thrombozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
thrombozyten_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = thrombozyten_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- thrombozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = thrombozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion thrombozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "thrombozyten cells/ul",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_thrombozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(thrombozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_thrombozyten_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_thrombozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- thrombozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- thrombozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(thrombozyten_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "thrombozyten cells/ul",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- thrombozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- thrombozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(thrombozyten_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "thrombozyten cells/ul",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- thrombozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- thrombozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(thrombozyten_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "thrombozyten cells/ul",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_thrombozyten_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### erythrozyten ####################################################################################


```{r}
erythrozyten_flupirtinbasic <- left_join(erythrozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "erythrozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
erythrozyten_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = erythrozyten_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- erythrozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = erythrozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion erythrozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "erythrozyten cells/ul",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_erythrozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(erythrozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_erythrozyten_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_erythrozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- erythrozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- erythrozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(erythrozyten_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "erythrozyten cells/ul",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- erythrozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- erythrozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(erythrozyten_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "erythrozyten cells/ul",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- erythrozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- erythrozyten_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(erythrozyten_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "erythrozyten cells/ul",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_erythrozyten_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### hb ####################################################################################


```{r}
hb_flupirtinbasic <- left_join(hb_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "hb Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
hb_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = hb_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- hb_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = hb_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion hb for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "hb g/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_hb_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(hb_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_hb_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_hb_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- hb_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- hb_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(hb_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "hb g/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- hb_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- hb_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(hb_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "hb g/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- hb_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- hb_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(hb_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "hb g/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_hb_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### gesamteiweiß ####################################################################################


```{r}
gesamteiweiß_flupirtinbasic <- left_join(gesamteiweiß_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "gesamteiweiß Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
gesamteiweiß_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = gesamteiweiß_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- gesamteiweiß_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = gesamteiweiß_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion gesamteiweiß for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "gesamteiweiß g/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_gesamteiweiß_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(gesamteiweiß_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_gesamteiweiß_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_gesamteiweiß_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- gesamteiweiß_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- gesamteiweiß_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(gesamteiweiß_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "gesamteiweiß g/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- gesamteiweiß_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- gesamteiweiß_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(gesamteiweiß_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "gesamteiweiß g/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- gesamteiweiß_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- gesamteiweiß_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(gesamteiweiß_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "gesamteiweiß g/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_gesamteiweiß_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### ap ####################################################################################


```{r}
ap_flupirtinbasic <- left_join(ap_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "ap Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
ap_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = ap_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ap_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ap_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion ap for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ap U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_ap_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ap_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_ap_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_ap_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- ap_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- ap_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(ap_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ap U/L",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- ap_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- ap_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(ap_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ap U/L",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- ap_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- ap_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(ap_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "ap U/L",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_ap_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```

### total_bilirubin ####################################################################################


```{r}
total_bilirubin_flupirtinbasic <- left_join(total_bilirubin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "total_bilirubin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
total_bilirubin_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = total_bilirubin_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- total_bilirubin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = total_bilirubin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion total_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "total_bilirubin mg/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_total_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(total_bilirubin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_total_bilirubin_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_total_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- total_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- total_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(total_bilirubin_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "total_bilirubin mg/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- total_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- total_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(total_bilirubin_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "total_bilirubin mg/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- total_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- total_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(total_bilirubin_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "total_bilirubin mg/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_total_bilirubin_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### direct_bilirubin ####################################################################################


```{r}
direct_bilirubin_flupirtinbasic <- left_join(direct_bilirubin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "direct_bilirubin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
direct_bilirubin_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = direct_bilirubin_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- direct_bilirubin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = direct_bilirubin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion direct_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "direct_bilirubin mg/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_direct_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(direct_bilirubin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_direct_bilirubin_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_direct_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- direct_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- direct_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(direct_bilirubin_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "direct_bilirubin mg/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- direct_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- direct_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(direct_bilirubin_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "direct_bilirubin mg/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- direct_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- direct_bilirubin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(direct_bilirubin_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "direct_bilirubin mg/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_direct_bilirubin_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### kreatinin ####################################################################################


```{r}
kreatinin_flupirtinbasic <- left_join(kreatinin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "kreatinin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
kreatinin_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = kreatinin_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- kreatinin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = kreatinin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion kreatinin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kreatinin mg/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_kreatinin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(kreatinin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_kreatinin_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_kreatinin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- kreatinin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- kreatinin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(kreatinin_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "kreatinin mg/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- kreatinin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- kreatinin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(kreatinin_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "kreatinin mg/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- kreatinin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- kreatinin_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(kreatinin_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "kreatinin mg/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_kreatinin_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### harnstoff ####################################################################################


```{r}
harnstoff_flupirtinbasic <- left_join(harnstoff_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "harnstoff Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
harnstoff_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = harnstoff_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- harnstoff_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = harnstoff_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion harnstoff for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "harnstoff mg/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_harnstoff_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(harnstoff_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_harnstoff_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_harnstoff_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- harnstoff_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- harnstoff_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(harnstoff_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "harnstoff mg/dl",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- harnstoff_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- harnstoff_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(harnstoff_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "harnstoff mg/dl",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- harnstoff_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- harnstoff_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(harnstoff_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "harnstoff mg/dl",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_harnstoff_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### crp ####################################################################################


```{r}
crp_flupirtinbasic <- left_join(crp_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "crp Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
crp_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = crp_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- crp_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = crp_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion crp for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "crp mg/l",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_crp_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(crp_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_crp_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_crp_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- crp_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- crp_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(crp_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "crp mg/l",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- crp_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- crp_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(crp_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "crp mg/l",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- crp_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- crp_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(crp_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "crp mg/l",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_crp_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### natrium ####################################################################################


```{r}
natrium_flupirtinbasic <- left_join(natrium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "natrium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
natrium_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = natrium_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- natrium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = natrium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion natrium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "natrium mmol/l",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_natrium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(natrium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_natrium_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_natrium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- natrium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- natrium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(natrium_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "natrium mmol/l",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- natrium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- natrium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(natrium_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "natrium mmol/l",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- natrium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- natrium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(natrium_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "natrium mmol/l",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_natrium_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### kalium ####################################################################################


```{r}
kalium_flupirtinbasic <- left_join(kalium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "kalium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
kalium_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = kalium_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- kalium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = kalium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion kalium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kalium mmol/l",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_kalium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(kalium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_kalium_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_kalium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- kalium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- kalium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(kalium_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "kalium mmol/l",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- kalium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- kalium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(kalium_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "kalium mmol/l",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- kalium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- kalium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(kalium_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "kalium mmol/l",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_kalium_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### kalzium ####################################################################################


```{r}
kalzium_flupirtinbasic <- left_join(kalzium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "kalzium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
kalzium_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = kalzium_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- kalzium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = kalzium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion kalzium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kalzium mmol/l",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_kalzium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(kalzium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_kalzium_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_kalzium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- kalzium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- kalzium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(kalzium_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "kalzium mmol/l",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- kalzium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- kalzium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(kalzium_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "kalzium mmol/l",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- kalzium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- kalzium_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(kalzium_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "kalzium mmol/l",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_kalzium_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```


### quick ####################################################################################


```{r}
quick_flupirtinbasic <- left_join(quick_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "quick Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
quick_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = quick_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- quick_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = quick_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion quick for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "quick %",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_quick_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(quick_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_quick_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_quick_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- quick_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- quick_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(quick_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "quick %",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- quick_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- quick_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(quick_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "quick %",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- quick_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- quick_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(quick_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "quick %",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_quick_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```



### hämatokrit ####################################################################################


```{r}
hämatokrit_flupirtinbasic <- left_join(hämatokrit_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "hämatokrit Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
library(dlookr)
hämatokrit_flupirtinbasic %>% 
  group_by(flupirtin) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ flupirtin,
  data = hämatokrit_flupirtinbasic
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- hämatokrit_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = hämatokrit_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_Comparsion hämatokrit for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "hämatokrit %",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
all_groups_hämatokrit_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(hämatokrit_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/all groups_hämatokrit_viloin plot for flupirtin vs. no flupirtin intake.svg", height = 6, width = 8)
print(all_groups_hämatokrit_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



```{r}

f1_diclo <- hämatokrit_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo")
f1_diclo_counts <- f1_diclo %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f1_diclo <- hämatokrit_flupirtinbasic %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f1_diclo_counts, 
            aes(x = flupirtin, 
                y = max(hämatokrit_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "hämatokrit %",
    title = "Leber_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f2_ibu <- hämatokrit_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu")
f2_ibu_counts <- f2_ibu %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f2_ibu <- hämatokrit_flupirtinbasic %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f2_ibu_counts, 
            aes(x = flupirtin, 
                y = max(hämatokrit_flupirtinbasic$labreads) * 0.2, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "hämatokrit %",
    title = "Leber_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
f3_para <- hämatokrit_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para")
f3_para_counts <- f3_para %>% 
  group_by(flupirtin) %>%
  summarize(n_patients = n_distinct(`Edited_BfArM Nummer2`), .groups = "drop")
f3_para <- hämatokrit_flupirtinbasic %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =flupirtin, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  geom_text(data = f3_para_counts, 
            aes(x = flupirtin, 
                y = max(hämatokrit_flupirtinbasic$labreads) * 0.8, 
                label = paste0("n=", n_patients)),color = "red") +
  labs(
    x = "Comedication group",
    y = "hämatokrit %",
    title = "Leber_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```

```{r}
all_flupirtin <- f1_diclo+f2_ibu+f3_para

dir.create("plots", showWarnings = FALSE)
svg("plots/leber_hämatokrit_boxplot for flupirtin vs. no flupirtin intake.svg", height = 8, width = 12)
print(all_flupirtin)
dev.off()
```