---
title: "Untitled"
output: html_document
date: "2026-02-27"
---

```{r}
library(readxl)
library(tidyr)
library(dplyr)
library(ggstatsplot)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
```

```{r}
library(readxl)
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/flupirtin cases")

flupirtin_basicdata <- read_excel("flupirtin dosedata.xlsx", sheet = 3)
flupirtin_basicdata
```

### gpt #########################################################################


```{r}
gpt_full <- all_data %>% 
  filter(panel_id == "gpt")
```

```{r}
gpt_flupirtinbasic <- left_join(gpt_full, flupirtin_data, 
                                by = join_by("bf_ar_m_nummer"),
                                relationship = "many-to-many") %>% 
  drop_na() %>% 
  #filter(treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "gpt Day_Unknown") %>% 
 filter(!str_detect(attribute, "_krankheitsbeginn|DBS")) #%>% 
 #filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  #group_by(flupirtin) 
gpt_flupirtinbasic
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_gpt_flupirtinbasic <- gpt_flupirtinbasic %>%
  filter(treatment == "Leber_Diclo") 

n_patients <- ld_gpt_flupirtinbasic %>%
  distinct(bf_ar_m_nummer, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_gpt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion gpt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "gpt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_gpt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_gpt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

#dir.create("plots/nsaid seperated", showWarnings = FALSE)
#svg("plots/nsaid seperated/ld_gpt_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_gpt_comparison_of_flupirtin_vs_no_flupirtin_intake)
#dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_gpt_flupirtinbasic <- gpt_flupirtinbasic %>%
  filter(treatment == "Leber_Ibu") 

n_patients <- li_gpt_flupirtinbasic %>%
  distinct(bf_ar_m_nummer, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_gpt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion gpt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "gpt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_gpt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_gpt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

#dir.create("plots/nsaid seperated", showWarnings = FALSE)
#svg("plots/nsaid seperated/li_gpt_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_gpt_comparison_of_flupirtin_vs_no_flupirtin_intake)
#dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_gpt_flupirtinbasic <- gpt_flupirtinbasic %>%
  filter(treatment == "Leber_Para") 

n_patients <- lp_gpt_flupirtinbasic %>%
  distinct(bf_ar_m_nummer, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_gpt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion gpt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "gpt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_gpt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_gpt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

#dir.create("plots/nsaid seperated", showWarnings = FALSE)
#svg("plots/nsaid seperated/lp_gpt_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_gpt_comparison_of_flupirtin_vs_no_flupirtin_intake)
#dev.off()
```


### got #########################################################################
```{r}
got_flupirtinbasic <- left_join(got_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "got Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_got_flupirtinbasic <- got_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_got_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_got_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion got for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "got U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_got_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_got_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_got_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_got_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_got_flupirtinbasic <- got_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_got_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_got_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion got for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "got U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_got_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_got_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_got_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_got_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_got_flupirtinbasic <- got_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_got_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_got_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion got for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "got U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_got_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_got_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_got_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_got_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```



### ggt #########################################################################
```{r}
ggt_flupirtinbasic <- left_join(ggt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "ggt Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_ggt_flupirtinbasic <- ggt_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_ggt_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_ggt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion ggt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ggt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_ggt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_ggt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_ggt_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_ggt_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_ggt_flupirtinbasic <- ggt_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_ggt_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_ggt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion ggt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ggt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_ggt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_ggt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_ggt_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_ggt_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_ggt_flupirtinbasic <- ggt_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_ggt_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_ggt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion ggt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ggt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_ggt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_ggt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_ggt_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_ggt_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### ldh #########################################################################
```{r}
ldh_flupirtinbasic <- left_join(ldh_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "ldh Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_ldh_flupirtinbasic <- ldh_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_ldh_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_ldh_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion ldh for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ldh U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_ldh_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_ldh_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_ldh_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_ldh_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_ldh_flupirtinbasic <- ldh_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_ldh_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_ldh_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion ldh for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ldh U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_ldh_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_ldh_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_ldh_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_ldh_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_ldh_flupirtinbasic <- ldh_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_ldh_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_ldh_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion ldh for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ldh U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_ldh_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_ldh_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_ldh_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_ldh_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### ck #########################################################################
```{r}
ck_flupirtinbasic <- left_join(ck_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "ck Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_ck_flupirtinbasic <- ck_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_ck_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_ck_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion ck for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ck U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_ck_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_ck_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_ck_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_ck_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_ck_flupirtinbasic <- ck_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_ck_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_ck_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion ck for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ck U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_ck_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_ck_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_ck_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_ck_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_ck_flupirtinbasic <- ck_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_ck_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_ck_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion ck for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ck U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_ck_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_ck_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_ck_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_ck_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### ap #########################################################################
```{r}
ap_flupirtinbasic <- left_join(ap_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "ap Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_ap_flupirtinbasic <- ap_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_ap_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_ap_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion ap for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ap U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_ap_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_ap_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_ap_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_ap_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_ap_flupirtinbasic <- ap_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_ap_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_ap_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion ap for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ap U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_ap_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_ap_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_ap_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_ap_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_ap_flupirtinbasic <- ap_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_ap_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_ap_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion ap for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ap U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_ap_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_ap_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_ap_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_ap_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### quick #########################################################################
```{r}
quick_flupirtinbasic <- left_join(quick_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "quick Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_quick_flupirtinbasic <- quick_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_quick_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_quick_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion quick for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "quick (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_quick_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_quick_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_quick_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_quick_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_quick_flupirtinbasic <- quick_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_quick_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_quick_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion quick for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "quick (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_quick_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_quick_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_quick_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_quick_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_quick_flupirtinbasic <- quick_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_quick_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_quick_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion quick for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "quick (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_quick_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_quick_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_quick_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_quick_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### hämatokrit #########################################################################
```{r}
hämatokrit_flupirtinbasic <- left_join(hämatokrit_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "hämatokrit Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_hämatokrit_flupirtinbasic <- hämatokrit_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_hämatokrit_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_hämatokrit_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion hämatokrit for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "hämatokrit (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_hämatokrit_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_hämatokrit_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_hämatokrit_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_hämatokrit_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_hämatokrit_flupirtinbasic <- hämatokrit_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_hämatokrit_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_hämatokrit_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion hämatokrit for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "hämatokrit (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_hämatokrit_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_hämatokrit_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_hämatokrit_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_hämatokrit_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_hämatokrit_flupirtinbasic <- hämatokrit_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_hämatokrit_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_hämatokrit_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion hämatokrit for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "hämatokrit (%)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_hämatokrit_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_hämatokrit_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_hämatokrit_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_hämatokrit_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### ptt #########################################################################
```{r}
ptt_flupirtinbasic <- left_join(ptt_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "ptt Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_ptt_flupirtinbasic <- ptt_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_ptt_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_ptt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion ptt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ptt (Sec.)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_ptt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_ptt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_ptt_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_ptt_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_ptt_flupirtinbasic <- ptt_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_ptt_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_ptt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion ptt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ptt (Sec.)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_ptt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_ptt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_ptt_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_ptt_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_ptt_flupirtinbasic <- ptt_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_ptt_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_ptt_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion ptt for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "ptt (Sec.)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_ptt_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_ptt_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_ptt_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_ptt_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### leukozyten #########################################################################
```{r}
leukozyten_flupirtinbasic <- left_join(leukozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "leukozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_leukozyten_flupirtinbasic <- leukozyten_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_leukozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_leukozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion leukozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "leukozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_leukozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_leukozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_leukozyten_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_leukozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_leukozyten_flupirtinbasic <- leukozyten_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_leukozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_leukozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion leukozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "leukozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_leukozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_leukozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_leukozyten_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_leukozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_leukozyten_flupirtinbasic <- leukozyten_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_leukozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_leukozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion leukozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "leukozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_leukozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_leukozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_leukozyten_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_leukozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### erythrozyten #########################################################################
```{r}
erythrozyten_flupirtinbasic <- left_join(erythrozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "erythrozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_erythrozyten_flupirtinbasic <- erythrozyten_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_erythrozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_erythrozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion erythrozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "erythrozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_erythrozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_erythrozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_erythrozyten_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_erythrozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_erythrozyten_flupirtinbasic <- erythrozyten_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_erythrozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_erythrozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion erythrozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "erythrozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_erythrozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_erythrozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_erythrozyten_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_erythrozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_erythrozyten_flupirtinbasic <- erythrozyten_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_erythrozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_erythrozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion erythrozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "erythrozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_erythrozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_erythrozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_erythrozyten_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_erythrozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### thrombozyten #########################################################################
```{r}
thrombozyten_flupirtinbasic <- left_join(thrombozyten_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "thrombozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```

```{r}
thrombozyten_flupirtinbasic_long <- left_join(thrombozyten_long, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "thrombozyten Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```

```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_thrombozyten_flupirtinbasic <- thrombozyten_flupirtinbasic_long %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_thrombozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_thrombozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion thrombozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "thrombozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_thrombozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_thrombozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_thrombozyten_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_thrombozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_thrombozyten_flupirtinbasic <- thrombozyten_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_thrombozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_thrombozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion thrombozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "thrombozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_thrombozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_thrombozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_thrombozyten_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_thrombozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_thrombozyten_flupirtinbasic <- thrombozyten_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_thrombozyten_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_thrombozyten_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion thrombozyten for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "thrombozyten (cells/ul)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_thrombozyten_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_thrombozyten_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_thrombozyten_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_thrombozyten_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### hb #########################################################################
```{r}
hb_flupirtinbasic <- left_join(hb_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "hb Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_hb_flupirtinbasic <- hb_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_hb_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_hb_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion hb for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "hb (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_hb_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_hb_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_hb_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_hb_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_hb_flupirtinbasic <- hb_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_hb_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_hb_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion hb for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "hb (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_hb_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_hb_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_hb_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_hb_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_hb_flupirtinbasic <- hb_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_hb_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_hb_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion hb for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "hb (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_hb_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_hb_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_hb_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_hb_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### gesamteiweiß #########################################################################
```{r}
gesamteiweiß_flupirtinbasic <- left_join(gesamteiweiß_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "gesamteiweiß Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```

```{r}
gesamteiweiß_flupirtinbasic_long <- left_join(gesamteiweiß_long, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "gesamteiweiß Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```

```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_gesamteiweiß_flupirtinbasic <- gesamteiweiß_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_gesamteiweiß_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_gesamteiweiß_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion gesamteiweiß for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "gesamteiweiß (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_gesamteiweiß_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_gesamteiweiß_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_gesamteiweiß_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_gesamteiweiß_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_gesamteiweiß_flupirtinbasic <- gesamteiweiß_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_gesamteiweiß_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_gesamteiweiß_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion gesamteiweiß for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "gesamteiweiß (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_gesamteiweiß_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_gesamteiweiß_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_gesamteiweiß_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_gesamteiweiß_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_gesamteiweiß_flupirtinbasic <- gesamteiweiß_flupirtinbasic_long %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_gesamteiweiß_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_gesamteiweiß_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion gesamteiweiß for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "gesamteiweiß (g/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_gesamteiweiß_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_gesamteiweiß_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_gesamteiweiß_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_gesamteiweiß_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### total_bilirubin #########################################################################
```{r}
total_bilirubin_flupirtinbasic <- left_join(total_bilirubin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "total_bilirubin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_total_bilirubin_flupirtinbasic <- total_bilirubin_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_total_bilirubin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_total_bilirubin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion total_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "total_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_total_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_total_bilirubin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_total_bilirubin_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_total_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_total_bilirubin_flupirtinbasic <- total_bilirubin_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_total_bilirubin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_total_bilirubin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion total_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "total_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_total_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_total_bilirubin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_total_bilirubin_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_total_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_total_bilirubin_flupirtinbasic <- total_bilirubin_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_total_bilirubin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_total_bilirubin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion total_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "total_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_total_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_total_bilirubin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_total_bilirubin_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_total_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### direct_bilirubin #########################################################################
```{r}
direct_bilirubin_flupirtinbasic <- left_join(direct_bilirubin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "direct_bilirubin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_direct_bilirubin_flupirtinbasic <- direct_bilirubin_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_direct_bilirubin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_direct_bilirubin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion direct_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "direct_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_direct_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_direct_bilirubin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_direct_bilirubin_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_direct_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_direct_bilirubin_flupirtinbasic <- direct_bilirubin_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_direct_bilirubin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_direct_bilirubin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion direct_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "direct_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_direct_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_direct_bilirubin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_direct_bilirubin_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_direct_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_direct_bilirubin_flupirtinbasic <- direct_bilirubin_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_direct_bilirubin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_direct_bilirubin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion direct_bilirubin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "direct_bilirubin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_direct_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_direct_bilirubin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_direct_bilirubin_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_direct_bilirubin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### kreatinin #########################################################################
```{r}
kreatinin_flupirtinbasic <- left_join(kreatinin_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "kreatinin Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_kreatinin_flupirtinbasic <- kreatinin_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_kreatinin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_kreatinin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion kreatinin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kreatinin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_kreatinin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_kreatinin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_kreatinin_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_kreatinin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_kreatinin_flupirtinbasic <- kreatinin_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_kreatinin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_kreatinin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion kreatinin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kreatinin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_kreatinin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_kreatinin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_kreatinin_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_kreatinin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_kreatinin_flupirtinbasic <- kreatinin_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_kreatinin_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_kreatinin_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion kreatinin for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kreatinin (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_kreatinin_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_kreatinin_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_kreatinin_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_kreatinin_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### harnstoff #########################################################################
```{r}
harnstoff_flupirtinbasic <- left_join(harnstoff_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "harnstoff Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_harnstoff_flupirtinbasic <- harnstoff_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_harnstoff_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_harnstoff_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion harnstoff for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "harnstoff (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_harnstoff_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_harnstoff_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_harnstoff_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_harnstoff_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_harnstoff_flupirtinbasic <- harnstoff_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_harnstoff_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_harnstoff_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion harnstoff for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "harnstoff (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_harnstoff_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_harnstoff_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_harnstoff_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_harnstoff_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_harnstoff_flupirtinbasic <- harnstoff_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_harnstoff_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_harnstoff_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion harnstoff for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "harnstoff (mg/dl)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_harnstoff_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_harnstoff_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_harnstoff_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_harnstoff_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### crp #########################################################################
```{r}
crp_flupirtinbasic <- left_join(crp_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "crp Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_crp_flupirtinbasic <- crp_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_crp_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_crp_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion crp for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "crp (mg/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_crp_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_crp_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_crp_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_crp_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_crp_flupirtinbasic <- crp_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_crp_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_crp_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion crp for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "crp (mg/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_crp_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_crp_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_crp_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_crp_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_crp_flupirtinbasic <- crp_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_crp_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_crp_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion crp for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "crp (mg/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_crp_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_crp_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_crp_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_crp_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### natrium #########################################################################
```{r}
natrium_flupirtinbasic <- left_join(natrium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "natrium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```

```{r}
natrium_flupirtinbasic_long <- left_join(natrium_long, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "natrium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```

```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_natrium_flupirtinbasic <- natrium_flupirtinbasic_long %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_natrium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_natrium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion natrium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "natrium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_natrium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_natrium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_natrium_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_natrium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_natrium_flupirtinbasic <- natrium_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_natrium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_natrium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion natrium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "natrium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_natrium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_natrium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_natrium_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_natrium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_natrium_flupirtinbasic <- natrium_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_natrium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_natrium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion natrium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "natrium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_natrium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_natrium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_natrium_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_natrium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### kalium #########################################################################
```{r}
kalium_flupirtinbasic <- left_join(kalium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "kalium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_kalium_flupirtinbasic <- kalium_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_kalium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_kalium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion kalium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kalium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_kalium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_kalium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_kalium_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_kalium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_kalium_flupirtinbasic <- kalium_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_kalium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_kalium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion kalium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kalium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_kalium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_kalium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_kalium_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_kalium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_kalium_flupirtinbasic <- kalium_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_kalium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_kalium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion kalium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kalium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_kalium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_kalium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_kalium_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_kalium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### kalzium #########################################################################
```{r}
kalzium_flupirtinbasic <- left_join(kalzium_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "kalzium Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_kalzium_flupirtinbasic <- kalzium_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_kalzium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_kalzium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion kalzium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kalzium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_kalzium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_kalzium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_kalzium_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_kalzium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_kalzium_flupirtinbasic <- kalzium_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_kalzium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_kalzium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion kalzium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kalzium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_kalzium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_kalzium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_kalzium_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_kalzium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_kalzium_flupirtinbasic <- kalzium_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_kalzium_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_kalzium_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion kalzium for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "kalzium (mmol/l)",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_kalzium_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_kalzium_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_kalzium_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_kalzium_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


### inr #########################################################################
```{r}
inr_flupirtinbasic <- left_join(inr_full, flupirtin_basicdata, c = "`Edited_BfArM Nummer2`") %>% 
  drop_na() %>% 
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "inr Day_Unknown") %>% 
 filter(!str_detect(attribute, "_From Start|_From start|DBS"))%>% 
 filter(!grepl("SJS_ | Haut_", Treatment)) %>% 
  group_by(flupirtin) 
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
ld_inr_flupirtinbasic <- inr_flupirtinbasic %>%
  filter(Treatment == "Leber_Diclo") 

n_patients <- ld_inr_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_inr_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_Comparsion inr for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "inr ",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ld_all_groups_inr_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(ld_inr_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/ld_inr_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(ld_all_groups_inr_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
li_inr_flupirtinbasic <- inr_flupirtinbasic %>%
  filter(Treatment == "Leber_Ibu") 

n_patients <- li_inr_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_inr_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_Comparsion inr for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "inr ",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
li_all_groups_inr_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(li_inr_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/li_inr_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(li_all_groups_inr_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
lp_inr_flupirtinbasic <- inr_flupirtinbasic %>%
  filter(Treatment == "Leber_Para") 

n_patients <- lp_inr_flupirtinbasic %>%
  distinct(`Edited_BfArM Nummer2`, flupirtin) %>%  # nur einzigartige Patienten
  count(flupirtin, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_inr_flupirtinbasic,
  x = "flupirtin",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_Comparsion inr for flupirtin vs. no flupirtin intake",
  xlab = "Comedication group",
  ylab = "inr ",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
lp_all_groups_inr_comparison_of_flupirtin_vs_no_flupirtin_intake <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = flupirtin, 
        y = max(lp_inr_flupirtinbasic$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots/nsaid seperated", showWarnings = FALSE)
svg("plots/nsaid seperated/lp_inr_viloin plot for flupirtin vs. no flupirtin.svg", height = 6, width = 8)
print(lp_all_groups_inr_comparison_of_flupirtin_vs_no_flupirtin_intake)
dev.off()
```


