---
title: "Untitled"
output: html_document
date: "2025-09-30"
---

### Diclofenac - Cumulative dose patients count ##################################################################################


```{r}
dose_data3 <- dose_data %>%
  filter(
    Kathegorie == "Cummulative Dosis",
    Treatment == "Diclofenac",
    Attribut == "Leber_Diclo",
    Parameter != 0  # hier die 0 ausschließen
  )

dose_data3_count <- dose_data3 %>% 
  group_by(Parameter) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(Parameter, na.rm = TRUE),
    .groups = "drop"
  )

```

```{r}
liver_diclo_patients_count_for_cumulative_dose_below <- dose_data3_count %>% 
  filter(as.numeric(as.character(Parameter)) <= 1000) %>%  # nur Parameter ≤ 1000
  mutate(Parameter = as.factor(Parameter)) %>%
  ggplot(aes(x = Parameter, y = n_patients)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Patients count for cumulative dose of Diclofenac <1000mg",
    x = "Cumulative Dose (mg)",
    y = "Number of Patients"
  ) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_y_continuous(breaks = seq(0, max(dose_data3_count$n_patients), by = 1))

dir.create("plots_cumulative dose counts", showWarnings = FALSE)
svg("plots_cumulative dose counts/liver diclo_patients count for cumulative dose below 1000mg.svg", height = 6, width = 8)
print(liver_diclo_patients_count_for_cumulative_dose_below)
dev.off()
```

```{r}
liver_diclo_patients_count_for_cumulative_dose_above <- dose_data3_count %>% 
  filter(as.numeric(as.character(Parameter)) > 1000) %>%  # nur Parameter ≤ 1000
  mutate(Parameter = as.factor(Parameter)) %>%
  ggplot(aes(x = Parameter, y = n_patients)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Patients count for cumulative dose of Diclofenac >1000mg",
    x = "Cumulative Dose (mg)",
    y = "Number of Patients"
  ) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_y_continuous(breaks = seq(0, max(dose_data3_count$n_patients), by = 1))

dir.create("plots_cumulative dose counts", showWarnings = FALSE)
svg("plots_cumulative dose counts/liver diclo_patients count for cumulative dose above 1000mg.svg", height = 6, width = 8)
print(liver_diclo_patients_count_for_cumulative_dose_above)
dev.off()
```




```{r}
ld_cd_dosegroups <- dose_data3 %>%
  mutate(Dose_Group = cut(Parameter,
                          breaks = c(0, 500,1000,2500, 5000,10000,20000, Inf),
                          labels = c("50mg to 0.5g","0.5g to 1g","1g to 2.5g","2.5g to 5g", "5g to 10g", "10g to 20g", "20g < Higher"),
                          right = FALSE)) # right = FALSE to make intervals inclusive of lower bound and exclusive of upper bound

ld_cd_dosegroups_count <- ld_cd_dosegroups %>% 
  group_by(Dose_Group) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    .groups = "drop"
  )
```



```{r}
liver_diclo_frequency_of_Cumulative_Dose_Groups <- ggplot(ld_cd_dosegroups_count, aes(x = Dose_Group, y = n_patients)) +
  geom_bar(stat = "identity") +  # <- wichtig!
  labs(
    title = "liver_diclo Frequency of Cumulative Dose Groups",
    x = "Dose Group",
    y = "Number of Patients"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(margin = margin(b = 10), color = "black", face = "bold", hjust = 0.5),
    axis.text.x = element_text(face = "bold", angle = 45, hjust = 1))+
    scale_y_continuous(breaks = seq(0, max(ld_cd_dosegroups_count$n_patients), by = 1))

dir.create("plots_cumulative dose counts", showWarnings = FALSE)
svg("plots_cumulative dose counts/liver diclo_Frequency of Cumulative Dose Groups.svg", height = 6, width = 8)
print(liver_diclo_frequency_of_Cumulative_Dose_Groups)
dev.off()
```


### Ibuprofen - Cumulative dose patients count ##################################################################################


```{r}
dose_data3 <- dose_data %>%
  filter(
    Kathegorie == "Cummulative Dosis",
    Treatment == "Ibuprofen",
    Attribut == "Leber_Ibu",
    Parameter != 0  # hier die 0 ausschließen
  )

dose_data3_count <- dose_data3 %>% 
  group_by(Parameter) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(Parameter, na.rm = TRUE),
    .groups = "drop"
  )

```

```{r}
liver_ibu_patients_count_for_cumulative_dose_below <- dose_data3_count %>% 
  filter(as.numeric(as.character(Parameter)) <= 1000) %>%  # nur Parameter ≤ 1000
  mutate(Parameter = as.factor(Parameter)) %>%
  ggplot(aes(x = Parameter, y = n_patients)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Patients count for cumulative dose of Ibuprofen <1000mg",
    x = "Cumulative Dose (mg)",
    y = "Number of Patients"
  ) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_y_continuous(breaks = seq(0, max(dose_data3_count$n_patients), by = 1))

dir.create("plots_cumulative dose counts", showWarnings = FALSE)
svg("plots_cumulative dose counts/liver ibu_patients count for cumulative dose below 1000mg.svg", height = 6, width = 8)
print(liver_ibu_patients_count_for_cumulative_dose_below)
dev.off()
```

```{r}
liver_ibu_patients_count_for_cumulative_dose_above <- dose_data3_count %>% 
  filter(as.numeric(as.character(Parameter)) > 1000) %>%  # nur Parameter ≤ 1000
  mutate(Parameter = as.factor(Parameter)) %>%
  ggplot(aes(x = Parameter, y = n_patients)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Patients count for cumulative dose of Ibuprofen >1000mg",
    x = "Cumulative Dose (mg)",
    y = "Number of Patients"
  ) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_y_continuous(breaks = seq(0, max(dose_data3_count$n_patients), by = 1))

dir.create("plots_cumulative dose counts", showWarnings = FALSE)
svg("plots_cumulative dose counts/liver ibu_patients count for cumulative dose above 1000mg.svg", height = 6, width = 8)
print(liver_ibu_patients_count_for_cumulative_dose_above)
dev.off()
```




```{r}
li_cd_dosegroups <- dose_data3 %>%
  mutate(Dose_Group = cut(Parameter,
                          breaks = c(0, 500,1000,2500, 5000,10000,20000, Inf),
                          labels = c("50mg to 0.5g","0.5g to 1g","1g to 2.5g","2.5g to 5g", "5g to 10g", "10g to 20g", "20g < Higher"),
                          right = FALSE)) # right = FALSE to make intervals inclusive of lower bound and exclusive of upper bound

li_cd_dosegroups_count <- li_cd_dosegroups %>% 
  group_by(Dose_Group) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    .groups = "drop"
  )
```



```{r}
liver_ibu_frequency_of_Cumulative_Dose_Groups <- ggplot(li_cd_dosegroups_count, aes(x = Dose_Group, y = n_patients)) +
  geom_bar(stat = "identity") +  # <- wichtig!
  labs(
    title = "liver_ibu Frequency of Cumulative Dose Groups",
    x = "Dose Group",
    y = "Number of Patients"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(margin = margin(b = 10), color = "black", face = "bold", hjust = 0.5),
    axis.text.x = element_text(face = "bold", angle = 45, hjust = 1))+
    scale_y_continuous(breaks = seq(0, max(li_cd_dosegroups_count$n_patients), by = 1))

dir.create("plots_cumulative dose counts", showWarnings = FALSE)
svg("plots_cumulative dose counts/liver ibu_Frequency of Cumulative Dose Groups.svg", height = 6, width = 8)
print(liver_ibu_frequency_of_Cumulative_Dose_Groups)
dev.off()
```



### Paracetamol - Cumulative dose patients count ##################################################################################


```{r}
dose_data3 <- dose_data %>%
  filter(
    Kathegorie == "Cummulative Dosis",
    Treatment == "Paracetamol",
    Attribut == "Leber_Para",
    Parameter != 0  # hier die 0 ausschließen
  )

dose_data3_count <- dose_data3 %>% 
  group_by(Parameter) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(Parameter, na.rm = TRUE),
    .groups = "drop"
  )

```

```{r}
liver_para_patients_count_for_cumulative_dose_below <- dose_data3_count %>% 
  filter(as.numeric(as.character(Parameter)) <= 1000) %>%  # nur Parameter ≤ 1000
  mutate(Parameter = as.factor(Parameter)) %>%
  ggplot(aes(x = Parameter, y = n_patients)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Patients count for cumulative dose of paracetamol <1000mg",
    x = "Cumulative Dose (mg)",
    y = "Number of Patients"
  ) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_y_continuous(breaks = seq(0, max(dose_data3_count$n_patients), by = 1))

dir.create("plots_cumulative dose counts", showWarnings = FALSE)
svg("plots_cumulative dose counts/liver para_patients count for cumulative dose below 1000mg.svg", height = 6, width = 8)
print(liver_para_patients_count_for_cumulative_dose_below)
dev.off()
```

```{r}
liver_para_patients_count_for_cumulative_dose_above <- dose_data3_count %>% 
  filter(as.numeric(as.character(Parameter)) > 1000) %>%  # nur Parameter ≤ 1000
  mutate(Parameter = as.factor(Parameter)) %>%
  ggplot(aes(x = Parameter, y = n_patients)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Patients count for cumulative dose of paracetamol >1000mg",
    x = "Cumulative Dose (mg)",
    y = "Number of Patients"
  ) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_y_continuous(breaks = seq(0, max(dose_data3_count$n_patients), by = 1))

dir.create("plots_cumulative dose counts", showWarnings = FALSE)
svg("plots_cumulative dose counts/liver para_patients count for cumulative dose above 1000mg.svg", height = 6, width = 8)
print(liver_para_patients_count_for_cumulative_dose_above)
dev.off()
```




```{r}
lp_cd_dosegroups <- dose_data3 %>%
  mutate(Dose_Group = cut(Parameter,
                          breaks = c(0, 500,1000,2500, 5000,10000,20000, Inf),
                          labels = c("50mg to 0.5g","0.5g to 1g","1g to 2.5g","2.5g to 5g", "5g to 10g", "10g to 20g", "20g < Higher"),
                          right = FALSE)) # right = FALSE to make intervals inclusive of lower bound and exclusive of upper bound

lp_cd_dosegroups_count <- lp_cd_dosegroups %>% 
  group_by(Dose_Group) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    .groups = "drop"
  )
```



```{r}
liver_para_frequency_of_Cumulative_Dose_Groups <- ggplot(lp_cd_dosegroups_count, aes(x = Dose_Group, y = n_patients)) +
  geom_bar(stat = "identity") +  # <- wichtig!
  labs(
    title = "liver_para Frequency of Cumulative Dose Groups",
    x = "Dose Group",
    y = "Number of Patients"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(margin = margin(b = 10), color = "black", face = "bold", hjust = 0.5),
    axis.text.x = element_text(face = "bold", angle = 45, hjust = 1))+
    scale_y_continuous(breaks = seq(0, max(lp_cd_dosegroups_count$n_patients), by = 1))

dir.create("plots_cumulative dose counts", showWarnings = FALSE)
svg("plots_cumulative dose counts/liver para_Frequency of Cumulative Dose Groups.svg", height = 6, width = 8)
print(liver_para_frequency_of_Cumulative_Dose_Groups)
dev.off()
```

