---
title: "hospitalisation labvalues at time of dismiss"
output: html_document
date: "2024-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(readxl)
library(tidyr)
library(dplyr)
library(ggstatsplot)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
```




```{r}
library(readxl)
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/cholestatische hepatitis - mortalität (r-value)")

hcm_rawdata <- read_excel("r value rawdata.xlsx")
hcm_rawdata

```


```{r}
library(readxl)
setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/death")

mortality_rawdata <- read_excel("death statistic.xlsx", sheet = 2)
mortality_rawdata
```



```{r}
hcm_mortality <- left_join(hcm_rawdata, mortality_rawdata, c = "Edited_BfArM Nummer2") 
  
hcm_mortality
```




```{r}
hcm_mortality <- left_join(hcm_rawdata, mortality_rawdata, c = "Edited_BfArM Nummer2") %>% 
  drop_na()
#  filter(Treatment == "Leber_Diclo") %>% 
#  filter(!attribute == "GPT Day_Unknown") %>% 

hcm_mortality
```








```{r}

# Daten einlesen
#df <- read.csv(hcm_mortality, stringsAsFactors = FALSE)

# r_value und death als Faktoren umwandeln
hcm_mortality$r_value <- factor(hcm_mortality$r_value, levels = c("hepatocellular", "mixed_cholestatic"))
hcm_mortality$death <- factor(hcm_mortality$death, levels = c("no", "yes"))

# Kreuztabelle erstellen
table_r_death <- table(hcm_mortality$r_value, hcm_mortality$death)

# Ausgabe der Tabelle anzeigen
print(table_r_death)

# Chi-Quadrat-Test
chi_result <- chisq.test(table_r_death)
print(chi_result)

# Alternativ: Fisher-Test bei kleinen Stichproben
fisher_result <- fisher.test(table_r_death)
print(fisher_result)
```


```{r}

library(ggplot2)

ggplot(hcm_mortality, aes(x = r_value, fill = death)) +
  geom_bar(position = "fill") +  # Prozentuale Darstellung
  scale_y_continuous(labels = scales::percent) +
  labs(title = "all groups_relative ratio of death and r-value",
       x = "r-value",
       y = "death ratio",
       fill = "Death") +
  theme_minimal()
```


```{r}

ggplot(hcm_mortality, aes(x = r_value, fill = death)) +
  geom_bar(position = "dodge") +
  labs(title = "all groups_absolute ratio of death and r-value",
       x = "r-value",
       y = "death ratio",
       fill = "Death") +
  theme_minimal()
```

