---
title: "Untitled"
output: html_document
date: "2026-03-15"
---

```{r}
library(GGally)
library(dplyr)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(ggstatsplot)
library(ggplot2)
library(performance)
library(car)
```

```{r}

setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/hospitalisation")

hospitalisation_time_data <- read_excel("hospitalisation rawdata.xlsx", sheet = 3)  

#lvdiclo_dosedata <- dose_data %>% 
#  filter(Attribut == "Leber_Diclo") %>% 
#  rename( "Edited_BfArM Nummer2" ="BfArM Nummer_2" )

#lvdiclo_dosedata
hospitalisation_time_data
```



```{r}
# Häufigkeit jedes Wertes zählen
diclo_value_counts <- hospitalisation_time_data %>%
  count(diclo, name = "Anzahl")

# Ergebnis anzeigen
print(diclo_value_counts)
```

```{r}
ggplot(diclo_value_counts, aes(x = diclo, y = Anzahl)) +
  geom_col(fill = "steelblue") +           # Balkenfarbe
  geom_text(aes(label = Anzahl),           # Werte über den Balken
            vjust = -0.3, size = 3.5) +
  scale_y_continuous(limits = c(0, 20)) + 
  labs(
    x = "Time from diagnosis to hospitalisation (days)",                          # X-Achse beschriften
    y = "Number of Patients",              # Y-Achse beschriften
    title = "Diclofenac_time from diagnosis to hospitalisation"       # Titel des Diagramms
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) # X-Werte kippen für bessere Lesbarkeit
```

## Ibuprofen

```{r}
# Häufigkeit jedes Wertes zählen
ibu_value_counts <- hospitalisation_time_data %>%
  count(ibu, name = "Anzahl")

# Ergebnis anzeigen
print(ibu_value_counts)
```

```{r}
ggplot(ibu_value_counts, aes(x = ibu, y = Anzahl)) +
  geom_col(fill = "steelblue") +           # Balkenfarbe
  geom_text(aes(label = Anzahl),           # Werte über den Balken
            vjust = -0.3, size = 3.5) +
  scale_y_continuous(limits = c(0, 20)) + 
  labs(
    x = "Time from diagnosis to hospitalisation (days)",                          # X-Achse beschriften
    y = "Number of Patients",              # Y-Achse beschriften
    title = "Ibuprofen_time from diagnosis to hospitalisation"       # Titel des Diagramms
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) # X-Werte kippen für bessere Lesbarkeit
```


## Paracetamol

```{r}
# Häufigkeit jedes Wertes zählen
para_value_counts <- hospitalisation_time_data %>%
  count(para, name = "Anzahl")

# Ergebnis anzeigen
print(para_value_counts)
```

```{r}
ggplot(para_value_counts, aes(x = para, y = Anzahl)) +
  geom_col(fill = "steelblue") +           # Balkenfarbe
  geom_text(aes(label = Anzahl),           # Werte über den Balken
            vjust = -0.3, size = 3.5) +
  scale_y_continuous(limits = c(0, 10)) + 
  labs(
    x = "Time from diagnosis to hospitalisation (days)",                          # X-Achse beschriften
    y = "Number of Patients",              # Y-Achse beschriften
    title = "Paracetamol_time from diagnosis to hospitalisation"       # Titel des Diagramms
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) # X-Werte kippen für bessere Lesbarkeit
```




```{r}

setwd("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/hospitalisation")

hospitalisation_data <- read_excel("hospitalisation rawdata.xlsx", sheet = 1)  

#lvdiclo_dosedata <- dose_data %>% 
#  filter(Attribut == "Leber_Diclo") %>% 
#  rename( "Edited_BfArM Nummer2" ="BfArM Nummer_2" )

#lvdiclo_dosedata
hospitalisation_data
```

```{r}
hospitalisation_data_filter <- hospitalisation_data %>%
  filter(!(hospitalisation == "unknown")) %>%
  dplyr::select(1,4)
hospitalisation_data_filter

gpt_hosp <- left_join(hospitalisation_data_filter, gpt_full, by = ("Edited_BfArM Nummer2"))
gpt_hosp
```



```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- gpt_hosp %>%
  distinct(`Edited_BfArM Nummer2`, hospitalisation) %>%  # nur einzigartige Patienten
  count(hospitalisation, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = gpt_hosp,
  x = "hospitalisation",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "All groups_gpt_comparison ambulant vs. stationary treated patients",
  xlab = "Patient group",
  ylab = "gpt (u/l)",
  messages = FALSE
)

# Schritt 3: N-Werte oberhalb der Violinenplots_all_labvalues einfügen
all_groups_gpt_comparison_stat_amb <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = hospitalisation, 
        y = max(gpt_hosp$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

all_groups_gpt_comparison_stat_amb
#dir.create("plots_all_labvalues", showWarnings = FALSE)
#svg("plots_all_labvalues/all_ldh_full_comparison_diabetic_vs_nondiabetic.svg", height = 8, width = 6.5)
#print(liver_ldh_full_comparison_diabetic_vs_nondiabetic)
#dev.off()
```

```{r}
ld_gpt_hosp <- gpt_hosp  %>%
  filter(!(Treatment == "Leber_Diclo"))
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ld_gpt_hosp %>%
  distinct(`Edited_BfArM Nummer2`, hospitalisation) %>%  # nur einzigartige Patienten
  count(hospitalisation, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ld_gpt_hosp,
  x = "hospitalisation",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo_gpt_comparison ambulant vs. stationary treated patients",
  xlab = "Patient group",
  ylab = "gpt (u/l)",
  messages = FALSE
)

# Schritt 3: N-Werte oberhalb der Violinenplots_all_labvalues einfügen
ld_gpt_comparison_stat_amb <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = hospitalisation, 
        y = max(ld_gpt_hosp$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

ld_gpt_comparison_stat_amb
#dir.create("plots_all_labvalues", showWarnings = FALSE)
#svg("plots_all_labvalues/all_ldh_full_comparison_diabetic_vs_nondiabetic.svg", height = 8, width = 6.5)
#print(liver_ldh_full_comparison_diabetic_vs_nondiabetic)
#dev.off()
```


```{r}
li_gpt_hosp <- gpt_hosp  %>%
  filter(!(Treatment == "Leber_Ibu"))
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- li_gpt_hosp %>%
  distinct(`Edited_BfArM Nummer2`, hospitalisation) %>%  # nur einzigartige Patienten
  count(hospitalisation, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = li_gpt_hosp,
  x = "hospitalisation",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu_gpt_comparison ambulant vs. stationary treated patients",
  xlab = "Patient group",
  ylab = "gpt (u/l)",
  messages = FALSE
)

# Schritt 3: N-Werte oberhalb der Violinenplots_all_labvalues einfügen
ld_gpt_comparison_stat_amb <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = hospitalisation, 
        y = max(li_gpt_hosp$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

ld_gpt_comparison_stat_amb
#dir.create("plots_all_labvalues", showWarnings = FALSE)
#svg("plots_all_labvalues/all_ldh_full_comparison_diabetic_vs_nondiabetic.svg", height = 8, width = 6.5)
#print(liver_ldh_full_comparison_diabetic_vs_nondiabetic)
#dev.off()
```


```{r}
lp_gpt_hosp <- gpt_hosp  %>%
  filter(!(Treatment == "Leber_Para"))
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- lp_gpt_hosp %>%
  distinct(`Edited_BfArM Nummer2`, hospitalisation) %>%  # nur einzigartige Patienten
  count(hospitalisation, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = lp_gpt_hosp,
  x = "hospitalisation",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para_gpt_comparison ambulant vs. stationary treated patients",
  xlab = "Patient group",
  ylab = "gpt (u/l)",
  messages = FALSE
)

# Schritt 3: N-Werte oberhalb der Violinenplots_all_labvalues einfügen
ld_gpt_comparison_stat_amb <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = hospitalisation, 
        y = max(lp_gpt_hosp$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

ld_gpt_comparison_stat_amb
#dir.create("plots_all_labvalues", showWarnings = FALSE)
#svg("plots_all_labvalues/all_ldh_full_comparison_diabetic_vs_nondiabetic.svg", height = 8, width = 6.5)
#print(liver_ldh_full_comparison_diabetic_vs_nondiabetic)
#dev.off()
```

