---
title: "hospitalisation labvalues at time of dismiss"
output: html_document
date: "2024-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(readxl)
library(tidyr)
library(dplyr)
library(ggstatsplot)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(patchwork)
```



```{r}
suicide_data <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Suicide/suicide rawdata.xlsx", sheet = 1)%>% drop_na() 

suicide_data
```

```{r}
gpt_full
```

###GPT################

```{r}
gpt_suicide <- left_join(gpt_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
gpt_suicide
```

### Based on Patient number ###


```{r}
gpt_suicide %>% 
  filter(suicide == "suicide attempt") %>%
  filter(Treatment == "Leber_Ibu") %>% 
  group_by(`Edited_BfArM Nummer2`) %>%
  summarise(mean_labread = mean(labreads)) %>%
  ggplot(aes(x = `Edited_BfArM Nummer2`, y = mean_labread))+
  geom_col()+
  theme_classic()+
  labs(title = "Liver_Ibu_suicide attempt cases labvalues", hjust = 0.5,
       x = "Patients",
       y = "ALT u/l"
       )+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
   
  )

```

```{r}
gpt_suicide %>% 
  filter(suicide == "suicide attempt") %>%
  filter(Treatment == "Leber_Para") %>% 
  group_by(`Edited_BfArM Nummer2`) %>%
  summarise(mean_labread = mean(labreads)) %>%
  ggplot(aes(x = `Edited_BfArM Nummer2`, y = mean_labread))+
  geom_col()+
  theme_classic()+
  labs(title = "Liver_Para_suicide attempt cases labvalues", hjust = 0.5,
       x = "Patients",
       y = "ALT u/l"
       )+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
   
  )

```

```{r}
library(dlookr)
gpt_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```



```{r}
t.test(
   labreads ~ suicide,
  data = gpt_suicide
)
```



```{r}
library(ggstatsplot)

ggbetweenstats(
  data = gpt_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",
  title = "all groups_Comparsion of patients with and without sucicide attempt", # ALT for labvalue and daily dose",
       xlab = "Patient group",
       ylab = "ALT u/l") 

```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- gpt_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = gpt_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_gpt_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "GPT U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
gpt_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(gpt_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/gpt_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(gpt_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```



```{r}
p1_diclo <- gpt_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "GPT U/L",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- gpt_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "GPT U/L",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
p2_ibu_plot
```


```{r}
p3_para <- gpt_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "GPT U/L",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "gpt_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/gpt_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```



### got ################################################################

```{r}
got_suicide <- left_join(got_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
got_suicide
```



```{r}
library(dlookr)
got_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ suicide,
  data = got_suicide
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- got_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = got_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_got_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "got U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
got_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(got_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/got_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(got_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```


```{r}
p1_diclo <- got_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "got U/L",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- got_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "got U/L",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p3_para <- got_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "got U/L",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "got_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/got_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```


### ggt ################################################################

```{r}
ggt_suicide <- left_join(ggt_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
ggt_suicide
```



```{r}
library(dlookr)
ggt_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ suicide,
  data = ggt_suicide
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ggt_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ggt_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_ggt_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "ggt U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ggt_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(ggt_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/ggt_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(ggt_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```


```{r}
p1_diclo <- ggt_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "ggt U/L",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- ggt_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "ggt U/L",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p3_para <- ggt_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "ggt U/L",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "ggt_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/ggt_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```

### ck ################################################################

```{r}
ck_suicide <- left_join(ck_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
ck_suicide
```



```{r}
library(dlookr)
ck_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ suicide,
  data = ck_suicide
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ck_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ck_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_ck_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "ck U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ck_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(ck_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/ck_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(ck_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```


```{r}
p1_diclo <- ck_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "ck U/L",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- ck_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "ck U/L",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p3_para <- ck_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "ck U/L",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "ck_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/ck_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```



### ap ################################################################

```{r}
ap_suicide <- left_join(ap_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
ap_suicide
```



```{r}
library(dlookr)
ap_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ suicide,
  data = ap_suicide
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- ap_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = ap_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_ap_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "ap U/L",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
ap_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(ap_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/ap_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(ap_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```


```{r}
p1_diclo <- ap_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "ap U/L",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- ap_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "ap U/L",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p3_para <- ap_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "ap U/L",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "ap_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/ap_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```






### leukozyten ################################################################

```{r}
leukozyten_suicide <- left_join(leukozyten_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
leukozyten_suicide
```



```{r}
library(dlookr)
leukozyten_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ suicide,
  data = leukozyten_suicide
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- leukozyten_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = leukozyten_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_leukozyten_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "leukozyten cells/ul",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
leukozyten_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(leukozyten_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/leukozyten_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(leukozyten_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```


```{r}
p1_diclo <- leukozyten_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "leukozyten cells/ul",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- leukozyten_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "leukozyten cells/ul",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p3_para <- leukozyten_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "leukozyten cells/ul",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "leukozyten_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/leukozyten_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```







### hb ################################################################

```{r}
hb_suicide <- left_join(hb_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
hb_suicide
```



```{r}
library(dlookr)
hb_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ suicide,
  data = hb_suicide
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- hb_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = hb_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_hb_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "hb g/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
hb_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(hb_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/hb_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(hb_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```


```{r}
p1_diclo <- hb_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "hb g/dl",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- hb_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "hb g/dl",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p3_para <- hb_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "hb g/dl",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "hb_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/hb_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```





### total_bilirubin ################################################################

```{r}
total_bilirubin_suicide <- left_join(total_bilirubin_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
total_bilirubin_suicide
```



```{r}
library(dlookr)
total_bilirubin_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ suicide,
  data = total_bilirubin_suicide
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- total_bilirubin_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = total_bilirubin_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_total_bilirubin_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "total_bilirubin mg/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
total_bilirubin_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(total_bilirubin_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/total_bilirubin_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(total_bilirubin_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```


```{r}
p1_diclo <- total_bilirubin_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "total_bilirubin mg/dl",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- total_bilirubin_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "total_bilirubin mg/dl",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p3_para <- total_bilirubin_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "total_bilirubin mg/dl",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "total_bilirubin_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/total_bilirubin_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```




### kreatinin ################################################################

```{r}
kreatinin_suicide <- left_join(kreatinin_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
kreatinin_suicide
```



```{r}
library(dlookr)
kreatinin_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ suicide,
  data = kreatinin_suicide
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- kreatinin_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = kreatinin_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_kreatinin_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "kreatinin mg/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
kreatinin_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(kreatinin_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/kreatinin_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(kreatinin_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```


```{r}
p1_diclo <- kreatinin_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "kreatinin mg/dl",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- kreatinin_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "kreatinin mg/dl",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p3_para <- kreatinin_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "kreatinin mg/dl",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "kreatinin_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/kreatinin_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```


### harnstoff ################################################################

```{r}
harnstoff_suicide <- left_join(harnstoff_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
harnstoff_suicide
```



```{r}
library(dlookr)
harnstoff_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ suicide,
  data = harnstoff_suicide
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- harnstoff_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = harnstoff_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_harnstoff_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "harnstoff mg/dl",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
harnstoff_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(harnstoff_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/harnstoff_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(harnstoff_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```


```{r}
p1_diclo <- harnstoff_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "harnstoff mg/dl",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- harnstoff_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "harnstoff mg/dl",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p3_para <- harnstoff_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "harnstoff mg/dl",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "harnstoff_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/harnstoff_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```








### kalzium ################################################################

```{r}
kalzium_suicide <- left_join(kalzium_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
kalzium_suicide
```



```{r}
library(dlookr)
kalzium_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ suicide,
  data = kalzium_suicide
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- kalzium_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = kalzium_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_kalzium_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "kalzium mmol/l",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
kalzium_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(kalzium_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/kalzium_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(kalzium_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```


```{r}
p1_diclo <- kalzium_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "kalzium mmol/l",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- kalzium_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "kalzium mmol/l",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p3_para <- kalzium_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "kalzium mmol/l",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "kalzium_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/kalzium_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```


### quick ################################################################

```{r}
quick_suicide <- left_join(quick_full, suicide_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute)) %>% 
  group_by(suicide) 
#%>% 
  #summarise(mean_labread = mean(labreads),
            #(sd_labread = sd(labreads)))
quick_suicide
```



```{r}
library(dlookr)
quick_suicide %>% 
  group_by(suicide) %>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ suicide,
  data = quick_suicide
)
```


```{r}
# Schritt 1: Anzahl einzigartiger Patienten pro Diabetes-Gruppe berechnen
n_patients <- quick_suicide %>%
  distinct(`Edited_BfArM Nummer2`, suicide) %>%  # nur einzigartige Patienten
  count(suicide, name = "n") %>%
  mutate(label = paste0("N = ", n))

# Schritt 2: ggbetweenstats-Plot erstellen
plot_without_count <- ggbetweenstats(
  data = quick_suicide,
  x = "suicide",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "all groups_quick_full_violin plot for suicide attempt patients",
  xlab = "Patient group",
  ylab = "quick %",
  messages = FALSE)

# Schritt 3: N-Werte oberhalb der Violinenplots einfügen
quick_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt <- plot_without_count+ 
  geom_text(
    data = n_patients,
    aes(x = suicide, 
        y = max(quick_suicide$labreads, na.rm = TRUE) * 1.05,  # Position leicht oberhalb
        label = label),
    inherit.aes = FALSE,
    size = 4
  )

dir.create("plots", showWarnings = FALSE)
svg("plots/quick_all groups_full_violin plot for patients with and without suicide attempt.svg", height = 6, width = 8)
print(quick_all_groups_full_violin_plot_for_patients_with_and_without_suicide_attempt)
dev.off()
```


```{r}
p1_diclo <- quick_suicide %>% 
  filter(Treatment == "Leber_Diclo")

# n & ymax pro Gruppe berechnen
p1_diclo_counts <- p1_diclo %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p1_diclo_plot <- p1_diclo %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p1_diclo_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "quick %",
    title = "Leber Diclo"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p2_ibu <- quick_suicide %>% 
  filter(Treatment == "Leber_Ibu")

# n & ymax pro Gruppe berechnen
p2_ibu_counts <- p2_ibu %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p2_ibu_plot <- p2_ibu %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p2_ibu_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "quick %",
    title = "Leber Ibu"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
p3_para <- quick_suicide %>% 
  filter(Treatment == "Leber_Para")

# n & ymax pro Gruppe berechnen
p3_para_counts <- p3_para %>% 
  group_by(suicide) %>%
  summarize(
    n_patients = n_distinct(`Edited_BfArM Nummer2`),
    ymax = max(labreads, na.rm = TRUE),
    .groups = "drop"
  )

# Plot erstellen
p3_para_plot <- p3_para %>% 
  ggplot(aes(x = suicide, y = labreads)) +
  geom_boxplot() +
  geom_jitter(color = "red", width = 0.2, height = 0) +
  geom_text(data = p3_para_counts, 
            aes(x = suicide, 
                y = ymax, 
                label = paste0("n=", n_patients)), 
            color = "red", 
            vjust = -0.5) +  # leicht über dem Maximum
  labs(
    x = "Patient group",
    y = "quick %",
    title = "Leber Para"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5)
  )
```


```{r}
all_suicide <- p1_diclo_plot+p2_ibu_plot+p3_para_plot +
  plot_annotation(title = "quick_full_boxplot for suicide attempt patients")

dir.create("plots", showWarnings = FALSE)
svg("plots/quick_full_boxplot for suicide attempt patients.svg", height = 8, width = 12)
print(all_suicide)
dev.off()
```




