---
title: "Untitled"
output: html_document
date: "2026-02-20"
---




```{r}
library(readxl)
library(tidyr)
library(dplyr)
library(ggstatsplot)
library(tidyverse)
library(readxl)
library(dlookr)
library(reshape2)
library(dlookr)
```



```{r}
diabetic_data <- read_excel("E:/Daten(x)/Daten(lw-r)/Abc/Doktorarbeit SJS/Analyse R-Statistics/Diabetes/Diabetes rawdata.xlsx", sheet = 2)%>% drop_na() 

diabetic_data
```



```{r}
gpt_diabetic <- left_join(gpt_full, diabetic_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
#  filter(Diabetes == "Diabetic") %>% 
#  filter(!attribute == "GPT Day_Unknown") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute))# %>% 
#  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
#  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
#  slice(1) %>% 
#  ungroup()

gpt_diabetic 
```


```{r}
gpt_diabetic_day13_peak <- gpt_diabetic %>% 
  filter(attribute %in% c("GPT Day1", "GPT Day2", "GPT Day3")) %>%
  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
gpt_diabetic_day13_peak
```


```{r}
gpt_diabetic_timecouse_peak <- gpt_diabetic %>% 
  group_by(`Edited_BfArM Nummer2`) %>%
  filter(n_distinct(attribute) >= 3) %>%
  ungroup() %>%
  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()

gpt_diabetic_timecouse_peak
```

```{r}
gpt_diabetic_pruned_peak <- bind_rows(gpt_diabetic_day13_peak,  gpt_diabetic_timecouse_peak) %>%
  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
gpt_diabetic_pruned_peak
```




### Based on Patient number ###

```{r}
gpt_diabetic_pruned_peak1 <- gpt_diabetic_pruned_peak %>% 
  filter(Diabetes == "Diabetic") 

liver_gpt_full_diabetic_pruned_peak_cases_labvalues <-  ggplot(
  data = gpt_diabetic_pruned_peak1,
  aes(x = `Edited_BfArM Nummer2`, y = labreads)) +
  geom_col(width = 0.2)+
  theme_classic()+
  labs(title = "Liver_diabetic_cases pruned peak gpt", hjust = 0.5,
      x = "Patients",
      y = "Peak-gpt (u/l)")+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
liver_gpt_full_diabetic_pruned_peak_cases_labvalues
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_gpt_pruned peak labvalues.svg", height = 7, width = 10)
print(liver_gpt_full_diabetic_pruned_peak_cases_labvalues)
dev.off()
```



```{r}
gpt_diabetic_pruned_peak2 <- gpt_diabetic_pruned_peak %>% 
  filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute))

gpt_diabetic_pruned_peak2$attribute <-  factor(gpt_diabetic_pruned_peak2$attribute, 
                                   levels = c( "GPT Day1", "GPT Day2", "GPT Day3","GPT Day4","GPT Day5", "GPT Day6","GPT Day7","GPT Day8","GPT Day9","GPT Day10", "GPT Day11","GPT Day12","GPT Day13","GPT Day14","GPT Day15","GPT Day16","GPT Day17","GPT Day18","GPT Day19","GPT Day20","GPT Day21","GPT Day22","GPT Day23","GPT Day24","GPT Day25","GPT Day26","GPT Day27","GPT Day28","GPT Day29","GPT Day30","GPT Day31","GPT Day32","GPT Day33","GPT Day34","GPT Day35","GPT Day36","GPT Day37","GPT Day38","GPT Day39","GPT Day40","GPT Day41","GPT Day42","GPT Day43","GPT Day44","GPT Day45","GPT Day46","GPT Day47","GPT Day48","GPT Day49","GPT Day50","GPT Day51","GPT Day52","GPT Day53","GPT Day54","GPT Day55","GPT Day56","GPT Day57","GPT Day58","GPT Day59","GPT Day60","GPT Day61","GPT Day62","GPT Day63","GPT Day64","GPT Day65","GPT Day66","GPT Day67","GPT Day68","GPT Day69","GPT Day70","GPT Day71","GPT Day72","GPT Day73","GPT Day74","GPT Day75","GPT Day76","GPT Day77","GPT Day78","GPT Day79","GPT Day80","GPT Day81","GPT Day82","GPT Day83","GPT Day84","GPT Day85","GPT Day86","GPT Day87","GPT Day88","GPT Day89","GPT Day90","GPT Day91","GPT Day92","GPT Day93","GPT Day94","GPT Day95","GPT Day96","GPT Day97","GPT Day98","GPT Day99","GPT Day100"))
ld_gpt_mean_of_peak_labvalues_time <- gpt_diabetic_pruned_peak2 %>%
  ggplot(aes(x = attribute, y = labreads))+
  geom_col()+
  theme_classic()+
  labs(title = "liver_diabetic_cases mean of all pruned peak-gpt", hjust = 0.5,
       x = "Day of measurement",
       y = "Peak-gpt (u/l)"
       )+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) 
ld_gpt_mean_of_peak_labvalues_time
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_gpt_mean_of_peak_labvalues_time.svg", height = 7, width = 10)
print(ld_gpt_mean_of_peak_labvalues_time)
dev.off()
```


```{r}
gpt_diabetic_pruned_peak %>% 
  group_by(Diabetes)%>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ Diabetes,
  data = gpt_diabetic_pruned_peak)
```

### violin plots ###
```{r}
liver_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = gpt_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "All Groups: Comparison of pruned peak-gpt for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-gpt (u/l)",
  messages = FALSE
)
liver_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_gpt_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(liver_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
ld_gpt_diabetic_pruned_peak <- gpt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Diclo")

ld_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = ld_gpt_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo Comparison of pruned peak-gpt for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-gpt (u/l)",
  messages = FALSE
)
ld_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/ld_gpt_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(ld_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
li_gpt_diabetic_pruned_peak <- gpt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Ibu")

li_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = li_gpt_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu Comparison of pruned peak-gpt for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-gpt (u/l)",
  messages = FALSE
)
li_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/li_gpt_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(li_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
lp_gpt_diabetic_pruned_peak <- gpt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Para")

lp_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = lp_gpt_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para Comparison of pruned peak-gpt for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-gpt (u/l)",
  messages = FALSE
)
lp_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/lp_gpt_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(lp_gpt_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
p1_diclo <- gpt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =Diabetes, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  labs(
    x = "Patient group",
    y = "Peak-gpt (U/L)",
    title = "Liver_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
p2_ibu <- gpt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =Diabetes, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  labs(
    x = "Patient group",
    y = "Peak-gpt (U/L)",
    title = "Liver_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
p3_para <- gpt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =Diabetes, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  labs(
    x = "Patient group",
    y = "Peak-gpt (U/L)",
    title = "Liver_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
liver_gpt_full_boxplot_diabetic_peak_vs_nondiabetic <- p1_diclo+p2_ibu+p3_para

dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_gpt_boxplot pruned peak diabetic vs. nondiabetic.svg", height = 7, width = 12)
print(liver_gpt_full_boxplot_diabetic_peak_vs_nondiabetic)
dev.off()
```

### got #########################################################################
#################################################################################

```{r}
got_diabetic <- left_join(got_full, diabetic_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
#  filter(Diabetes == "Diabetic") %>% 
#  filter(!attribute == "GOT Day_Unknown") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute))# %>% 
#  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
#  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
#  slice(1) %>% 
#  ungroup()

got_diabetic 
```


```{r}
got_diabetic_day13_peak <- got_diabetic %>% 
  filter(attribute %in% c("GOT Day1", "GOT Day2", "GOT Day3")) %>%
  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
got_diabetic_day13_peak
```


```{r}
got_diabetic_timecouse_peak <- got_diabetic %>% 
  group_by(`Edited_BfArM Nummer2`) %>%
  filter(n_distinct(attribute) >= 3) %>%
  ungroup() %>%
  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()

got_diabetic_timecouse_peak
```

```{r}
got_diabetic_pruned_peak <- bind_rows(got_diabetic_day13_peak,  got_diabetic_timecouse_peak) %>%
  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
got_diabetic_pruned_peak
```




### Based on Patient number ###

```{r}
got_diabetic_pruned_peak1 <- got_diabetic_pruned_peak %>% 
  filter(Diabetes == "Diabetic") 

liver_got_full_diabetic_pruned_peak_cases_labvalues <-  ggplot(
  data = got_diabetic_pruned_peak1,
  aes(x = `Edited_BfArM Nummer2`, y = labreads)) +
  geom_col(width = 0.2)+
  theme_classic()+
  labs(title = "Liver_diabetic_cases pruned peak got", hjust = 0.5,
      x = "Patients",
      y = "Peak-got (u/l)")+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
liver_got_full_diabetic_pruned_peak_cases_labvalues
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_got_pruned peak labvalues.svg", height = 7, width = 10)
print(liver_got_full_diabetic_pruned_peak_cases_labvalues)
dev.off()
```



```{r}
got_diabetic_pruned_peak2 <- got_diabetic_pruned_peak %>% 
  filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute))

got_diabetic_pruned_peak2$attribute <-  factor(got_diabetic_pruned_peak2$attribute, 
                                   levels = c( "GOT Day1", "GOT Day2", "GOT Day3","GOT Day4","GOT Day5", "GOT Day6","GOT Day7","GOT Day8","GOT Day9","GOT Day10", "GOT Day11","GOT Day12","GOT Day13","GOT Day14","GOT Day15","GOT Day16","GOT Day17","GOT Day18","GOT Day19","GOT Day20","GOT Day21","GOT Day22","GOT Day23","GOT Day24","GOT Day25","GOT Day26","GOT Day27","GOT Day28","GOT Day29","GOT Day30","GOT Day31","GOT Day32","GOT Day33","GOT Day34","GOT Day35","GOT Day36","GOT Day37","GOT Day38","GOT Day39","GOT Day40","GOT Day41","GOT Day42","GOT Day43","GOT Day44","GOT Day45","GOT Day46","GOT Day47","GOT Day48","GOT Day49","GOT Day50","GOT Day51","GOT Day52","GOT Day53","GOT Day54","GOT Day55","GOT Day56","GOT Day57","GOT Day58","GOT Day59","GOT Day60","GOT Day61","GOT Day62","GOT Day63","GOT Day64","GOT Day65","GOT Day66","GOT Day67","GOT Day68","GOT Day69","GOT Day70","GOT Day71","GOT Day72","GOT Day73","GOT Day74","GOT Day75","GOT Day76","GOT Day77","GOT Day78","GOT Day79","GOT Day80","GOT Day81","GOT Day82","GOT Day83","GOT Day84","GOT Day85","GOT Day86","GOT Day87","GOT Day88","GOT Day89","GOT Day90","GOT Day91","GOT Day92","GOT Day93","GOT Day94","GOT Day95","GOT Day96","GOT Day97","GOT Day98","GOT Day99","GOT Day100"))
ld_got_mean_of_peak_labvalues_time <- got_diabetic_pruned_peak2 %>%
  ggplot(aes(x = attribute, y = labreads))+
  geom_col()+
  theme_classic()+
  labs(title = "liver_diabetic_cases mean of all pruned peak-got", hjust = 0.5,
       x = "Day of measurement",
       y = "Peak-got (u/l)"
       )+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) 
ld_got_mean_of_peak_labvalues_time
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_got_mean_of_peak_labvalues_time.svg", height = 7, width = 10)
print(ld_got_mean_of_peak_labvalues_time)
dev.off()
```


```{r}
got_diabetic_pruned_peak %>% 
  group_by(Diabetes)%>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ Diabetes,
  data = got_diabetic_pruned_peak)
```

### violin plots ###
```{r}
liver_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = got_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "All Groups: Comparison of pruned peak-got for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-got (u/l)",
  messages = FALSE
)
liver_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_got_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(liver_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
ld_got_diabetic_pruned_peak <- got_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Diclo")

ld_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = ld_got_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo Comparison of pruned peak-got for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-got (u/l)",
  messages = FALSE
)
ld_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/ld_got_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(ld_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
li_got_diabetic_pruned_peak <- got_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Ibu")

li_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = li_got_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu Comparison of pruned peak-got for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-got (u/l)",
  messages = FALSE
)
li_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/li_got_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(li_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
lp_got_diabetic_pruned_peak <- got_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Para")

lp_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = lp_got_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para Comparison of pruned peak-got for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-got (u/l)",
  messages = FALSE
)
lp_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/lp_got_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(lp_got_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
p1_diclo <- got_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =Diabetes, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  labs(
    x = "Patient group",
    y = "Peak-got (U/L)",
    title = "Liver_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
p2_ibu <- got_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =Diabetes, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  labs(
    x = "Patient group",
    y = "Peak-got (U/L)",
    title = "Liver_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
p3_para <- got_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =Diabetes, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  labs(
    x = "Patient group",
    y = "Peak-got (U/L)",
    title = "Liver_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
liver_got_full_boxplot_diabetic_peak_vs_nondiabetic <- p1_diclo+p2_ibu+p3_para

dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_got_boxplot pruned peak diabetic vs. nondiabetic.svg", height = 7, width = 12)
print(liver_got_full_boxplot_diabetic_peak_vs_nondiabetic)
dev.off()
```



### ggt #########################################################################
#################################################################################

```{r}
ggt_diabetic <- left_join(ggt_full, diabetic_data, c = "Edited_BfArM Nummer2") %>% 
  drop_na() %>% 
#  filter(Diabetes == "Diabetic") %>% 
#  filter(!attribute == "GGT Day_Unknown") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute))# %>% 
#  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
#  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
#  slice(1) %>% 
#  ungroup()

ggt_diabetic 
```


```{r}
ggt_diabetic_day13_peak <- ggt_diabetic %>% 
  filter(attribute %in% c("GGT Day1", "GGT Day2", "GGT Day3")) %>%
  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
ggt_diabetic_day13_peak
```


```{r}
ggt_diabetic_timecouse_peak <- ggt_diabetic %>% 
  group_by(`Edited_BfArM Nummer2`) %>%
  filter(n_distinct(attribute) >= 3) %>%
  ungroup() %>%
  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()

ggt_diabetic_timecouse_peak
```

```{r}
ggt_diabetic_pruned_peak <- bind_rows(ggt_diabetic_day13_peak,  ggt_diabetic_timecouse_peak) %>%
  group_by(Diabetes) %>%  group_by(`Edited_BfArM Nummer2`) %>%   
  filter(labreads == max(labreads, na.rm = TRUE)) %>%  
  slice(1) %>% 
  ungroup()
ggt_diabetic_pruned_peak
```




### Based on Patient number ###

```{r}
ggt_diabetic_pruned_peak1 <- ggt_diabetic_pruned_peak %>% 
  filter(Diabetes == "Diabetic") 

liver_ggt_full_diabetic_pruned_peak_cases_labvalues <-  ggplot(
  data = ggt_diabetic_pruned_peak1,
  aes(x = `Edited_BfArM Nummer2`, y = labreads)) +
  geom_col(width = 0.2)+
  theme_classic()+
  labs(title = "Liver_diabetic_cases pruned peak ggt", hjust = 0.5,
      x = "Patients",
      y = "Peak-ggt (u/l)")+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
liver_ggt_full_diabetic_pruned_peak_cases_labvalues
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_ggt_pruned peak labvalues.svg", height = 7, width = 10)
print(liver_ggt_full_diabetic_pruned_peak_cases_labvalues)
dev.off()
```



```{r}
ggt_diabetic_pruned_peak2 <- ggt_diabetic_pruned_peak %>% 
  filter(Diabetes == "Diabetic") %>% 
  filter(!grepl("_From Start|_From start|DBS", attribute))

ggt_diabetic_pruned_peak2$attribute <-  factor(ggt_diabetic_pruned_peak2$attribute, 
                                   levels = c( "GGT Day1", "GGT Day2", "GGT Day3","GGT Day4","GGT Day5", "GGT Day6","GGT Day7","GGT Day8","GGT Day9","GGT Day10", "GGT Day11","GGT Day12","GGT Day13","GGT Day14","GGT Day15","GGT Day16","GGT Day17","GGT Day18","GGT Day19","GGT Day20","GGT Day21","GGT Day22","GGT Day23","GGT Day24","GGT Day25","GGT Day26","GGT Day27","GGT Day28","GGT Day29","GGT Day30","GGT Day31","GGT Day32","GGT Day33","GGT Day34","GGT Day35","GGT Day36","GGT Day37","GGT Day38","GGT Day39","GGT Day40","GGT Day41","GGT Day42","GGT Day43","GGT Day44","GGT Day45","GGT Day46","GGT Day47","GGT Day48","GGT Day49","GGT Day50","GGT Day51","GGT Day52","GGT Day53","GGT Day54","GGT Day55","GGT Day56","GGT Day57","GGT Day58","GGT Day59","GGT Day60","GGT Day61","GGT Day62","GGT Day63","GGT Day64","GGT Day65","GGT Day66","GGT Day67","GGT Day68","GGT Day69","GGT Day70","GGT Day71","GGT Day72","GGT Day73","GGT Day74","GGT Day75","GGT Day76","GGT Day77","GGT Day78","GGT Day79","GGT Day80","GGT Day81","GGT Day82","GGT Day83","GGT Day84","GGT Day85","GGT Day86","GGT Day87","GGT Day88","GGT Day89","GGT Day90","GGT Day91","GGT Day92","GGT Day93","GGT Day94","GGT Day95","GGT Day96","GGT Day97","GGT Day98","GGT Day99","GGT Day100"))
ld_ggt_mean_of_peak_labvalues_time <- ggt_diabetic_pruned_peak2 %>%
  ggplot(aes(x = attribute, y = labreads))+
  geom_col()+
  theme_classic()+
  labs(title = "liver_diabetic_cases mean of all pruned peak-ggt", hjust = 0.5,
       x = "Day of measurement",
       y = "Peak-ggt (u/l)"
       )+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) 
ld_ggt_mean_of_peak_labvalues_time
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_ggt_mean_of_peak_labvalues_time.svg", height = 7, width = 10)
print(ld_ggt_mean_of_peak_labvalues_time)
dev.off()
```


```{r}
ggt_diabetic_pruned_peak %>% 
  group_by(Diabetes)%>% 
  normality(labreads)
```


```{r}
t.test(
   labreads ~ Diabetes,
  data = ggt_diabetic_pruned_peak)
```

### violin plots ###
```{r}
liver_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = ggt_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "All Groups: Comparison of pruned peak-ggt for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-ggt (u/l)",
  messages = FALSE
)
liver_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_ggt_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(liver_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
ld_ggt_diabetic_pruned_peak <- ggt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Diclo")

ld_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = ld_ggt_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_diclo Comparison of pruned peak-ggt for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-ggt (u/l)",
  messages = FALSE
)
ld_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/ld_ggt_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(ld_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
li_ggt_diabetic_pruned_peak <- ggt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Ibu")

li_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = li_ggt_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_ibu Comparison of pruned peak-ggt for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-ggt (u/l)",
  messages = FALSE
)
li_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/li_ggt_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(li_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
lp_ggt_diabetic_pruned_peak <- ggt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Para")

lp_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic <- ggbetweenstats(
  data = lp_ggt_diabetic_pruned_peak,
  x = "Diabetes",
  y = "labreads",
  type = "np",  # non-parametrisch
  title = "liver_para Comparison of pruned peak-ggt for Diabetic vs. Non-Diabetic Patients",
  xlab = "Patient group",
  ylab = "Peak-ggt (u/l)",
  messages = FALSE
)
lp_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic
dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/lp_ggt_violin diabetic vs nondiabetic pruned peak.svg", height = 6, width = 8)
print(lp_ggt_full_comparison_diabetic_pruned_peak_vs_nondiabetic)
dev.off()
```


```{r}
p1_diclo <- ggt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Diclo") %>% 
  ggplot(aes( x =Diabetes, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  labs(
    x = "Patient group",
    y = "Peak-ggt (U/L)",
    title = "Liver_Diclo" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
p2_ibu <- ggt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  ggplot(aes( x =Diabetes, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  labs(
    x = "Patient group",
    y = "Peak-ggt (U/L)",
    title = "Liver_Ibu" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
p3_para <- ggt_diabetic_pruned_peak %>% 
  filter(Treatment == "Leber_Para") %>% 
  ggplot(aes( x =Diabetes, y = labreads))+
  geom_boxplot()+
  geom_jitter(colour = "red")+
  labs(
    x = "Patient group",
    y = "Peak-ggt (U/L)",
    title = "Liver_Para" )+
  theme_classic()+
  theme(
    plot.title = element_text(size = 10, hjust =0.5)
  )
```


```{r}
liver_ggt_full_boxplot_diabetic_peak_vs_nondiabetic <- p1_diclo+p2_ibu+p3_para

dir.create("plots_pruned_peak", showWarnings = FALSE)
svg("plots_pruned_peak/liver_ggt_boxplot pruned peak diabetic vs. nondiabetic.svg", height = 7, width = 12)
print(liver_ggt_full_boxplot_diabetic_peak_vs_nondiabetic)
dev.off()
```

