---
title: "Untitled"
author: "Arun Kumar"
date: "2025-05-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(stringr)
```

## how the data looks likes ##
```{r}
rawdata <- read_excel("D:/Project R Folder/MyPhD/Doktorarbeit SJS/Exceltabellen/Interimsanalyse/sjsstudy/dosetable.xlsx")
rawdata
```


```{r}
headers <- read_excel("D:/Project R Folder/MyPhD/Doktorarbeit SJS/Exceltabellen/Interimsanalyse/sjsstudy/dosetable.xlsx",n_max =4 , col_names = FALSE)
headers
```

```{r}
combined_names <- paste(headers[2, ],headers[3, ],headers[4, ], sep = "_") %>%
  str_replace_all("_NA", "")
combined_names
```

```{r}
data <- read_excel("D:/Project R Folder/MyPhD/Doktorarbeit SJS/Exceltabellen/Interimsanalyse/sjsstudy/dosetable.xlsx",
                   skip = 4,col_names = combined_names)
data
```

```{r}
library(dplyr)
library(tidyr)

data %>% 
  pivot_longer(
    cols      = 3:42,
    names_to  = "full_name",    # temporary column
    values_to = "labreads"
  ) %>% 
  separate(
    col   = full_name,
    into  = c("treatment", "medication"),
    sep   = "_",
    extra = "merge",    # everything after the first “_” goes into `medication`
    fill  = "right"     # if there’s no underscore, `medication` will be NA
  )

```

```{r}
data_comedication_clean <- data %>% 
  pivot_longer(
        cols = 3:42,
        names_to    = c("drug", "medication", "group"),
        names_pattern = "([^_]+)_([^_]+)_(.*)",
        values_to   = "labreads") %>% 
  dplyr::rename("BfArM_Nummer2" = "number_BfArM Nummer_Edited_BfArM Nummer2",
                "category" = "categroy_Kathegorie_Treatment") %>% 
  drop_na(labreads)
  

data_comedication_clean
```


```{r}
data_comedication_clean %>% 
  mutate( treatment = as.factor(treatment),
          medication = as.factor(medication),
          kathegorie = as.factor(category)) %>%
  dplyr::select(treatment,medication, labreads) %>% 
  drop_na(labreads)%>%
  group_by(treatment, medication)%>%
  summarise(count = n()) %>%  
  dplyr::arrange(desc(count))
  
```


```{r}
data_comedication_clean %>% 
  dplyr::filter(BfArM_Nummer2 == "7072184")
```


```{r}
library(pdftools)
```

```{r}
pdf_text_data <- pdf_text("Diclofenac_DE_1993_SMQ_Hepatic_disorders.pdf")
pdf_text_data
```












```{r}
library(pdftools)
library(dplyr)

# Read PDF
#pdf_text_data <- pdf_text("your_file.pdf")

# Initialize an empty data frame
debfarm_df <- data.frame(
  page = integer(),
  line_number = integer(),
  text = character(),
  stringsAsFactors = FALSE
)

# Loop over pages
for (i in seq_along(pdf_text_data)) {
  lines <- unlist(strsplit(pdf_text_data[[i]], "\n"))
  match_idx <- grep("DE-BFARM", lines)
  
  if (length(match_idx) > 0) {
    matches <- data.frame(
      page = i,
      line_number = match_idx,
      text = lines[match_idx],
      stringsAsFactors = FALSE
    )
    
    debfarm_df <- bind_rows(debfarm_df, matches)
  }
}

# View the table
print(debfarm_df)

```












































































