---
title: "LIver_Ibu"
author: "Arun Kumar"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##GOT liver IBU
## here we merge gptlong data with dosetreatment
## create new column

```{r }
got_ibu_value_dose <- inner_join(got_long,dosetreatment, by="Edited_BfArM Nummer2")

got_ibu_value_dose$patient_dose <- paste0(got_ibu_value_dose$Treatment2, got_ibu_value_dose$`Edited_BfArM Nummer2`)



got_ibu_value_dose %>% mutate(Ibuprofen_Cumulative_Dosis = as.factor(Ibuprofen_Cumulative_Dosis)) %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  select(patient_dose,Ibuprofen_Cumulative_Dosis,labreads) %>% 
  group_by(patient_dose) %>% 
  drop_na() %>% 
  ggplot(aes(y = labreads, x= Ibuprofen_Cumulative_Dosis))+
  geom_point(position = position_dodge(width = 0.2))+
    labs(
    x = "Cumulative Dose (mg)",
    y = "GOT lab Values (mg)",
    title = "GOT in Liver Ibuprofen", hjust = 0.5)+
  #scale_y_continuous(limits = c(0,6000))+
  theme_classic()+
  theme(
    plot.title = element_text(margin = margin(b=10), 
                              color="black", face="bold", hjust = 0.5),
    axis.title.x = element_text(face= "bold", size = 15, colour = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y = element_text(face = "bold", size = 15, colour = "black"),
    legend.position = c(0.2,0.9),
    legend.text = element_text(size = 15, face = "bold"))

ggsave( "Visual_ibu/liveribu_got_cumulative1.png", plot=last_plot(), width = 8, height = 7, dpi = 600)

```

## got ibu Plots


```{r, echo=FALSE}
got_ibu_value_dose
```




```{r, echo=FALSE}
gpt_ibu_value_dose <- inner_join(gpt_long,dosetreatment, by="Edited_BfArM Nummer2")

gpt_ibu_value_dose$patient_dose <- paste0(gpt_ibu_value_dose$Treatment2, gpt_ibu_value_dose$`Edited_BfArM Nummer2`)

##plot
gpt_ibu_value_dose %>% mutate(Ibuprofen_Cumulative_Dosis = as.factor(Ibuprofen_Cumulative_Dosis)) %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  select(patient_dose,Ibuprofen_Cumulative_Dosis,labreads) %>% 
  group_by(patient_dose) %>% 
  drop_na() %>% 
  ggplot(aes(x = Ibuprofen_Cumulative_Dosis, y= labreads))+
  geom_point(position = position_dodge(width = 0.2))+
    labs(
    x = "Cumulative dose (mg)",
    y = "GPT Lab Values",
    title = "GPT in Liver Ibuprofen", hjust = 0.5)+
  #scale_y_continuous(limits = c(0,6000))+
  theme_classic()+
  theme(
    plot.title = element_text(margin = margin(b=10), 
                              color="black", face="bold", hjust = 0.5),
    axis.title.x = element_text(face= "bold", size = 15, colour = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y = element_text(face = "bold", size = 15, colour = "black"),
    legend.position = c(0.2,0.9),
    legend.text = element_text(size = 15, face = "bold"))

ggsave( "Visual_ibu/liveribu_gpt_cumulative1.png", plot=last_plot(), width = 8, height = 7, dpi = 600)


```

```{r, echo=FALSE}
thrombozyten_ibu_value_dose <- inner_join(thrombozyten_long,dosetreatment, by="Edited_BfArM Nummer2")

thrombozyten_ibu_value_dose$patient_dose <- paste0(thrombozyten_ibu_value_dose$Treatment2, thrombozyten_ibu_value_dose$`Edited_BfArM Nummer2`)

##plot
thrombozyten_ibu_value_dose %>% mutate(Ibuprofen_Cumulative_Dosis = as.factor(Ibuprofen_Cumulative_Dosis)) %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  select(patient_dose,Ibuprofen_Cumulative_Dosis,labreads) %>% 
  group_by(patient_dose) %>% 
  drop_na() %>% 
  ggplot(aes(x = Ibuprofen_Cumulative_Dosis, y= labreads))+
  geom_point(position = position_dodge(width = 0.2))+
    labs(
    x = "Cumulative dose (mg)",
    y = "thrombozyten Lab Values",
    title = "Thrombozyten in Liver Ibuprofen", hjust = 0.5)+
  #scale_y_continuous(limits = c(0,6000))+
  theme_classic()+
  theme(
    plot.title = element_text(margin = margin(b=10), 
                              color="black", face="bold", hjust = 0.5),
    axis.title.x = element_text(face= "bold", size = 15, colour = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y = element_text(face = "bold", size = 15, colour = "black"),
    legend.position = c(0.2,0.9),
    legend.text = element_text(size = 15, face = "bold"))

ggsave( "Visual_ibu/liveribu_thrombozyten_cumulative1.png", plot=last_plot(), width = 8, height = 7, dpi = 600)
```



```{r, echo=FALSE}
leukozyten_ibu_value_dose <- inner_join(leukozyten_long,dosetreatment, by="Edited_BfArM Nummer2")

leukozyten_ibu_value_dose$patient_dose <- paste0(leukozyten_ibu_value_dose$Treatment2, leukozyten_ibu_value_dose$`Edited_BfArM Nummer2`)

##plot
leukozyten_ibu_value_dose %>% mutate(Ibuprofen_Cumulative_Dosis = as.factor(Ibuprofen_Cumulative_Dosis)) %>% 
  filter(Treatment == "Leber_Ibu") %>% 
  select(patient_dose,Ibuprofen_Cumulative_Dosis,labreads) %>% 
  group_by(patient_dose) %>% 
  drop_na() %>% 
  ggplot(aes(x = Ibuprofen_Cumulative_Dosis, y= labreads))+
  geom_point(position = position_dodge(width = 0.2))+
    labs(
    x = "Cumulative dose (mg)",
    y = "Leukozyten Lab Values",
    title = "Leukozyten in Liver Ibuprofen", hjust = 0.5)+
  #scale_y_continuous(limits = c(0,6000))+
  theme_classic()+
  theme(
    plot.title = element_text(margin = margin(b=10), 
                              color="black", face="bold", hjust = 0.5),
    axis.title.x = element_text(face= "bold", size = 15, colour = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y = element_text(face = "bold", size = 15, colour = "black"),
    legend.position = c(0.2,0.9),
    legend.text = element_text(size = 15, face = "bold"))

ggsave( "Visual_ibu/liveribu_Leukozyten_cumulative1.png", plot=last_plot(), width = 8, height = 7, dpi = 600)
```




```{r, echo=FALSE}

```



```{r, echo=FALSE}

```





```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```







```{r, echo=FALSE}

```



































































































































































































































